### ISSUE TITLE
Missing CDN in website

### ISSUE THREAD

**Issue by vipulpandey7860** [Bookingjini-Labs/bookingjini-icons#101]
**Please describe the problem**
Website doesn't provide CDN link or any link that can lead the user to copy CDN. The users cannot use icons and thus is urgent to fix.

**Describe the solution you'd like**
We can add copy CDN button on the navbar or can give GitHub link on the navbar from where the user can get CDN.

**Screenshot**
<img width="959" alt="icons bug" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/53248489/121a64d4-8c11-4f06-b409-3034fc7fca36">

**Comment by vipulpandey7860** [comment]
please assign this to me

**Comment by bookingjini** [comment]
> I-VipulPandey

Thank you, @I-VipulPandey, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.
