### ISSUE TITLE
Improvement in the UI 

### ISSUE THREAD

**Issue by Hardikaz** [Bookingjini-Labs/bookingjini-icons#103]
Improving UI and adding more functionalities to it will make it more suitable for the users.

I would like to improve the way icons are displayed.

**Screenshot**

![Screenshot (150)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/95474096/b50371b6-efb6-4b2b-b211-486a621a41e7)

Please assign me this issue with respect to GSSoC'23. I will be very thankful to you.

**Comment by bookingjini** [comment]
> Hardikaz

Thank you, @Hardikaz, for your prompt reply. Could you please share a prototype or design sample illustrating the changes you intend to contribute? This will help us better understand the modifications you wish to make to the repository.

**Comment by Hardikaz** [comment]
# ok I will show it 
## Here is the design which I intend to implement here
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/95474096/20963b7a-d351-45ea-ab36-1dc991367a87)
- It would be awesome and more interactive when this type of UI will be there . 
- I will also include some hover and other functionalities to make it more live. 
- If you have suggestions regarding this I can add them too. After doing this I have more plans to contribute in this website.

**Comment by AshutoshDash1999** [comment]
Please go ahead. Follow the hover effect for both light and dark mode

**Comment by Hardikaz** [comment]
You want me to implement only hover effect?
Not proper borders and paddings?

**Comment by AshutoshDash1999** [comment]
if you wish you can improve the hover effect on icon card

**Comment by Hardikaz** [comment]
ok so I will do that . Thanks !
