### ISSUE TITLE
Adding a footer

### ISSUE THREAD

**Issue by Sakar95** [Bookingjini-Labs/bookingjini-icons#104]
Hey, @ramanujamgond  I want to add a footer which provides a professional look to the website

please assign me this under gssoc'23

![Screenshot 2023-05-25 004603](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/107045521/aaac12a3-2d8f-49dc-8f9d-6aca1bcb64b3)

**Comment by bookingjini** [comment]
> Sakar95

Thank you, @Sakar95, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by Sakar95** [comment]
Thanks for assigning Sir @bookingjini, I will surely submit the screenshot.

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.
