### ISSUE TITLE
Add LICENCE

### ISSUE THREAD

**Issue by Jiggy9** [Bookingjini-Labs/bookingjini-icons#106]
Hey, @AshutoshDash1999  I'm active GSSoC'23 contributor and I would like to add a license file to this repository. Please assign me to this issue. Thank you!

**Comment by bookingjini** [comment]
> Jiggy9

Thank you, @Jiggy9, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.
