### ISSUE TITLE
[new]: Adding hover effects in icon buttons in both modes

### ISSUE THREAD

**Issue by Ks103** [Bookingjini-Labs/bookingjini-icons#107]
**Please describe the problem**
Why do you want to add this feature?
As in dark mode the hover effect is dim and also in light mode the hover effect is not there 

**Describe the solution you'd like**
so there must be some good ui so that the color match to both modes. I request you to please assign me the task.

**Screenshot**
Please attach any relevant screenshot(s).

![Screenshot 2023-05-25 102447](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/86292101/aadafc2e-1a4b-4283-8214-71690bb985d6)
![Screenshot 2023-05-25 102516](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/86292101/c6e574b0-2b93-4497-9695-273fca9a0a51)

**Comment by bookingjini** [comment]
> Ks103

Thank you, @Ks103, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by Ks103** [comment]
I have made the changes in the code please check and verify

**Comment by Ks103** [comment]
attaching the ss 

![Screenshot 2023-05-25 203636](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/86292101/7ff361e6-c522-4586-9b25-eb5fad8c2330)
![Screenshot 2023-05-25 224220](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/86292101/a7cef873-291b-4cc8-86f1-ffb327132c75)

request you to please check the css code and merge the pr

**Comment by AshutoshDash1999** [comment]
@Ks103 this is not looking good. Please check some online examples for the same.

**Comment by PatilHarshh** [comment]
@AshutoshDash1999 may i proceed with this issue 

1) beautify the the tittle by Text effect
2) Making Search Bar good 
3) adding Feature of color of theme  on  change of color
