### ISSUE TITLE
[GSSOC'23] Adding a "how to use icons section"

### ISSUE THREAD

**Issue by kharshita590** [Bookingjini-Labs/bookingjini-icons#108]
**Please describe the problem**
Why do you want to add this feature?
I think most of the people wants to know how to use the icon.Its better to add,that would be a great user experience

**Describe the solution you'd like**
I want to add a how to use section,where i will show how the icon should be used to work appropriately ,by showing the code

**Comment by bookingjini** [comment]
> kharshita590

Thank you @kharshita590, for your response. - The issue had already been addressed. Please feel free to investigate the repository for any additional issues that may require attention.
