### ISSUE TITLE
Interactive home page (GSSOC'23)

### ISSUE THREAD

**Issue by Bharatpathak08** [Bookingjini-Labs/bookingjini-icons#109]
**Please describe the problem**
Why do you want to add this feature?
As the home page is not looking and attractive and is pretty simple.

**Describe the solution you'd like**
I'll style the page with css.

**Comment by bookingjini** [comment]
> Bharatpathak08

Thank you, @Bharatpathak08, for your prompt reply. Could you please share a prototype or design sample illustrating the changes you intend to contribute? This will help us better understand the modifications you wish to make to the repository.

**Comment by Bharatpathak08** [comment]
![Capture](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/97437398/d9865788-24dd-4198-9c8e-36b046827025)

I would like to make the home page something like this attractive.

**Comment by AshutoshDash1999** [comment]
@Bharatpathak08 Thank you for the effort but we don't need it like this for now. Feel free to explore other issues.
