### ISSUE TITLE
Improve Accessibility of CDN for Users

### ISSUE THREAD

**Issue by premsaivarmachekuri** [Bookingjini-Labs/bookingjini-icons#110]
### Problem Description:
- When using the website as a user, it was challenging to locate the CDN (Content Delivery Network) information.
- Specifically, I needed to copy a CDN link for an icon to use in my code but couldn't find it on the website.
- As a result, I had to navigate back to the GitHub page to access the necessary CDN details.

### Proposed Solution:
- Place the CDN information prominently above the search icon on the website.
- By having the CDN readily available in a visible location, users can easily access the code snippets or resources they require.
- This improvement would eliminate the need for extra navigation or searching, enhancing the overall user experience.

### Screenshots
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/110842297/0ea8f968-57d9-4bbe-be61-b34bc9b8d608)

### Additional Information:
Improving the accessibility and visibility of the CDN information would be a valuable enhancement to the website, promoting a smoother user experience. As part of GSSOC23, I have prior experience in providing effective enhancements to previous projects. I look forward to receiving feedback on this idea and contributing to the improvement of the website's usability.

**Comment by bookingjini** [comment]
> premsaivarmachekuri

Thank you, @premsaivarmachekuri, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by premsaivarmachekuri** [comment]
Your welcome @Bookingjini-Labs/bookingjini-icons
***@***.***>. Noted
I wil be following the code standards and will be sharing the screenshot
during PR.
