### ISSUE TITLE
Want to add a bottom up button to the website

### ISSUE THREAD

**Issue by LadityaGogoi** [Bookingjini-Labs/bookingjini-icons#113]
### **Figma design 👍🏻** 
![34](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/108052802/e0dd127a-91b1-4255-bf12-c252278525c1)

**Want to add this feature to the website, when user went to deep down the user, then they can easily move to the top
by simply clicking on this button.**

#Better user experience

Please assign this task to me under @GSSOC2023

**Comment by bookingjini** [comment]
> ### **Figma design 👍🏻**
> ![34](https://user-images.githubusercontent.com/108052802/240821627-e0dd127a-91b1-4255-bf12-c252278525c1.png)
> 
> **Want to add this feature to the website, when user went to deep down the user, then they can easily move to the top by simply clicking on this button.**
> 
> #Better user experience
> 
> Please assign this task to me under @GSSOC2023

Thank you @Lobi29, for your response. - The issue had already been addressed in issue #35. Please feel free to investigate the repository for any additional issues that may require attention.
