### ISSUE TITLE
Want to category section for icons (left menu)

### ISSUE THREAD

**Issue by LadityaGogoi** [Bookingjini-Labs/bookingjini-icons#114]
### **Figma design 👍🏻** 
![35](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/108052802/e9f70e4c-1954-4ddb-9ae6-809eb29480cb)

**here user can search icons by category also,** 

search bar and categories will be present in left and all related icons will be present in right.
Category will definitely improve the User Experience because now they can choose one easily among other related icons

Please assign this task to me under @GSSOC2023

**Comment by bookingjini** [comment]
> ### **Figma design 👍🏻**
> ![35](https://user-images.githubusercontent.com/108052802/240824201-e9f70e4c-1954-4ddb-9ae6-809eb29480cb.png)
> 
> **here user can search icons by category also,**
> 
> search bar and categories will be present in left and all related icons will be present in right. Category will definitely improve the User Experience because now they can choose one easily among other related icons
> 
> Please assign this task to me under @GSSOC2023

Thank you, @Lobi29, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by AshutoshDash1999** [comment]
@Lobi29 any update on this?

**Comment by AshutoshDash1999** [comment]
@Lobi29 i am closing this issue since you didn't update for more than 3 days
