### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by mohammadshaad** [Bookingjini-Labs/bookingjini-icons#122]
**Please describe the problem**
Right now the project doesn't have the .gitignore file. It is really necessary file that a project should have to avoid some random and useless files.

**Describe the solution you'd like**
I would like to add a .gitignore file including all the file names those should be ignored while pushing the code to this repo

**Comment by mohammadshaad** [comment]
I want to work on this issue and I am a GSSoC'23 contributor so kindly assign me this issue @bookingjini

**Comment by bookingjini** [comment]
> **Please describe the problem** Right now the project doesn't have the .gitignore file. It is really necessary file that a project should have to avoid some random and useless files.
> 
> **Describe the solution you'd like** I would like to add a .gitignore file including all the file names those should be ignored while pushing the code to this repo

Thank you, @mohammadshaad, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by mohammadshaad** [comment]
Thank you so much
