### ISSUE TITLE
Add social media icons

### ISSUE THREAD

**Issue by mohammadshaad** [Bookingjini-Labs/bookingjini-icons#123]
**Please describe the problem**
There is lack of few icons like Instagram, Facebook, Snapchat, GitHub

**Describe the solution you'd like**
I will design the icons myself as I am a designer.

**Comment by mohammadshaad** [comment]
@bookingjini I am a GSSoC'23 contributor so kindly assign me this issue

**Comment by bookingjini** [comment]
> **Please describe the problem** There is lack of few icons like Instagram, Facebook, Snapchat, GitHub
> 
> **Describe the solution you'd like** I will design the icons myself as I am a designer.

Thank you @mohammadshaad, for your response. - The issue had already been addressed. Please feel free to investigate the repository for any additional issues that may require attention.

**Comment by RSN601KRI** [comment]
As a GSSoc Contributor I want to raise and fix this issue by adding a icons of social media to the website. Icons serve as a highlights and connectiond representation of the website and typically displayed in the browser's tab, bookmarks bar, and browser history.

I'm a GSSoC contributor and I've added a Pull Request at #123
Am i supposed to add the screenshot of the code snippet along with the PR ?
