### ISSUE TITLE
Adding a 'NewsLetter' section to give the user any update about trending,new arrival icons.

### ISSUE THREAD

**Issue by splusb** [Bookingjini-Labs/bookingjini-icons#125]
Hi, I think a 'NewsLetter' section will be useful. So please assign me this issue under GSSOC'23

**Comment by bookingjini** [comment]
> splusb

Thank you, @splusb, for your prompt reply. Could you please share a prototype or design sample illustrating the changes you intend to contribute? This will help us better understand the modifications you wish to make to the repository.

**Comment by splusb** [comment]
Thanks for your interest. I am thinking to make a newsletter like:
[https://images01.nicepagecdn.com/page/69/38/website-design-preview-69380.webp](url)

I want to add this newsletter page either in the contact us section or in the home page just above the footer.
I will maintain the background color and the background image with the image of the webpage.

In the newsletter section, I want to mention that if a user subscribes to it, they will get a notification in email whenever we add a new set of icons or we add a new user-friendly feature, or if the icon is available for which they were searching before but didn't get that in past.
I want to add this page by only using html, css, and js.

**Comment by splusb** [comment]
@AshutoshDash1999 Can you review this issue please?

**Comment by AshutoshDash1999** [comment]
@splusb We are not planning for the newsletter anytime soon. Thank you for mentioning this issue though.
