### ISSUE TITLE
Improve Display

### ISSUE THREAD

**Issue by Harleenkaur1712** [Bookingjini-Labs/bookingjini-icons#129]
Improve display and enhance its CSS

pls assign me this under gssoc23

**Comment by bookingjini** [comment]
> Improve display and enhance its CSS
> 
> pls assign me this under gssoc23

Thank you, @Harleenkaur1712, for your prompt reply. Could you please share a prototype or design sample illustrating the changes you intend to contribute? This will help us better understand the modifications you wish to make to the repository.
