### ISSUE TITLE
Adding icons to navbar

### ISSUE THREAD

**Issue by vipulpandey7860** [Bookingjini-Labs/bookingjini-icons#131]
**Please describe the problem**
The nav bar links doesn't have icons. Being an icons website nav bar elements should have icons.

**Describe the solution you'd like**
Adding the icons for lignt/dark theme, download and get cdn button.

**Comment by vipulpandey7860** [comment]
please assign this issue to me under gssoc'23

**Comment by bookingjini** [comment]
> **Please describe the problem** The nav bar links doesn't have icons. Being an icons website nav bar elements should have icons.
> 
> **Describe the solution you'd like** Adding the icons for lignt/dark theme, download and get cdn button.

Thank you, @I-VipulPandey, for your reply. Could you please share a prototype or design sample illustrating the changes you intend to contribute? This will help us better understand the modifications you wish to make to the repository.

**Comment by vipulpandey7860** [comment]
> > **Please describe the problem** The nav bar links doesn't have icons. Being an icons website nav bar elements should have icons.
> > **Describe the solution you'd like** Adding the icons for lignt/dark theme, download and get cdn button.
> 
> Thank you, @I-VipulPandey, for your reply. Could you please share a prototype or design sample illustrating the changes you intend to contribute? This will help us better understand the modifications you wish to make to the repository.




The current design of nav bar doesn't give user all the details, thus by adding icons on nav bar and displaying them when hovered user can get more details what function will the following button will do. I am attaching a video of what I exactly ment, I can also change it if you have something specific.


https://github.com/Bookingjini-Labs/bookingjini-icons/assets/53248489/7bfb80a6-ae75-4d1c-a762-166a74669eee

**Comment by AshutoshDash1999** [comment]
> > > **Please describe the problem** The nav bar links doesn't have icons. Being an icons website nav bar elements should have icons.
> > > **Describe the solution you'd like** Adding the icons for lignt/dark theme, download and get cdn button.
> > 
> > 
> > Thank you, @I-VipulPandey, for your reply. Could you please share a prototype or design sample illustrating the changes you intend to contribute? This will help us better understand the modifications you wish to make to the repository.
> 
> The current design of nav bar doesn't give user all the details, thus by adding icons on nav bar and displaying them when hovered user can get more details what function will the following button will do. I am attaching a video of what I exactly ment, I can also change it if you have something specific.
> 
>  My.Video.mp4

@I-VipulPandey please go forward with it. Please pull the latest changes

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.

**Comment by AshutoshDash1999** [comment]
@I-VipulPandey have you submitted a PR for this?

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by AshutoshDash1999** [comment]
@pjyoti121 assigning this to you

**Comment by AshutoshDash1999** [comment]
@pjyoti121 please update on this issue

**Comment by Kajal2468** [comment]
please assign this issue .

**Comment by AshutoshDash1999** [comment]
@Kajal2468 assigning this issue to you

**Comment by Kajal2468** [comment]
Thank You sir for assign this project ,
It's my pleaser to work on this project .

**Comment by AshutoshDash1999** [comment]
@Kajal2468 what's the update on this?

**Comment by Kajal2468** [comment]
@AshutoshDash1999 still Working on this project.

**Comment by Kajal2468** [comment]
@AshutoshDash1999 in navbar section which type of icons u want to take can u share some sample this will help me to  better understand the modification because in navbar already dark light / download / Repo section available.....
![navbar](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/121488331/b325987d-ee95-4e20-b828-1942cf88bcc4)

Thank You!!

**Comment by AshutoshDash1999** [comment]
use the icons like that in `Repo` button

**Comment by Kajal2468** [comment]
ok
