### ISSUE TITLE
Integration of Chatbot [GSSOC'23]

### ISSUE THREAD

**Issue by shagunZ** [Bookingjini-Labs/bookingjini-icons#132]
This pull request aims to integrate a chatbot into the website, providing an enhanced user experience and improved support capabilities. The chatbot functionality will allow users to interact with the website in a conversational manner, providing assistance, answering queries, and offering personalized recommendations. This will increase user satisfaction and retention by providing a seamless and interactive website experience.
Kindly assign me this issue. I would love to work on it and try it out for the very first time.

**Comment by bookingjini** [comment]
@AshutoshDash1999 - Kindly look into the pull request.

**Comment by AshutoshDash1999** [comment]
@shagunZ can you please be specific with what tech will you be using? Do you need us to setup any backend?

**Comment by shagunZ** [comment]
I was thinking to integrate the chatbot using Dialogflow for the web application. This can be achieved without the need of a dedicated backend. We will provide a variety of training phrases to ensure the chatbot can accurately recognize user queries. We will define a set of intents based on the specific requirements of the application. Though the app demands a limited set of queries, so intents implementation wouldn't require much.

**Comment by AshutoshDash1999** [comment]
The website doesn't need any chatbot for now as it will be overkill and would affect the load time. Thank you for raising this issue though.

**Comment by shagunZ** [comment]
Okay! I may look for some other issues, Thankyou :)
