### ISSUE TITLE
[UI Improvement] Adding search icon in the search bar

### ISSUE THREAD

**Issue by Ishita-Ghosh-25** [Bookingjini-Labs/bookingjini-icons#134]
**Please describe the problem**
Why do you want to add this feature?
 Adding a search icon in the search bar to make the UI look more interactive.

**Describe the solution you'd like**

Adding a Search icon to the search bar

**Screenshot**
Please attach any relevant screenshot(s).
<img width="955" alt="image" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/70560812/20921a1c-9afc-4b6e-a9c9-2702add9fb33">

**Comment by bookingjini** [comment]
> **Please describe the problem** Why do you want to add this feature? Adding a search icon in the search bar to make the UI look more interactive.
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> Adding a Search icon to the search bar
> 
> **Screenshot** Please attach any relevant screenshot(s). <img alt="image" width="955" src="https://user-images.githubusercontent.com/70560812/241001560-20921a1c-9afc-4b6e-a9c9-2702add9fb33.png">

Thank you, @Ishita-Ghosh-25, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.
