### ISSUE TITLE
Add support for Fuzzy matching

### ISSUE THREAD

**Issue by monarxxjain** [Bookingjini-Labs/bookingjini-icons#135]
**Problem**
  Currently, the search functionality on the platform is limited as it does not account for misspellings,
   synonyms, or typos in search queries. This results in users having trouble finding the results they need.

**Feature Request**
   To improve our search functionality, I would like to add support for a fuzzy search algorithm. This will
   allow users to find relevant results even when they make mistakes in their search queries.

**Solution**
  I propose implementing a fuzzy search algorithm using techniques such as Levenshtein distance,  Jaro-Wink
  ler distance, etc. We can leverage existing libraries such as  Fuse.js to implement this algorithm
  with minimal effort.

**Expected Outcome**
  With the implementation of fuzzy search, I expect that users will be able to find relevant results more
  easily, even when they make mistakes in their search queries.

**Screenshots**

<details>
<summary>Current</summary>
<img src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/128830789/d3f95919-4143-4147-ba89-f1771664dd2b" alt="Current screenshot">
</details>

<details>
<summary>Final</summary>
<img src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/128830789/6e50bccb-3144-42e2-8c71-52786561e04a" alt="Final screenshot">
</details>

I believe this feature will significantly improve the user experience on the platform and increase user
engagement. Please let me know if you have any questions or concerns regarding this feature request. Thank
you for your consideration       :)

**Comment by bookingjini** [comment]
> **Problem** Currently, the search functionality on the platform is limited as it does not account for misspellings, synonyms, or typos in search queries. This results in users having trouble finding the results they need.
> 
> **Feature Request** To improve our search functionality, I would like to add support for a fuzzy search algorithm. This will allow users to find relevant results even when they make mistakes in their search queries.
> 
> **Solution** I propose implementing a fuzzy search algorithm using techniques such as Levenshtein distance, Jaro-Wink ler distance, etc. We can leverage existing libraries such as Fuse.js to implement this algorithm with minimal effort.
> 
> **Expected Outcome** With the implementation of fuzzy search, I expect that users will be able to find relevant results more easily, even when they make mistakes in their search queries.
> 
> **Screenshots**
> 
> Current
> Final
> I believe this feature will significantly improve the user experience on the platform and increase user engagement. Please let me know if you have any questions or concerns regarding this feature request. Thank you for your consideration :)

Thank you, @monarxxjain, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.
