### ISSUE TITLE
"Search box text in dark mode becomes invisible upon hover"

### ISSUE THREAD

**Issue by monarxxjain** [Bookingjini-Labs/bookingjini-icons#136]
**Please describe the problem**
When using dark mode and typing text into the search box, the text becomes invisible when hovering over it.

**Why do you want to add this feature?**
Users who prefer dark mode are having difficulty seeing the text in the search box when they hover over it.
 This makes it difficult for them to search for content on the site.

**Describe the solution you'd like**

A solution that would be helpful is to modify the CSS for the search box so that the text remains visible when
 hovered over, regardless of whether dark mode is enabled or not. Specifically, the color of the text should
 be changed to a lighter shade when hovering over it in dark mode.

**Bug Clip**

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/128830789/4de41e02-193d-42ff-8829-7bfebd73b37f

Thank you for your attention to this issue. Let me know if there is any further information I can provide to
 help resolve this problem.

I would like to get it assigned to me  :)

**Comment by bookingjini** [comment]
> **Please describe the problem** When using dark mode and typing text into the search box, the text becomes invisible when hovering over it.
> 
> **Why do you want to add this feature?** Users who prefer dark mode are having difficulty seeing the text in the search box when they hover over it. This makes it difficult for them to search for content on the site.
> 
> **Describe the solution you'd like**
> 
> A solution that would be helpful is to modify the CSS for the search box so that the text remains visible when hovered over, regardless of whether dark mode is enabled or not. Specifically, the color of the text should be changed to a lighter shade when hovering over it in dark mode.
> 
> **Bug Clip**
> 
>  SearchBox.mp4 
> Thank you for your attention to this issue. Let me know if there is any further information I can provide to help resolve this problem.
> 
> I would like to get it assigned to me :)

Thank you, @monarxxjain, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by monarxxjain** [comment]
This bug is now solved by someone else, So should I close this issue  #136

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.
