### ISSUE TITLE
Suggestion: Hovering effect on the text

### ISSUE THREAD

**Issue by DivyanshiNarang** [Bookingjini-Labs/bookingjini-icons#137]
**Enhancement**
Adding a hovering effect on "Bookingjini Icons." to make the text attractive.

**Screenshot**
<img width="778" alt="Screenshot 2023-05-26 030828" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74779601/2f6b7cb7-1f27-4b80-8839-81326133054a">

*Please assign this issue to me under GSSoC'23*

**Comment by bookingjini** [comment]
> **Enhancement** Adding a hovering effect on "Bookingjini Icons." to make the text attractive.
> 
> **Screenshot** <img alt="Screenshot 2023-05-26 030828" width="778" src="https://user-images.githubusercontent.com/74779601/241066136-2f6b7cb7-1f27-4b80-8839-81326133054a.png">

Thank you, @DivyanshiNarang, for your prompt reply. Could you please share a prototype or design sample illustrating the changes you intend to contribute? This will help us better understand the modifications you wish to make to the repository.

**Comment by DivyanshiNarang** [comment]
Sure, here are some of the ideas.
1.)

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74779601/cf541e23-f2ee-483f-be76-ea1cc50762f7


2.)

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74779601/8472ec4a-4e49-492c-acac-f25c34c86054

3.)

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74779601/7a6ce4b7-f517-4c8e-88f5-4ea96493c769

Please suggest, if any other.

**Comment by dhruv8433** [comment]
I would like to work on this...

**Comment by DivyanshiNarang** [comment]
Hello @bookingjini, Can you please review the prototypes I have mentioned so I can start working on it.

**Comment by KamalSritha-04** [comment]
I would like to work on this issue can you please assign it to me.

**Comment by AshutoshDash1999** [comment]
@DivyanshiNarang  please go forward with an animation effect like that in the first gif.
