### ISSUE TITLE
Alphabetical Glossary Hyperlink Section

### ISSUE THREAD

**Issue by rimi0602** [Bookingjini-Labs/bookingjini-icons#138]
**Please describe the problem**
----> There are too icons to keep track. Therefore, having a glossary in alphabetical order would make users go through the list before copying any icons and it is easier to find as well as organised.

**Why do you want to add this feature?**
To add an extra feature which might work as an Index for the icons

**Describe the solution you'd like**
I'd like to add a section where in all the icons starting from A would be under alphabet A, similarly B icons under alphabet, C d e ... z . A user would be able to navigate through the alphabets to find any kind of emoji. 

**Screenshot**
Please attach any relevant screenshot(s).
[https://www.google.com/url?sa=i&url=https%3A%2F%2Fherothemes.com%2Fblog%2Fhow-to-add-a-glossary-to-wordpress%2F&psig=AOvVaw2q5qjEqEuMZ4gEalwpIqtC&ust=1685140017400000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCID7svLBkf8CFQAAAAAdAAAAABAJ](url)
Something like this to keep it organised

@AshutoshDash1999 @bikidsx

**Comment by AshutoshDash1999** [comment]
@rimi0602 that's a good idea. please go ahead. While submitting a PR please make sure to include screenshot

**Comment by AshutoshDash1999** [comment]
@rimi0602 any update on this?

**Comment by AshutoshDash1999** [comment]
closing this issue since the assignee didn't give any update
