### ISSUE TITLE
Adding a FAQ Section

### ISSUE THREAD

**Issue by raj3000k** [Bookingjini-Labs/bookingjini-icons#139]
**Please describe the problem**
Why do you want to add this feature?
So to answer the common questions of the user easily.

**Describe the solution you'd like**
Adding a FAQ Section on how to use the icons,answers to the common errors user might face while using icons in various places .
**Screenshot**
Please attach any relevant screenshot(s).

**Comment by N03Nilay** [comment]
I have earlier added this FAQ component in different website .
![Screenshot (252)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/109015625/d7d4f61a-dbb0-4db3-a56b-e4a2a1a660cd)
![Screenshot (254)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/109015625/6022e708-02e7-48b4-9bca-4f738348312d)

**Comment by pjyoti121** [comment]
I WOULD LIKE TO SOLVE THIS ISSUE 
PLEASE ASSIGN ME THIS ISSUE UNDER GSSOC'23

**Comment by AshutoshDash1999** [comment]
@raj3000k this issue is assigned to you

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.
