### ISSUE TITLE
Add view-point icon

### ISSUE THREAD

**Issue by Archit-Kohli** [Bookingjini-Labs/bookingjini-icons#142]
## Feature
Add a new view-point icon

## Description
I will create a view-point icon symbolising amazing view from room or balcony

*Please assign this issue to me*

**Comment by AshutoshDash1999** [comment]
We haven't added the doc for how you can add your icons. We will soon update it. If you want to develop the icon please go with it. Let me know once the logo is ready.

**Comment by Archit-Kohli** [comment]
I do not wish to do this issue now, but if some one else wants to do this, please go ahead
