### ISSUE TITLE
Change Background  color for both themes

### ISSUE THREAD

**Issue by NaveenVaratharaj** [Bookingjini-Labs/bookingjini-icons#144]
**Please describe the problem**
This is a enhancement that need to be added!

**Describe the solution you'd like**
The User Interface is not much appealing in terms of colors. So I would like to change background for both light and dark themes.

**Screenshot**
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/88475979/0ae4f4dd-1a50-43fa-b00d-f3cd4d097eec)
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/88475979/1049c46a-1e69-4db2-8ec9-2c1eea2be78f)

Please assign the issue to me!

**Comment by why-sid** [comment]
Is this issue assigned to someone? Is it still open?

**Comment by why-sid** [comment]
I want to work on this issue

**Comment by KamalSritha-04** [comment]
Is this issue still open can you please assign it to me?

**Comment by Upasana112** [comment]
hey, i would like to contribute to this issue

**Comment by NaveenVaratharaj** [comment]
@purnima143 I am unable to complete this I am facing some problems in local machine. Assign this to someone else, sorry for the inconvenience happened!

**Comment by KamalSritha-04** [comment]
@purnima143 I think i can do it, can you please assign me this issue under GSSOC'23?

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.

**Comment by purnima143** [comment]
Assigned @priyanka7976

**Comment by AshutoshDash1999** [comment]
Closed due to inactivity.
