### ISSUE TITLE
Bug in the user lnterface while using light theme

### ISSUE THREAD

**Issue by NaveenVaratharaj** [Bookingjini-Labs/bookingjini-icons#145]
**Please describe the problem**
There is a bug in the website while it is viewed in a light mode!

**Describe the solution you'd like**
When the user using the website in light mode there is no change in the button's text which is present in Navbar.

**Screenshot**
While using it in light mode, the button text doesn't change to dark mode! Consider this bug and assign this to me!
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/88475979/dfc0b4dd-71a3-4ac0-98e5-f74fcc3db051)

**Comment by AshutoshDash1999** [comment]
This issue is already addressed and the button has been changed to switch. It still has some bugs though. Feel free to address it in a new issue.
