### ISSUE TITLE
Adding a Share Website link Feature using LinkedIn icon, Twitter Icon, Whatsapp Icon

### ISSUE THREAD

**Issue by shreyaslax** [Bookingjini-Labs/bookingjini-icons#147]
To share the website with maximum people possible, I am adding a Share Website Link feature.

Using Material UI Icons, which on clicking lead to sharing the website link on these Social Media Platforms

I have worked on such projects before.
Looking forward to contribute.

Thank you

**Comment by purnima143** [comment]
Hi @shreyaslax , you can go ahead. But where will you add those share links?

**Comment by shreyaslax** [comment]
Just below the Navbar at the rightmost part below the Horizontal rule which is below the Download Button  . [purnima143](https://github.com/purnima143)  Could you please assign this issue to me

**Comment by AshutoshDash1999** [comment]
@shreyaslax can you share any relevant screenshot?
