### ISSUE TITLE
copy right reserved 

### ISSUE THREAD

**Issue by Sushilverma002** [Bookingjini-Labs/bookingjini-icons#148]
**Please describe the problem**
Why do you want to add this feature?
I want to add this feature so that know one get directly copy your website and said it was mine so it will aware other that this website has license.

**Describe the solution you'd like**
solution for that i would like to add the footer section in the last of the website that will work on both dark and light theme.
**Screenshot**
![Untitled](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114687502/663df52b-c9db-4338-84f6-15ac213e3325)

**Comment by Sushilverma002** [comment]
assign me i will do this for you.

**Comment by AshutoshDash1999** [comment]
this is already included in website
