### ISSUE TITLE
delivery(truck-fast) icon

### ISSUE THREAD

**Issue by Sushilverma002** [Bookingjini-Labs/bookingjini-icons#149]
**Please describe the problem**
this icons will help for truck -fast.
**Describe the solution you'd like**
one more icon will get added
**Screenshot**
![Screenshot 2023-05-26 204254](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114687502/83c898dd-d6dc-4422-9e3f-b1f0cc5d7669)

**Comment by vk20july** [comment]
@Sushilverma002 mam can i do this task under gssoc'23

**Comment by AshutoshDash1999** [comment]
We are not accepting any more icons for now.
