### ISSUE TITLE
angle left-right-up-down icons

### ISSUE THREAD

**Issue by Sushilverma002** [Bookingjini-Labs/bookingjini-icons#150]
**Please describe the problem**
these are arrow of angle left -right -up -down which will enhance the ions which are already present 
**Describe the solution you'd like**
i will just add these ions which work on both dark and light theme
**Screenshot**
Please attach any relevant screenshot(s).
![angle left right](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114687502/09b84d48-f052-4d0d-8ca6-ee6df1440167)
![angle up and right](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114687502/e9b20ece-7e11-4ba2-8f0c-e3daddb5d7f2)

**Comment by vk20july** [comment]
@purnima143 sir can I do this task under gssoc'23

**Comment by AshutoshDash1999** [comment]
We are not accepting any more icons for now.
