### ISSUE TITLE
Adding a scroll-to-top button

### ISSUE THREAD

**Issue by deepeshmlgupta** [Bookingjini-Labs/bookingjini-icons#151]
**Please describe the problem**
As this feature enables the user to scroll-up the website in one click
**Describe the solution you'd like**
I can Add this scroll up button in your website 

Please assign this issue to me under GSSOC'23

**Comment by purnima143** [comment]
The issue had already been addressed #35 . Please feel free to investigate the repository for any additional issues that may require attention.
