### ISSUE TITLE
Missing pull request template

### ISSUE THREAD

**Issue by DivyanshiNarang** [Bookingjini-Labs/bookingjini-icons#155]
Addition of Pull Request template.

**Comment by AshutoshDash1999** [comment]
@DivyanshiNarang can you work on the PR template? Its on priority for us for now.

**Comment by DivyanshiNarang** [comment]
Yeah sure. I will start working on the PR template. Do I have to raise another issue for the PR template? @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
@DivyanshiNarang please change the issue title. Assigning this to you.

**Comment by DivyanshiNarang** [comment]
Okay, sure.

**Comment by DivyanshiNarang** [comment]
Hello @AshutoshDash1999 sir, now can I add the remaining issue templates by raising another issue?

**Comment by AshutoshDash1999** [comment]
@DivyanshiNarang yes, please. Please change the issue description too to make it more relevant to title
