### ISSUE TITLE
Add scroll down button

### ISSUE THREAD

**Issue by KumariShaliniDwivedi** [Bookingjini-Labs/bookingjini-icons#156]
**Please describe the problem**
We can add up to down button and down to up button 

**Screenshot**
![Screenshot (416)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/132951829/536d72f7-9cee-4b72-8c61-8e7fe65b602e)
![Screenshot (417)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/132951829/54fb30a6-17b7-4836-a24e-a87be4568514)

**Comment by AshutoshDash1999** [comment]
scroll to the top button is already there on the website. we don't need scroll to bottom for now. 
Thank you

**Comment by KumariShaliniDwivedi** [comment]
okay thanks
