### ISSUE TITLE
Update the Dark/Light mode Button 

### ISSUE THREAD

**Issue by JeevarajB** [Bookingjini-Labs/bookingjini-icons#157]
The current button will switch the both modes good. Add the toggle switch like "🌞->🌛" Can you assign me to fix that. I'm GSSOC 23 Contributor.

**Comment by rohanmittal1163** [comment]
Hey @bookingjini the working of modes is good on the website. But it good be more atractive with the toggle button. I want to implement the toggle switch button in the repo. 
**SCREENSHORTS**
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/97821844/fa9bae07-cfdf-49e0-8363-c28c021a13b7)
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/97821844/51ef7f76-a92d-4d7e-8904-6b9954f49f5f)
could you pls assign me this issue under GSSOC'23 contribution. Thank you for reading

**Comment by AshutoshDash1999** [comment]
@JeevarajBoomi you are being assigned

**Comment by JeevarajB** [comment]
hey!! I'm update the Button. I got an error in the pull, so I will send the 3 pull request for one update
