### ISSUE TITLE
NavBar is not responsive and the alignments of icons are also not responsive

### ISSUE THREAD

**Issue by picturepatch07** [Bookingjini-Labs/bookingjini-icons#160]
**Please describe the problem**
The website's navbar is not responsive, and when we browse the site on a mobile device, the icon alignments are not exactly right. 

**Describe the solution you'd like**
I will make the website responsive using CSS. 

**Screenshot**

![issue1](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/88630461/be66825b-441d-43d2-b1a3-253aac2aa554)

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/88630461/da0befd3-05fb-4635-93b2-92d3184f3f02)

**Comment by picturepatch07** [comment]
Please assign me this issue

**Comment by picturepatch07** [comment]
@AshutoshDash1999 assign me this issue

**Comment by AshutoshDash1999** [comment]
@picturepatch07 sure

**Comment by pjyoti121** [comment]
THE NAVBAR IS STILL NOT RESPONSIVE PLEASE ASSIGN ME THIS ISSUE

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.
