### ISSUE TITLE
[docs] Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by bhartik021** [Bookingjini-Labs/bookingjini-icons#162]
**Please describe the problem**
This commit updates the CONTRIBUTING.md file in the repository to provide clear guidelines for contributing to the project.

**Describe the solution you'd like**
The changes include the following:
- Added a section on how to report bugs and issues, including steps for reproducing them and providing relevant information.
- Included instructions on how to suggest new features or improvements, including the preferred format for feature requests.
- Clarified the code formatting and style guidelines to ensure consistency across contributions.
- Provided examples and explanations on how to submit pull requests, along with the necessary steps for the review process.
- Added a section on how to communicate effectively with the project maintainers and other contributors, emphasizing the importance of respectful and constructive discussions.
- These updates aim to streamline the contribution process and provide contributors with clear instructions on how to get involved. The goal is to foster a welcoming and collaborative environment for anyone interested in contributing to the project.

**Screenshot**
Please attach any relevant screenshot(s).
![screenshot](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/75694208/d0fbdd49-88c9-4d74-bf20-f03c882b1f4e)

**Comment by bhartik021** [comment]
@bookingjini Please assign this issue to me under gssoc'23

**Comment by AshutoshDash1999** [comment]
@bhartik021 This is really good. Assigned to you. Please pull the latest code as we already have contributing.md file, you can add your changes on top of it.

**Comment by Snigdha2712** [comment]
Please assign this issue to me. I would like to work on it @bhartik021

**Comment by AshutoshDash1999** [comment]
@bhartik021 any update on this?
