### ISSUE TITLE
Adding search icon before the "search icon placeholder text"

### ISSUE THREAD

**Issue by Anshkaran7** [Bookingjini-Labs/bookingjini-icons#163]
**Please describe the problem**
Lack of search icon before the search bar, resulting in reduced visual appeal and user attractiveness.

**Describe the solution you'd like**
Add a search icon to the search bar for improved aesthetics and enhanced user experience.

**Screenshot**
![Screenshot 2023-05-27 203855](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/106963118/aae4f6c8-8186-46e1-a6f0-87d3f4274873)

**Comment by rohanmittal1163** [comment]
hi @bookingjini i want to add a search icon to the website. It looks more appealing with the hover effect as well.

here is the look of the search button  - width will be increased in this and placeholder would be change
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/97821844/2c532b65-aec4-46c7-837c-e7858287c090)
could you pls assign me this issue under GSSOC'23 contributor

**Comment by AshutoshDash1999** [comment]
this issue has been already added. Feel free to change current search input UI though
