### ISSUE TITLE
Responsives need to be improved for small screen devices

### ISSUE THREAD

**Issue by Devil1205** [Bookingjini-Labs/bookingjini-icons#164]
**Please describe the problem**
Why do you want to add this feature?
Content alignment is not comfortable and attractive for small screen devices.

**Describe the solution you'd like**
I would like to improve the responsiveness of the main page by adding some margins and align the content accordingly.

**Screenshot**
Please attach any relevant screenshot(s).
![127 0 0 1_5500_website_index html](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/103431946/f27f7ea0-159b-4223-b1d7-a6a47d656354)

**Comment by AshutoshDash1999** [comment]
@Devil1205 assigned to you

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.

**Comment by AshutoshDash1999** [comment]
@priyanka7976 ok assigning it to you.

**Comment by AshutoshDash1999** [comment]
@priyanka7976 any update on this

**Comment by AshutoshDash1999** [comment]
Closing this as the assignee failed to give any update for more than 3 days.
