### ISSUE TITLE
Changing the download and light mode buttons [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [Bookingjini-Labs/bookingjini-icons#165]
**Please describe the problem**
The light mode button and download button does no go good with the existing design. I think they can be made better.

**Describe the solution you'd like**
I have designed multiple buttons and with the project mentors feedback I can design more buttons. Some examples are :
![buttons_options](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/116020663/ca9ac94e-0b0d-4a79-8b3f-fe850d6ec15c)

**Screenshot**
Please attach any relevant screenshot(s).

Please assign me this issue under GSSoC'23

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by AshutoshDash1999** [comment]
the UI for light/dark mode has changed.

**Comment by 1Shubham7** [comment]
OK @AshutoshDash1999 .
