### ISSUE TITLE
Adding a footer in the website. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [Bookingjini-Labs/bookingjini-icons#166]
**Please describe the problem**
There is no footer to the website where we can have Terms and conditions, Contact us , etc.

**Describe the solution you'd like**
I can create a footer for the website as well as create terms and conditions , contact us, etc etc pages .

**Screenshot**
![footer_issue](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/116020663/8f40a436-14d5-4d33-a35e-45b0336b8131)

Please assign me this issue under GSSoC'23

**Comment by aniketnimkar** [comment]
please assign this task to me, I'm eager to make a valuable contribution to this issue as part of the GSSOC initiative.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by AshutoshDash1999** [comment]
@1Shubham7 assigned to you

**Comment by 1Shubham7** [comment]
@AshutoshDash1999  Thank  you for assigning it to me I will surely not disappoint you.

**Comment by 1Shubham7** [comment]
@AshutoshDash1999 Please review this PR.

**Comment by 1Shubham7** [comment]
Thanks a lot @AshutoshDash1999 Bhaiya
