### ISSUE TITLE
making header more responsive and creative 

### ISSUE THREAD

**Issue by abansal15** [Bookingjini-Labs/bookingjini-icons#169]
**Please describe the problem**
Why do you want to add this feature?
header is not responsive and not much creative

**Describe the solution you'd like**
I want the header should be more responsive and creative

**Screenshot**
Please attach any relevant screenshot(s).
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/120590200/5febaaf9-b1f8-4fbd-9701-01f46e05b522)

**Comment by abansal15** [comment]
please assign this issue to me

**Comment by AshutoshDash1999** [comment]
@abansal15 assigning this to you

**Comment by ks20soni** [comment]
Even on the big screen, the header does not look very attractive. I would like to make it a bt more attractive by adding some CSS. Can you please assign it to me?

**Comment by AshutoshDash1999** [comment]
@abansal15 any update on this?

**Comment by abansal15** [comment]
Ya I will rase the pr till tonight

**Comment by abansal15** [comment]
@AshutoshDash1999 raised the pr
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/120590200/535e04cf-8028-44c6-ac1b-f30de127bbb4)

**Comment by AshutoshDash1999** [comment]
> @AshutoshDash1999 raised the pr

Please tag the issue number in the PR
