### ISSUE TITLE
request to make Contact us and about section

### ISSUE THREAD

**Issue by gaur15** [Bookingjini-Labs/bookingjini-icons#17]

**Comment by varshanim** [comment]
hello! I see that there is no contact us or about section provided at the bottom of the website. So i would like to improve this. Can you please assign this issue to me under GSSoC'23?

**Comment by chirayu-humar** [comment]
i also wanted to contribute to this issue, please assign me this issue under GSSoC'23.

**Comment by bookingjini** [comment]
> _No description provided._

Thank you @gaur15 for your response. Kindly describe your changes.

**Comment by kasturimandlik** [comment]
I would like to create a contact us section for the website.
The page will collect the details like Mail address, mobile number, message.
I would like to work on this under GSSOC'23. please assign me this issue.

**Comment by gaur15** [comment]
I would like to add HTML of about us in footer and add some CSS to it. and use html forms for contact us form.

> > _No description provided._
> 
> Thank you @gaur15 for your response. Kindly describe your changes.

**Comment by AshutoshDash1999** [comment]
@gaur15 please go ahead. Kindly follow the design which matches with overall UI of the website. Also while submitting PR please attach screenshots.

**Comment by AshutoshDash1999** [comment]
@gaur15 any update on this issue?

**Comment by gaur15** [comment]
> @gaur15 any update on this issue?

yes sir I have added the about  page and contact us form only some CSS is left in both. these are the images of the same kindly suggest some changes sir.

<img width="960" alt="Screenshot 2023-05-30 081856" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/133087361/11951650-532c-4bf6-aaa7-1cc88f8855f9">
<img width="960" alt="Screenshot 2023-05-30 081917" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/133087361/7c0f3800-2e4b-4ff1-a32f-8357de7e23f6">

**Comment by AshutoshDash1999** [comment]
@gaur15 please focus on minimalist design. the design doesn't look good. Please focus on making basic footer

**Comment by KamalSritha-04** [comment]
Is this issue still open, can you assign it to me under GSSOC'23
