### ISSUE TITLE
Buttons not creative and not proper spacing between them

### ISSUE THREAD

**Issue by abansal15** [Bookingjini-Labs/bookingjini-icons#170]
**Please describe the problem**
Why do you want to add this feature?
Butoons are not creative and not proper spacing

**Describe the solution you'd like**
i will make the button more creative more give proper space between them

**Screenshot**
Please attach any relevant screenshot(s).
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/120590200/0ed3f639-f783-48b0-9aa9-ff5e5bb5a84a)

**Comment by abansal15** [comment]
pls assign this issue to me....

**Comment by AshutoshDash1999** [comment]
the ui has changed, feel free to submit new issue according to that.
