### ISSUE TITLE
[Bug]: UI fix of Toast(Icon buttons)

### ISSUE THREAD

**Issue by anjz20** [Bookingjini-Labs/bookingjini-icons#171]
**Please describe the problem**
While selecting an icon more than one time the toast displays in a stack order.

**Describe the solution you'd like**
The correct behavior of the toast should be displayed only one at a time

**Screenshot**
![Screenshot (19)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/94970107/1867a006-39b4-4402-b542-c21b09e04a36)

**Comment by anjz20** [comment]
@AshutoshDash1999 @bookingjini  I want to fix this issue and I am working on it. It will be appreciated if you will assign to me

**Comment by AshutoshDash1999** [comment]
@anjz20 you are being assigned.

**Comment by AshutoshDash1999** [comment]
@anjz20 any update on this.

**Comment by AshutoshDash1999** [comment]
Closing this issue as assignee failed to give any update
