### ISSUE TITLE
Cloud icons or Sun icons or Social media icons

### ISSUE THREAD

**Issue by VardaPanchal005** [Bookingjini-Labs/bookingjini-icons#174]
Different types of cloud icons where some indicate rain ,some snow storm, some sunny ,clouds with lightning, haze, fog etc(with or without fill) 
or sun icons-sunrise, sun, sunset etc

or icons of social media like youtube, meta, messenger, instagram.

I would like to work on any of these issues.
@AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
@VardaPanchal005 please go through: https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/upload_icons/create_icons.md
