### ISSUE TITLE
Change Light Dark Mode Icon

### ISSUE THREAD

**Issue by ManasMadan** [Bookingjini-Labs/bookingjini-icons#175]
**Please describe the problem**
Why do you want to add this feature?
I Think adding icon for the dark mode and light mode toggle would make the website feel better. PS: It's a icon website so it should have a icon for the same

**Describe the solution you'd like**
I would be using icons for both sun and moon to replace the text and button

**Screenshot**
<img width="847" alt="image" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/84731321/7df9ee00-3eae-445f-9004-e0519571cd49">

**Comment by ManasMadan** [comment]
@AshutoshDash1999 Please assign me this issue under GSSoC 23

**Comment by AshutoshDash1999** [comment]
@ManasMadan this issue is already covered.

**Comment by ManasMadan** [comment]
Ok is there any other issue you would like me to work on @AshutoshDash1999
