### ISSUE TITLE
Sitemap addition

### ISSUE THREAD

**Issue by krishnamangal98** [Bookingjini-Labs/bookingjini-icons#177]
**Please describe the problem**
I wanted to create a sitemap for SEO

**Describe the solution you'd like**

**Screenshot**
Please attach any relevant screenshot(s).

**Comment by krishnamangal98** [comment]
please assign me this issue under gssoc23

**Comment by AshutoshDash1999** [comment]
@krishnamangal98 since we only have 1 page, we don't need it for now
