### ISSUE TITLE
Improving the index.html file 

### ISSUE THREAD

**Issue by harshsingh32** [Bookingjini-Labs/bookingjini-icons#18]
I would like to improve the index.html file of the project. Adding some features and making it engaging for the users.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by AshutoshDash1999** [comment]
@harshsingh32 hi thanks for contributing. Can you please share what exactly you want to improve?

**Comment by harshsingh32** [comment]
I want add some features in the index file, and make it more expressive and engaging. Not changing the structure of website but changing some minor features and adding some features to make it more expressive for the users so that users can contribute to the project.

**Comment by bookingjini** [comment]
> I want add some features in the index file, and make it more expressive and engaging. Not changing the structure of website but changing some minor features and adding some features to make it more expressive for the users so that users can contribute to the project.

Thank you @harshsingh32 for your response. Feel free to proceed ahead with ur contribution. Kindly provide a screenshot while you do the Pull Request.
