### ISSUE TITLE
Enhancing the readme

### ISSUE THREAD

**Issue by abhi03ruchi** [Bookingjini-Labs/bookingjini-icons#182]
**Please describe the problem**
To inprove user experience and engagement. This would be quite helpful for people who are looking forward to contribute in the project.

**Describe the solution you'd like**
I would like to Add 

- Table of Contents
- Teck Stack Used
- Back to Top Button

**Screenshot**
Sample :-
1)
<img width="392" alt="Screenshot 2023-05-29 at 10 41 21 PM" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/105661636/03fe61b0-7c11-4228-91fd-bcb454bba59f">

2)
<img width="209" alt="Screenshot 2023-05-30 at 6 36 29 AM" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/105661636/5aa85ee1-8b4d-4b92-8e16-8d511aff6c73">

3)
<img width="317" alt="Screenshot 2023-05-30 at 6 36 15 AM" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/105661636/4a2caad7-8265-4582-9d78-c93aa3e6b174">

**Comment by AshutoshDash1999** [comment]
we don't need this for now. thank you
