### ISSUE TITLE
Addition to ISSUE TEMPLATE

### ISSUE THREAD

**Issue by DivyanshiNarang** [Bookingjini-Labs/bookingjini-icons#183]
Here are three templates that I want to include to make it easier for contributors and maintainers to understand and address the problems or feature requests effectively. :

Bug/Issue Template: This template enables users to create well-structured issue reports by providing sections for a concise title, detailed description, steps to reproduce (if applicable), expected behavior, actual behavior, additional information, and environment details.

Feature Request Template: The feature request template allows users to outline their desired features with clarity, including sections for a clear feature description, expected benefits, and any additional context or information.

Documentation Template: This template facilitates the creation of comprehensive documentation by providing a structured format, including sections for an introduction, usage instructions, examples, and other relevant details.

*Please assign this issue to me under GSSoC'23* @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
@DivyanshiNarang please go ahead
