### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by Abhinavcode13** [Bookingjini-Labs/bookingjini-icons#184]
I want to add more icons related to hospitality of high resolution , please assign me this issue @AshutoshDash1999 !!

**Comment by Abhinavcode13** [comment]
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/126642111/55b484bd-f92c-47b2-9772-56cf26fa08e3)
icons which will be added

**Comment by Abhinavcode13** [comment]
@AshutoshDash1999 please check

**Comment by Abhinavcode13** [comment]
@purnima143 u too

**Comment by AshutoshDash1999** [comment]
@Abhinavcode13 you are assigned with this issue

**Comment by Abhinavcode13** [comment]
what we have to do after uploading the icon to icomoon? @AshutoshDash1999

**Comment by Abhinavcode13** [comment]
HTML
<span class="icon-woman-icon_adobe_express"></span>

CSS
.icon-woman-icon_adobe_express:before {
  content: "\e900";
}

**Comment by Abhinavcode13** [comment]
@AshutoshDash1999 ???

**Comment by Abhinavcode13** [comment]
@AshutoshDash1999 ?? can you explain

**Comment by AshutoshDash1999** [comment]
Thank you for expressing your interest in contributing new icons to our collection. We truly appreciate your enthusiasm and creativity. However, we have decided not to include more icons to maintain a consistent design style throughout our icons.
We hope you understand our decision and we encourage you to continue exploring your design style in other projects.
