### ISSUE TITLE
Improving the UX of navbar by adding icons

### ISSUE THREAD

**Issue by vipulpandey7860** [Bookingjini-Labs/bookingjini-icons#185]
Please describe the problem
The nav bar links doesn't have icons. Being an icons website nav bar elements should have icons.

Describe the solution you'd like
Adding the icons for lignt/dark theme, download and get cdn button.

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/53248489/d1131e0f-b959-47f3-b806-83eedbea76f4

Note - the icons here in light and dark mode are the same but I will add different icons for different theme.

**Comment by ShubhaSwarup** [comment]
Please assign this issue to me

**Comment by AshutoshDash1999** [comment]
this issue has already been covered
