### ISSUE TITLE
copyright line is not visible in dark mode 

### ISSUE THREAD

**Issue by gaur15** [Bookingjini-Labs/bookingjini-icons#192]
### Is your feature request related to a problem? Please describe.

In copyright line only bookinjini is visible in dark mode .

### Describe the solution you'd like

i would like improve the css of dark mode to view copyright clearly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
you talking about this right? 
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/46455250/b80dfd0d-d759-4e3b-8325-0de385b1e309)

**Comment by ks20soni** [comment]
It is actually not visible in the light mode, and I would like to change the CSS to make it visible.
![Screenshot 2023-06-02 at 2 18 23 PM](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/78134776/b4c561ae-a943-4a7f-bc7e-ce15d7bb2e93)

**Comment by gaur15** [comment]
> 

<img width="960" alt="Screenshot 2023-06-02 180426" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/133087361/ca1e520e-6fda-43ee-bdfc-714e0cb16345">
sir this is problem in light mode. Sorry for inconvenience but please assign this issue to me.

**Comment by AshutoshDash1999** [comment]
@gaur15 assigning this to you

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.
