### ISSUE TITLE
💡 [DOCS]: ADD PAGESPEED-INSIGHTS SCORE

### ISSUE THREAD

**Issue by 0xabdulkhaliq** [Bookingjini-Labs/bookingjini-icons#193]
### Is your feature request related to a problem? Please describe.

- There are a number of advantages to showing the PageSpeed Insights score in your GitHub repository. 
- First, it can help you identify areas where your website can be improved. 
- Second, it can help you attract users who are looking for websites with good performance. 
- Third, it can help you improve your search engine ranking.

### Describe the solution you'd like

- Google PageSpeed Insights is a free tool that helps you measure the performance of your website. It provides a score from 0 to 100, with higher scores indicating better performance. 
- The score is based on a number of factors, including the loading time of your website, the use of images and other resources, and the use of caching.
- My goal is to add the Score in `Svg` format, the main advantage is that i can develop the score in animated svg which is way more attractive and gives professional look to  the repository

### Example Image
 ![](https://github.com/0xabdulkhalid/interactive-rating-component/raw/main/images/pagespeed-insights-score.svg)

### Additional context
- Please assign me this issue under `gssoc23`, i would like to contribute to this repository.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@0xabdulkhalid thanks for raising this issue, but we don't need it for now.
