### ISSUE TITLE
Give attractive look to homepage by adding style and fixing alignment errors.Add footer as well.

### ISSUE THREAD

**Issue by raghav1482** [Bookingjini-Labs/bookingjini-icons#194]
### Is your feature request related to a problem? Please describe.

Adding footer along with making home page more attractive using css styling and js.

### Describe the solution you'd like

Using styling elements in css i would like to give the home page more attractive look.

### Describe alternatives you've considered

Also adding attractive footer is quite a bit required.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by raghav1482** [comment]
@AshutoshDash1999 Kindly assign me this issue (#194) under GSSOC 2023

**Comment by AshutoshDash1999** [comment]
@raghav1482 this issue is already covered
