### ISSUE TITLE
Favicon of the tab

### ISSUE THREAD

**Issue by suryanshsoni120** [Bookingjini-Labs/bookingjini-icons#197]
### Describe the bug

The symbol of Bookingjini Icons should be present as the favicon of the tab.

### Expected behaviour

 The favicon of the tab should be the same as the icon shown on the navbar.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@suryanshsoni120 assigning this to you

**Comment by imohit159** [comment]
Hello @AshutoshDash1999 I can see the title favicon is still not added to the website . And there is no response on this issue . If u assign this issue to me i would love to work on this .

**Comment by AshutoshDash1999** [comment]
Sure @itsmohit097
