### ISSUE TITLE
The website does not have meta tags with descriptions.

### ISSUE THREAD

**Issue by M-A-N-I-K** [Bookingjini-Labs/bookingjini-icons#198]
### Describe the bug

-     Issue: The website does not have meta tags with descriptions.
-     Impact: This means that the website is not as visible in search results, and users are less likely to click on the website's links.
    

### Expected behaviour

- Resolution: The website should add meta tags with descriptions to all of its pages. This will help the website rank higher in search results and attract more visitors.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@M-A-N-I-K feel free to work on this
