### ISSUE TITLE
Enhancing No result found section

### ISSUE THREAD

**Issue by NehaKariya0309** [Bookingjini-Labs/bookingjini-icons#199]
### Is your feature request related to a problem? Please describe.

On searching for an icon, if the icon is not available the output is No result found. However, since the website is itself an icons site, one can add an icon along with the no result found to enhance its look.

### Describe the solution you'd like

A catchy message along with an icon in the No Results found section would make the website look interactive.

Icons found on internet:
![Screenshot (87)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/100693529/62f4390e-b19d-4b7c-afbe-65d4698c0a9f)

### Additional context

As a GSSoC'23 contributor, I would like to add this feature. Features like these make the website engaging and interactive for users.
Thanks,
Neha Kariya

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@NehaKariya0309 feel free to work on this
