### ISSUE TITLE
Improving the header section and making Footer Section.

### ISSUE THREAD

**Issue by ghost** [Bookingjini-Labs/bookingjini-icons#20]
Hey Bookingjini,
I have seen your website and I am excited to work on some header and navigation improvements and make the footer section with extra enhancements. Please Assign this to me.

**Comment by AshutoshDash1999** [comment]
hi @584aditya can you please mention what exactly you want to improve and what do want to include in the header and footer section?

**Comment by ghost** [comment]
I think maybe there were less navigation menu with some normal stylings.
Let me enhance ui a little bit more like someone entering a coding platform.

If you have any kind of issue i which I can contribute my practise please let me know.

**Comment by ghost** [comment]
And maybe a nice footer with some social link and extra info about project to the footer with more enhanced ui

**Comment by AshutoshDash1999** [comment]
@584aditya you can add a footer section and include our social links, a little bit about us and our logo. Please make sure to include screenshots in your PR. Also make sure the UI matches with overall UI of our website.

**Comment by ghost** [comment]
Sir can you tell me which font style and bg color is used in this

**Comment by AshutoshDash1999** [comment]
Font: DM  Sans
Dark Mode colour: #2B2B2B

And please don't call me sir 🥲

**Comment by AshutoshDash1999** [comment]
@584aditya can you please update me on this issue?

**Comment by ghost** [comment]
currently i am working on it. Actually My end sem exams is going on that's why i am working on the section for not longer time. Let me Suggest a date before you want PR for this.

**Comment by Abhisharmika** [comment]
@584aditya I think i can work on a better footer for this website, following its theme
could you please assign me this issue:))

**Comment by AshutoshDash1999** [comment]
> currently i am working on it. Actually My end sem exams is going on that's why i am working on the section for not longer time. Let me Suggest a date before you want PR for this.

will 4th may work for u?

**Comment by ghost** [comment]
now my end sem exams are complete and I am also taking part in ACM hackCON held on 1st and 2nd june in delhi 
maybe i can make a PR before 5

**Comment by AshutoshDash1999** [comment]
@584aditya I am assigning this to someone for now. If you want to improve the then footer, please feel free to do so.

**Comment by AshutoshDash1999** [comment]
@Abhisharmika this issue is assigned to you, before submitting a PR please confirm the design of the footer

**Comment by Abhisharmika** [comment]
sure, and till when can i submit the footer?

**Comment by AshutoshDash1999** [comment]
@Abhisharmika please update within 3 days

**Comment by Abhisharmika** [comment]
@AshutoshDash1999 Isn't the dark mode running?

**Comment by AshutoshDash1999** [comment]
yes its working...try clicking on it 3-4 times. It's a bug and it needs to be fixed.

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.
