### ISSUE TITLE
Top Image-logo, Logo-text issue and light mode issue

### ISSUE THREAD

**Issue by ATOMworkplace** [Bookingjini-Labs/bookingjini-icons#200]
### Is your feature request related to a problem? Please describe.

**The top logo and logo text are not aligned properly. Icon issue with light mode**
![Screenshot 2023-06-01 142658](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114564628/7b296446-4aaf-4fbe-8d9a-7050e208f289)
![Screenshot 2023-06-01 142858](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114564628/8a17ad3f-94eb-4e84-b592-0ca0c8c94f0a)
![logoissue](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114564628/2414b306-4e79-46f6-a19b-4e8c67356428)

### Describe the solution you'd like

**I aligned both the logo and text and fixed issues with the light mode**

![logo](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114564628/85c486b2-f7a4-4c82-ae37-7b97e1b8cf9f)
![logo-mobile-preview](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114564628/c72734da-f50e-4841-954a-85e670de1f77)
![Screenshot 2023-06-01 145634](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114564628/303f0d6b-18a4-4d17-8b17-8d4dc9780c0c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ATOMworkplace** [comment]
I already resolved this issue and I have already created a pull request and changes can be seen in the screenshots. Please assign me this issue

**Comment by Visbhavesh** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by ATOMworkplace** [comment]
**Following changes have been made:**
![1-boj](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114564628/c41741e3-94a6-4c5f-8b00-db71fbe9d1ea)
![2-boj](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114564628/24573f5d-d95e-4018-800b-39087a898048)
![3-boj](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114564628/7ad83198-e9f3-49d1-82d0-a6ca466942e1)
![4-boj](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114564628/6093eb3c-fc0c-495b-a0af-39b7e53a5644)
  
**PR Top Image-logo and Logo-text issue #200 #201 is also submitted for the following**
