### ISSUE TITLE
[Docs]: Adding a new CONTRIBUTING.md to help new contributors.

### ISSUE THREAD

**Issue by Diveshmahajan4** [Bookingjini-Labs/bookingjini-icons#203]
### Is your feature request related to a problem? Please describe.

* In the current format, the contribution guidelines are present in the README.md. This make the README.md file too long. 
* Also there is no mention of CodeOfConduct in the README.md.
* In future, when we add more stats into README.md , it'll be hard to find contribution guidelines. 

### Describe the solution you'd like

* Creating  a new CONTRIBUTING.md file which will consist all the instructions related to contribution.
* We can add link to our Code of Conduct, Discord Channel.

### Additional context

_Please assign this issue to me under GSSoC'23_ @AshutoshDash1999 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Diveshmahajan4 please add only the contribution.md file to the repo.
