### ISSUE TITLE
[GSSOC-23]header section can be improved. The logo and other elements placement is messy. Making it responsive

### ISSUE THREAD

**Issue by samSoumyajitD** [Bookingjini-Labs/bookingjini-icons#204]
### Describe the bug

The placement of the logo at the top of the website is incorrect, and it fails to appear correctly on the screen. Furthermore, the responsive behavior of this particular section of the website requires improvement. The elements responsible for controlling the night/day mode, as well as the download and CDN functions, are awkwardly positioned and should be enhanced.

### Expected behaviour

It is necessary to correct the placement of the logo and relocate the download button, night/day mode control, and CDN retrieval to the top-left corner of the laptop screen.

### Screenshots

![heading11png](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/92439710/1bf77c21-899e-4fb7-81a9-587162dab7dd)

### Additional context

Hello Sir , I m a contributor of GSSOC-23 i want to contribute in  this project. Pls consider my inputs and allow be to condribute by assigning me this work under the label gssoc'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@samSoumyajitD thanks for bringing that up. This issue is already covered in #200
