### ISSUE TITLE
[GSSOC'23] Making the header section better looking / responsvie while in small screen

### ISSUE THREAD

**Issue by samSoumyajitD** [Bookingjini-Labs/bookingjini-icons#205]
### Is your feature request related to a problem? Please describe.

The header section of the website lacks visual appeal, particularly on smaller screens. Improvements are needed to enhance its responsiveness and optimize the placement of elements. Additionally, regulating the size of these elements to a predetermined value will ensure a more visually pleasing experience for users.
![123](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/92439710/6217705f-c382-493c-991d-c10cf5b321c3)

### Describe the solution you'd like

Implement a responsive design approach to ensure that the header section adapts well to different screen sizes and resolutions. This can include adjusting the placement, size, and spacing of elements.

Determine an appropriate size for the header elements that maintains a visually balanced composition. Avoid overly large or small elements that may disrupt the overall aesthetic

### Additional context

I m a contributor of GSSOC'23. I have a high interest in contributing to this project pls allow me to contribute in this by assigning me this issue under the label gssoc'23. I would be very grateful

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Visbhavesh** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by Visbhavesh** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by AshutoshDash1999** [comment]
@samSoumyajitD feel free to work on this..also pull the latest code before contributing and before submitting a PR

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.

**Comment by AshutoshDash1999** [comment]
@samSoumyajitD whats the status?

**Comment by samSoumyajitD** [comment]
@AshutoshDash1999 done sir by tonight I will send the PR.  Really sorry for the delay.

**Comment by AshutoshDash1999** [comment]
Reassigning this issue as the current assignee didn't gave any update.

@Visbhavesh do you want to work on this ?
