### ISSUE TITLE
Icon and Text Displacement Issue

### ISSUE THREAD

**Issue by aanya963** [Bookingjini-Labs/bookingjini-icons#206]
### Describe the bug

This issue is regarding a problem with the website where the icon and text in a particular section are being displaced from their intended position. Currently, the icon is appearing above the text, while it should be aligned to the left of the text. This issue is impacting the user experience and needs to be resolved.

### Expected behaviour

The icon and text should be aligned correctly, with the icon appearing to the left of the text.

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/101557638/bb9f9ecd-ac48-4b6e-958a-19c31608be02)

### Additional context

This issue is impacting the overall design of the website and making it look unprofessional. It is important to fix this issue to improve the user experience and maintain the brand image of the website.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
please check the latest review and feel free to create new issue based on that
