### ISSUE TITLE
Change "Get CDN" Button to "Star Repo" or "View GitHub"

### ISSUE THREAD

**Issue by premsaivarmachekuri** [Bookingjini-Labs/bookingjini-icons#207]
### Description of Feature Enhancement

The current header section contains a "Get CDN" button, which seems unnecessary since the CDN is already added directly to the website. This button may cause confusion for users and doesn't provide much value in its current form.

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/110842297/4ae4fdcf-2345-44fa-beec-e99f2d031a08)

### Solution

I propose changing the "Get CDN" button to either "Star Repo" or "View GitHub" to improve user engagement and provide additional information about the project. Here are the two options:

1. **Star Repo**- This button would allow users to easily star your repository on GitHub, indicating their interest and support for the project. It encourages community involvement and helps to showcase the project's popularity.

2. **View GitHub** - This button would redirect users to the GitHub repository of the project. It allows users to explore the project's codebase, documentation, and other relevant information. This can be helpful for users who want to understand the project more deeply or contribute to its development.

### Alternatives

In addition to the proposed changes, here are some alternative solutions or features that have been considered:

1. **Removing the button entirely:** One alternative option is to remove the button from the header section altogether. This would simplify the interface and eliminate any confusion caused by the "Get CDN" button. However, it may also reduce the visibility of the project's GitHub presence.

2. **Adding a "Contribute" button:** Instead of changing the "Get CDN" button, another option is to introduce a separate button specifically for contributing to the project. This button could lead users to a dedicated contribution guide or provide information on how to get involved. It would emphasize the project's openness to contributions and encourage community engagement.

These alternatives have been evaluated, but I believe that changing the "Get CDN" button to either "Star Repo" or "View GitHub" would provide the best balance between user engagement, project visibility, and providing additional context about the project.

### Additional context

I am participating in GSSOC23 and would like to contribute by suggesting this feature enhancement. I have prior experience in proposing and implementing similar improvements on various projects, which I believe would be valuable in enhancing the user experience of website.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@premsaivarmachekuri feel free to work on this
