### ISSUE TITLE
Content in Button Not Changing to Dark Mode When Light Mode is Selected

### ISSUE THREAD

**Issue by KeyurGK** [Bookingjini-Labs/bookingjini-icons#21]
Hello,

I would like to change the content of the mode button when the light mode is selected to dark mode and vice versa.
<img width="955" alt="image" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/56074740/f13c387a-fcdd-4b5e-a3cb-10640218a9dd">
I want to contribute and add value to this project under GSSoC 23. Looking forward!
 Thanks and Regards,
Keyur.

**Comment by AshutoshDash1999** [comment]
Hi @KeyurGK thanks for mentioning that. Go ahead, we would like to see what wonders you can do 😊.

**Comment by vk20july** [comment]
@AshutoshDash1999 sir can I do this task under gssoc'23

**Comment by KeyurGK** [comment]
> @AshutoshDash1999 sir can I do this task under gssoc'23

@vk20july I have already pulled a request for this #225

**Comment by vk20july** [comment]
> > @AshutoshDash1999 sir can I do this task under gssoc'23
> 
> @vk20july I have already pulled a request for this #225

ok
