### ISSUE TITLE
Addition of favicon

### ISSUE THREAD

**Issue by mohdshahzil** [Bookingjini-Labs/bookingjini-icons#211]
### Is your feature request related to a problem? Please describe.

Addition of favicon on the website will make it more appealing and better. It will attract users and will make our web page look classy.

### Describe the solution you'd like

I will add favicon to it with Bookingjini logo.

### Additional context

Assign this task to me under GSSoc'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
this issue has already covered
