### ISSUE TITLE
Make changes to the CSS of header 

### ISSUE THREAD

**Issue by ks20soni** [Bookingjini-Labs/bookingjini-icons#215]
### Describe the bug

The header of the website has some unnecessary paddings/margins also the CSS of the header is not very attractive I would like to work on it. 

### Expected behaviour

Remove any extra margins/paddings, make some font changes to the website name on the header and change the position of Download, Get CDN and switching modes buttons. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@ks20soni assigning this to you

**Comment by priyanka7976** [comment]
Hello @ks20soni , I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.
