### ISSUE TITLE
Making the website responsive to diverse screen sizes.

### ISSUE THREAD

**Issue by KeyurGK** [Bookingjini-Labs/bookingjini-icons#22]
Hello,
the website can be made responsive to diverse screen sizes.
I want to contribute and add value to this project under GSSoC 23. Looking forward!
Thanks and Regards,
Keyur.

**Comment by AshutoshDash1999** [comment]
Sure @KeyurGK, please go ahead. Do follow best practices and write maintainable code.

Thank you

**Comment by KeyurGK** [comment]
@AshutoshDash1999 Thanks for assigning !

**Comment by AshutoshDash1999** [comment]
@KeyurGK any update on this??

**Comment by KeyurGK** [comment]
In progress, pulling in a request soon.

**Comment by mandliyarajendra11** [comment]
@AshutoshDash1999 issue is still open ?? i want to work on this issue can you assign me this issue

**Comment by KeyurGK** [comment]
> @AshutoshDash1999 issue is still open ?? i want to work on this issue can you assign me this issue
> 

Thanks, but I am working on this and PR soon.

**Comment by mandliyarajendra11** [comment]
> Keyur.

okkk 👍 )

**Comment by AshutoshDash1999** [comment]
@KeyurGK please don't hold up a issue, as you can see i have already closed many related issues for this. Submit a PR within 2 days or I will be closing this issue.

**Comment by KeyurGK** [comment]
> @KeyurGK please don't hold up a issue, as you can see i have already closed many related issues for this. Submit a PR within 2 days or I will be closing this issue.

Please close this issue / assign to others. Due to some personal commitments, I cannot contribute enough time to this. Apologies for holding up.
