### ISSUE TITLE
Improving Search functionality

### ISSUE THREAD

**Issue by Deepanshu0703** [Bookingjini-Labs/bookingjini-icons#221]
### Is your feature request related to a problem? Please describe.

When you type a letter in the search section it searches a filter out the data. But the thing is it is matching exact same value means if a user types "P" then it is showing no data but on giving "A"  shows result so i want to add this functionality in the search that no matter the letter is Lowercase or Upper case it just matches that name and if it is same then show it in result. also there are some error in the search section.

I have added these screenshots to explain

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114489502/92f813a8-f60e-4e99-a0a8-86a98b0a260e)

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114489502/3cada20f-e60a-4ac1-99b6-3f02901e674f)

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114489502/c35ffe30-f3df-4105-b802-79452fe9c8b7)

Do assign it to me, I want to contribute . 

### Describe the solution you'd like

I will lowercase both the letters to match so that it is not judged by the casiing and by the only the letter.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Deepanshu0703 assigning this to you

**Comment by AshutoshDash1999** [comment]
@Deepanshu0703 any update on this?

**Comment by AshutoshDash1999** [comment]
Closing this issue as assignee failed to give any update.
