### ISSUE TITLE
Bug in the README file : Picture can be improved for the darkmode

### ISSUE THREAD

**Issue by Hardikaz** [Bookingjini-Labs/bookingjini-icons#223]
### Describe the bug

# The GsSOC logo is not properly visible in the dark mode . Here is the screenshot of it.

- 
![WhatsApp Image 2023-06-03 at 22 41 21](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/95474096/6b7778a2-4244-4802-ad62-cfdce0a0e3cb)

- I intend to change it with a bright picture where the font color will be in white colour.
- Please assign me this issue as I'm in GSSOC'23.

### Expected behaviour

- I intend to change it with a bright picture where the font color will be in white colour.
- Please assign me this issue as I'm in GSSOC'23.

### Screenshots

![WhatsApp Image 2023-06-03 at 22 41 21](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/95474096/6b7778a2-4244-4802-ad62-cfdce0a0e3cb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Hardikaz will it be visible in light mode?

**Comment by Hardikaz** [comment]
Yes sir  The image will be visible in both light and dark mode. Pls assign me this issue under GSSOC'23

**Comment by AshutoshDash1999** [comment]
ok then. assigning this to you. Make sure to submit your PR with screenshots
