### ISSUE TITLE
PR Template in .yml format

### ISSUE THREAD

**Issue by ManasMadan** [Bookingjini-Labs/bookingjini-icons#224]
### Is your feature request related to a problem? Please describe.

Pull Request Template means when someone opens a Pull Request, they will have a template that they can edit making it easier for maintainers of the project to review PR and make sure that no PR is submitted without proper description.

### Describe the solution you'd like

I will create a PR Template accoring to GitHub Rules

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ManasMadan** [comment]
@AshutoshDash1999 Please assign me this under GSSoC 23

**Comment by AshutoshDash1999** [comment]
@ManasMadan this issue is already covered. You want to add  on top of it?

**Comment by ManasMadan** [comment]
@AshutoshDash1999 Is the issue closed because the PR Template is in md format i want to contribute a yml format PR Template. As yml format can handle logic also

**Comment by AshutoshDash1999** [comment]
@ManasMadan what are the conditions you want to add?

**Comment by ManasMadan** [comment]
No New Conditions as such Just Logic Check on Existing Input and some basic basic fields @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
can you give me some example?

**Comment by ManasMadan** [comment]
Advantages of YAML Format for PR Templates
1. Readability and Maintainability
YAML's clean and intuitive syntax enhances the readability of PR templates. Its indentation-based structure promotes easy comprehension and maintenance of the template. Developers can quickly understand the different sections, steps, and configurations defined in the template, leading to improved collaboration and reduced confusion.

2. Flexibility and Extensibility
YAML supports a wide range of data types and allows for complex data structures. This flexibility enables the creation of comprehensive PR templates that can adapt to project-specific requirements. Developers can define custom sections, environment variables, conditional logic, and more within the template, ensuring that all necessary information is captured in a standardized manner.

3. Integration with Automation Tools
YAML-based PR templates seamlessly integrate with various automation tools and frameworks. Continuous Integration (CI) platforms like GitHub Actions, CircleCI, and GitLab CI/CD are built to interpret YAML files directly. This integration allows for automated execution of defined steps, enabling efficient and consistent PR reviews. Additionally, YAML-based PR templates can trigger automated workflows, perform tests, and even deploy code to designated environments.

4. Version Control
As YAML PR templates reside within the project repository, they become part of the version control system. This integration ensures that changes made to the templates can be tracked, reviewed, and rolled back when necessary. Developers can collaborate on improving the PR templates over time, utilizing the power of version control tools to manage revisions effectively.

5. Separation of Concerns
Using YAML for PR templates enables a clear separation of concerns between the template structure and the actual content. The template structure remains consistent, allowing developers to focus on populating the template with relevant information specific to each PR. This separation streamlines the process and encourages adherence to the defined template structure, reducing human errors and ensuring consistent PR documentation.

**Comment by ManasMadan** [comment]
@AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
> Just Logic Check on Existing Input and some basic basic fields

I asked for examples for this.
