### ISSUE TITLE
Improve hover properties

### ISSUE THREAD

**Issue by aparna03dubey** [Bookingjini-Labs/bookingjini-icons#226]
### Is your feature request related to a problem? Please describe.

Details:
I want to change the hover properties so as to make the website look more pleasing and attractive.
Please assign this issue to me.

### Describe the solution you'd like

I will add some significant changes when one hovers on to the Website name in light and dark mode.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hardikaz** [comment]
I m already assigned to do that.

**Comment by silky-modi22** [comment]
please assign this to me under gssoc 2023

**Comment by dhruv8433** [comment]
i would like to work on this under gssoc'23
