### ISSUE TITLE
want to change light mode button and make responsive

### ISSUE THREAD

**Issue by shubham-01-star** [Bookingjini-Labs/bookingjini-icons#23]
look like this

![Screenshot 2023-05-20 104910](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/72158457/cff97e88-cb7b-42ce-adca-969db4433e12)

**Comment by AshutoshDash1999** [comment]
Hi, @shubham-01-star that's great. Although your issue is already covered in #21  and #22.
