### ISSUE TITLE
Add some more icons

### ISSUE THREAD

**Issue by Durgesh4993** [Bookingjini-Labs/bookingjini-icons#232]
### Is your feature request related to a problem? Please describe.

can i add some more icons, because there are some icons are mising..
and also there are no favicion in your website can i add 

### Describe the solution you'd like

I add some icons in a svg format

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Hi @Durgesh4993 thanks for raising this issue. But we are not adding more icons for now.
