### ISSUE TITLE
Add icons [GSSOC'23]

### ISSUE THREAD

**Issue by Enhancer18** [Bookingjini-Labs/bookingjini-icons#234]
### Is your feature request related to a problem? Please describe.

Not exactly a problem but there are very few icons available in the website currently.

### Describe the solution you'd like

I would like to add 5-6 icons related to hospitality.
Like manager,..etc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Hi @Enhancer18  thanks for raising this issue. But we are not adding more icons for now.
