### ISSUE TITLE
Add Table of contents to readme[GSSOC'23]

### ISSUE THREAD

**Issue by Enhancer18** [Bookingjini-Labs/bookingjini-icons#235]
### Is your feature request related to a problem? Please describe.

User cannot go directly to something he is searching in readme file , he has to read full readme file to find a specific part.

### Describe the solution you'd like

Making a table of contents for readme file makes it easier for users to navigate through readme file with ease. They can directly click on the link to go to required section.
It will look similar to this:
![Screenshot_2023-05-28-09-34-39-51_320a9a695de7cdce83ed5281148d6f19~2.jpg](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/102911149/9b73fe1a-01cb-4c60-808f-e4518fbb1622)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Hi @Durgesh4993 thanks for raising this issue. But we don't need it for now/
