### ISSUE TITLE
User Experience [HOME PAGE]

### ISSUE THREAD

**Issue by yashpreet2707** [Bookingjini-Labs/bookingjini-icons#236]
### Describe the bug

The margin (top and bottom ) of is way to much and is not looking good.

<img width="1440" alt="Screenshot 2023-06-05 at 2 54 30 PM" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/111020648/cc1c964a-24e5-487b-a7a1-79c8e56daf68">

### Expected behaviour

This looks much better than the current one, as in the prev one the search bar is in very bottom area, but now it is looking good.

<img width="1440" alt="Screenshot 2023-06-05 at 2 59 51 PM" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/111020648/2535299e-877b-4e02-a391-1d875eed39f1">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NANDHINI45** [comment]
I am interested to work on this issue can you please assign me this issue under GSSOC'23 @AshutoshDash1999

**Comment by yashpreet2707** [comment]
@AshutoshDash1999 I've made the PR, and sorry for the late response.

**Comment by yashpreet2707** [comment]
@AshutoshDash1999 I've reconsidered your changes, now it looks good ig

**Comment by yashpreet2707** [comment]
@AshutoshDash1999 I've reconsidered your changes, now it looks good ig
<img width="1427" alt="Screenshot 2023-06-22 at 2 26 11 PM" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/111020648/da5c44fc-4f46-49b2-9064-1cdbf7e70393">
