### ISSUE TITLE
IMPROVING FOOTER-Section [GSSOC'23]

### ISSUE THREAD

**Issue by fantasticbuddy** [Bookingjini-Labs/bookingjini-icons#238]
### Is your feature request related to a problem? Please describe.

I went through the website and noticed that the footer-section needs some improvement. This issue aims to enhance the footer by adding valuable content and essential links that will improve user engagement and provide easy access to important resources.

Current footer is -

![Screenshot 2023-06-06 022232](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114503561/e2384202-4a56-4273-9df8-cf580ab709b4)

### Describe the solution you'd like

I would like to add popular social media icons (e.g., Twitter, Facebook, LinkedIn, etc.) into the footer, linking to the project's official social media profiles. This will facilitate social sharing and help users stay connected with the project.

After updating the footer would look like this -

![Screenshot 2023-06-06 023710](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114503561/64349266-ca68-4a22-a901-068173828dea)

If you like this enhancement kindly assign me this issue under GSSOC'23.
@AshutoshDash1999 
Thankyou.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@riyaVerma1726 assigned this to you

**Comment by fantasticbuddy** [comment]
Thankyou .

**Comment by VSatwika** [comment]
@AshutoshDash1999 May I work on this as it's already been 3 weeks?

**Comment by AshutoshDash1999** [comment]
@VSatwika this issue is already resolved #240
