### ISSUE TITLE
GROUPING ICONS - Category [GGSSOC'23]

### ISSUE THREAD

**Issue by fantasticbuddy** [Bookingjini-Labs/bookingjini-icons#239]
### Is your feature request related to a problem? Please describe.

I went through the page and found that currently, the icons on the page are displayed without any categorization, making it difficult for users to locate specific icons or understand their purpose at a glance. 
This issue proposes the addition of icon categorization to improve user experience and provide better organization of the icons.

### Describe the solution you'd like

PROPOSED SOLUTION -
 - We can introduce category labels or headings to group the icons based on their functionalities. For example, create categories like "Social Icons," "Common Icons," and "Household Icons" to classify the icons according to their respective purposes.
 - Also we can add visual elements to differentiate between the categories by using different background colors, dividers, or section headers to clearly differentiate each category.
 - Along with this we can implement navigation or search functionality that allows users to quickly jump to a particular category or search for specific icons within a category, avoiding the need to scroll down and go through each category.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@riyaVerma1726 this issue is already covered #114

**Comment by fantasticbuddy** [comment]
Ok ok
If it's not yet done or the assigned person is not giving any response kindly assign it to me. I would like to work on it.
Thankyou.

**Comment by AshutoshDash1999** [comment]
@riyaVerma1726 i have closed that issue since the other person didn't update anything after 4 days. assigning this to you.

**Comment by fantasticbuddy** [comment]
@AshutoshDash1999 
Thankyou
Will respond to you on this soon with the changes.

**Comment by fantasticbuddy** [comment]
I have made category wise distribution in the page -
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114503561/c1cf61f7-f508-443c-a3db-21c0c270fcb3)

kindly review and suggest changes. This is completely responsive.
@AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
yeah its good. please make sure about the UI when user searches for something

**Comment by fantasticbuddy** [comment]
Yes, everything is kept in consideration.
Also, do you want any specific grouping type or should i do it accordingly. Currently i have made 4 groups.

**Comment by AshutoshDash1999** [comment]
@fantasticbuddy we are fine with your own categories.

**Comment by fantasticbuddy** [comment]
Regarding navbar for category -
![Screenshot 2023-06-07 220419](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114503561/64ed3e07-721b-405f-821a-79da5e99d0ca)

![Screenshot 2023-06-07 220441](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114503561/fa95bc07-3dd4-45e3-93e6-4bd999ff6bd9)

![Screenshot 2023-06-07 220449](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114503561/ae8e4adb-c00d-42c6-a34a-4e660d1f4c95)

Is this fine. Do you want some changes in the styling.
Please mention.
@AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
umm no...it's not looking good. try some other designs or let it be.

**Comment by AshutoshDash1999** [comment]
please keep the theme gray/black for the light mode too
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/46455250/5b531976-5424-4b79-81ee-8a28281e8adb)

**Comment by fantasticbuddy** [comment]
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114503561/3fd73419-c030-46b8-b41c-ff2e1bd82206)

Is this one okay for light theme.

**Comment by AshutoshDash1999** [comment]
yeah better

**Comment by fantasticbuddy** [comment]
okaay lemme push the changes.
Everything else is working fine. The UI on searching is also checked.

**Comment by fantasticbuddy** [comment]
Kindly review and merge the request.
If you want any changes please mention.

**Comment by AshutoshDash1999** [comment]
please mention the PR number

**Comment by fantasticbuddy** [comment]
@AshutoshDash1999  this is regarding PR #249
