### ISSUE TITLE
update in css file

### ISSUE THREAD

**Issue by divyanshiet** [Bookingjini-Labs/bookingjini-icons#24]
I would to contribute in the CSS file of the site, There is a need of updating the labels of the icons and also improvement in the designing of the icons was also required. Kindly assign it to me under GSSOC'23

**Comment by bookingjini** [comment]
> I would to contribute in the CSS file of the site, There is a need of updating the labels of the icons and also improvement in the designing of the icons was also required. Kindly assign it to me under GSSOC'23

Thank you, @divyanshiet, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by divyanshiet** [comment]
> > I would to contribute in the CSS file of the site, There is a need of updating the labels of the icons and also improvement in the designing of the icons was also required. Kindly assign it to me under GSSOC'23
> 
> Thank you, @divyanshiet, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

do you have any social media presence?? if yes kindly provide their links and handle

**Comment by bookingjini** [comment]
@divyanshiet, indeed, we do have a presence on social media. For more information, you can follow our website page where you will find all our social media handles listed in the footer section. - https://bookingjini.com/
