### ISSUE TITLE
Improving Navbar Design

### ISSUE THREAD

**Issue by ShreyaDhiman24** [Bookingjini-Labs/bookingjini-icons#242]
### Is your feature request related to a problem? Please describe.

Navbar is invisible and not alighned properly.

### Describe the solution you'd like

It can be aligned properly.

### Describe alternatives you've considered

Can use glassmorphism to make it look better along with responsiveness.

### Additional context
Assign me this issue under GSSoC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by afreen-ahmed12** [comment]
hyyy.....please alllow me to do this task?

**Comment by afreen-ahmed12** [comment]
@ShreyaDhiman24 please assign me this task.... I want to do this
