### ISSUE TITLE
Issue: Text not visible properly on hover

### ISSUE THREAD

**Issue by DivyanshiNarang** [Bookingjini-Labs/bookingjini-icons#244]
Text is not visible properly on hover.

On hover, the content becomes unreadable.

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74779601/76d01849-3c62-4f72-af18-d9737814f1e8

<img width="309" alt="Screenshot 2023-06-06 235135" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74779601/bf72ad39-14a3-476c-98b9-31e366bc119b">

whereas it should be in contrast color i.e. white

<img width="326" alt="Screenshot 2023-06-06 235124" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74779601/33474bec-16c1-4b71-aeb3-3717916c2e90">

*Please assign this issue to me under GSSoC'23*
@AshutoshDash1999

**Comment by afreen-ahmed12** [comment]
hey...I want to do this task @dhruvaop

**Comment by AshutoshDash1999** [comment]
@DivyanshiNarang assigning this to you

**Comment by dhruvaop** [comment]
Hey, @afreen-ahmed12, it seems that the task you mentioned is already assigned to @DivyanshiNarang.
