### ISSUE TITLE
[feat]:Adding an attractive hover effect on social links

### ISSUE THREAD

**Issue by Dimple-01** [Bookingjini-Labs/bookingjini-icons#247]
feature?

I would love to add an attractive hover effect in the social links of the site. It will be more attractive and appealing.

Solution

I will make changes as shown.

![current social link](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114878264/2d37386d-207f-487b-8e7c-5a8badb9cf1e)

![new social link](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114878264/7e131ca6-5c52-4b9d-8e1e-64ce83771001)

Please give me a chance to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarb2003** [comment]
PLEASE ASSIGN ME THIS TASK  UNDER GSSOC'23

**Comment by dhruv8433** [comment]
I would like to work on that under GSSOC 23

**Comment by AshutoshDash1999** [comment]
We dont' want to add that as we want our site to be minimalist
