### ISSUE TITLE
Search Bar Looks Too Light 

### ISSUE THREAD

**Issue by shubham-shinde-442** [Bookingjini-Labs/bookingjini-icons#25]
As Contributor in GSSoC"23 , I Would like to Work on This Issue . Can You Assign me This Issue ?

![Screenshot (674)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/123376721/b2b23a48-18b0-4e05-910d-b016bc6de7cf)

**Comment by AshutoshDash1999** [comment]
hi @shubham-shinde-442, we would like to see some mockups on the search bar design part. Then only we could assign it.

**Comment by shubham-shinde-442** [comment]
Sure , Here are some mockups :

1)
![d6](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/123376721/8e5344b2-f1c0-4f71-9502-a8cf6af4178c)

2)
![d2](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/123376721/156b3401-78fb-42d9-b5ba-d09f0f79370f)

3)
![d4](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/123376721/f79275c3-6fc9-43fa-8b0b-da371626bdf9)

Or Please Suggest me .

**Comment by AshutoshDash1999** [comment]
@shubham-shinde-442 Please follow this one. With the icon, also write `search icon` in the placeholder

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/46455250/6c96da85-f860-420e-a6d4-b11324bd5693)

**Comment by shubham-shinde-442** [comment]
Ok , assign me

**Comment by AshutoshDash1999** [comment]
Assigned. We would love to see what magic you can bring. 😊
