### ISSUE TITLE
Add favicon to make logo appear on browser tab

### ISSUE THREAD

**Issue by poorvijn** [Bookingjini-Labs/bookingjini-icons#250]
I think adding a favicon would make the website look more professional.
Right now, a default browser icon is visible.

Here is how it looks right now:

![logo](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/87180220/71074e1f-bc5b-4648-bc99-9ed0e23222bb)

Could you please assign this to me under GSSoC'23?

**Comment by NANDHINI45** [comment]
@AshutoshDash1999 sir i am interested to work on this issue kindly assign me this issue under GSSoC'23

**Comment by AshutoshDash1999** [comment]
@poorvijn assigned this to you

**Comment by Sandeep77942** [comment]
Is this issue still open? I would like to work on it if it's open.
