### ISSUE TITLE
Adding a header section containing all the buttons

### ISSUE THREAD

**Issue by Illaf** [Bookingjini-Labs/bookingjini-icons#257]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

The buttons in the website are looking like scattered. I will align them up in a well defined header section which contains the download button, star repo ,dark mode and The logo as well
This will make the website look more clean

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
The website has all the buttons aligned.
We don't need this for now.
