### ISSUE TITLE
responsive UI(footer)

### ISSUE THREAD

**Issue by Yoogiitaa** [Bookingjini-Labs/bookingjini-icons#258]
### Describe the bug

Hey,
> the footer section of the website does not have proper responsiveness.
> if we are changing the screen size, the move-up button and footer does not align.

### Expected behaviour

when the screen size changes the footer should cover corners of the screen.

### Screenshots

![Screenshot (5)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/98513887/5126bc63-e394-4ca8-ae82-a494a6d329fe)

### Additional context

Please assign this issue to me. under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Yoogiitaa the footer section is updated. Please check if you can improve something.

**Comment by Yoogiitaa** [comment]
its alright but the progress button is overlapping with text inside footer. it will be better if we could stop it at the starting of footer.
![Screenshot (32)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/98513887/f8a2b13d-d31f-4766-84c4-fa823c9225ef)

correction-> 

![Screenshot (21)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/98513887/03908d6a-85d6-446a-97dd-7a2ecbf8fbb5)
can i change it like this

**Comment by AshutoshDash1999** [comment]
@Yoogiitaa Please go ahead

**Comment by priyanka7976** [comment]
Hello @Yoogiitaa , I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.

**Comment by Yoogiitaa** [comment]
Hi @priyanka7976, I am working on this issue.

**Comment by AshutoshDash1999** [comment]
@Yoogiitaa please update

**Comment by AshutoshDash1999** [comment]
Closing this issue as assignee failed to give any update.
