### ISSUE TITLE
Improvising the UI for different devices

### ISSUE THREAD

**Issue by abhayy143** [Bookingjini-Labs/bookingjini-icons#26]
### Issue 
As of you can see in the picture below the main title **Bookingjini** is not fully visible for an mobile. 

![5](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/53009878/5391268e-648f-4816-9c66-badb7fc4717c)

As a contributor for GSSoc 23 I want to fix this issue.

**Comment by AshutoshDash1999** [comment]
Hi @abhayy143, your issue is already covered in #22
