### ISSUE TITLE
[REQUEST] - Improve Navbar UI and Enhance Hover Effects

### ISSUE THREAD

**Issue by Amitavpanda** [Bookingjini-Labs/bookingjini-icons#261]
### Is your feature request related to a problem? Please describe.

The current navbar UI lacks visual appeal and the hover effects on the navbar buttons are not engaging enough. This can lead to a suboptimal user experience and may hinder the overall usability of the website/application.

### Describe the solution you'd like

I propose to improve the navbar UI and enhance the hover effects on the navbar buttons. The goal is to create a visually appealing and interactive navigation experience for users. 

The following changes should be implemented:

- Redesign the navbar to have a modern and aesthetic appearance.
- Implement smooth transitions and animations for the hover effects on the navbar buttons.
- Enhance the visual feedback when a button is in the active or focused state.

### Additional context

It is crucial to ensure that the improved navbar UI and hover effects are consistent across different devices and screen sizes to provide a seamless user experience.

**I would like to work on this issue under GSSOC'23.**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amitavpanda** [comment]
@ramanujamgond I would like to work on this issue under GSSOC'23, can you assign me this task.

**Comment by abansal15** [comment]
@ramanujamgond I would like to work on this issue under GSSOC'23, can you assign me this task. I will use the amazing animations and enhance the navbar user ui

**Comment by AshutoshDash1999** [comment]
> Redesign the navbar to have a modern and aesthetic appearance.

Can you let me know what exactly do you want to add?

**Comment by abansal15** [comment]
> > Redesign the navbar to have a modern and aesthetic appearance.
> 
> Can you let me know what exactly do you want to add?

I want to add a more animated download button, and want to increase the size of the dark reader button and try to add the hamburger for the mobile view so that it look attractive. Could you please assign this issue to me ?
