### ISSUE TITLE
New Revamped Logo

### ISSUE THREAD

**Issue by soumizde** [Bookingjini-Labs/bookingjini-icons#262]
### Is your feature request related to a problem? Please describe.

The current logo is does not have any context or provide any information about its purpose of the application. 

### Describe the solution you'd like

I want to create a logo that will resonate with the brand and make the website look and feel more professional. 

### Describe alternatives you've considered

I want to create a DESIGN.md file in the repo and then subsequently add logo and some other iterations in the file. Other people can also contribute to it and come up with suggestions. We can then have a poll on what looks the best and then we can change the logo from the assets.

### Additional context

I am a UI/UX designer and developer. I feel like branding is an essential part of a company. So for the sake of future growth, we should definitely use something that looks and feels good for the brand.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@soumizde the logo used is the official logo of [Bookingjini](https://www.bookingjini.com).
We don't want it to change.

Feel free to explore other issues related to UX/UI in the site though.
