### ISSUE TITLE
Enhancement of page layout

### ISSUE THREAD

**Issue by Dimple-01** [Bookingjini-Labs/bookingjini-icons#264]
### Is your feature request related to a problem? Please describe.

**The current layout doesn't seem to be attractive much.**

 **Current behavior**

![Screenshot (86)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114878264/80e5a7b6-78b4-414b-85f6-9f0bf3388459)

![Screenshot (87)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114878264/213e4ef7-fb61-4cdf-b621-ee547b83f40e)

### Describe the solution you'd like

**I want to add some effects so that it would become more engaging and attractive.**

**Desired behavior** 

![Screenshot (84)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114878264/ce7a093e-6074-4578-bf19-241464cf2495)

![Screenshot (85)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/114878264/5815202c-048c-404a-8888-2ec29247ec25)

### Describe alternatives you've considered

 I will dedicate efforts to improving the visual aspects of the page by adding CSS to it. The CSS styling techniques to modify the appearance of the icon will make it more visually appealing and intuitive for users. This involved customizing the icon's color, size, and positioning to create a consistent and coherent design.

Furthermore, I will make sure to consider responsive design principles while implementing the CSS changes. I ensured that the page remained visually appealing and functional across different screen sizes and devices.

### Additional context

I want to work on this issue.
Please assign this to me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Dimple-01 although we really appreciate your effort, but the suggested changes are not needed by our team. We would encourage you to explore other issues though.
