### ISSUE TITLE
Font size problem in the <h3> heading

### ISSUE THREAD

**Issue by Kaivanshah1** [Bookingjini-Labs/bookingjini-icons#266]
### Describe the bug

when the mode is changed from light to dark the font size of the text : 
      Find hospitality related icons, curated by creators from Bookingjini
changes 
<img width="812" alt="image" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/110343220/907d7ecd-24fa-4111-89a8-484a9e6bcb94">
<img width="791" alt="image" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/110343220/ab010436-777e-47bd-98c8-0adce7b5022f">

please assign me this issue 

### Expected behaviour

in both, the text should be of same font size
<img width="767" alt="image" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/110343220/6ba6415b-a144-4465-bb1b-616122dffc13">

<img width="782" alt="image" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/110343220/bf9c1eae-af4a-4fd4-8806-21917edc0e66">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Kaivanshah1 assigning this to you

**Comment by priyanka7976** [comment]
Hello @Kaivanshah1, I am GSSoc contrbutor. I would like to work on the issue pls assign it to me

**Comment by AshutoshDash1999** [comment]
Closed issue no more valid.
