### ISSUE TITLE
Adding a preloader

### ISSUE THREAD

**Issue by Shreyans2004** [Bookingjini-Labs/bookingjini-icons#267]
### Is your feature request related to a problem? Please describe.

Your website is very beautiful .It will become more beautiful if while loading ,a preloader will be there. I can add the preloader to the website so that looks better.Can you assign this task to me?

### Describe the solution you'd like

I want to add a preloader

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abansal15** [comment]
I would also like to work on the issue could u pls assign it to me  ?

**Comment by AshutoshDash1999** [comment]
@Shreyans2004 Thanks for the suggestion though, but we don't need this for now.
