### ISSUE TITLE
Margin and padding of the sections are not proper (On mobile size device)

### ISSUE THREAD

**Issue by LadityaGogoi** [Bookingjini-Labs/bookingjini-icons#27]
![2](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/108052802/08267316-7da0-4222-b8d8-da6264c379b4)

### ISSUE:
it is clearly seen that items of the website heading towards left instead of center, which gives the website an ugly impression

### SOLUTION
I will arrange all the items with proper margin and padding

Please assign this issue to me, under @GSSOC

**Comment by bleep123** [comment]
Hi,
I would like to work on this issue. Please assign it to me.

**Comment by AshutoshDash1999** [comment]
Hi thanks for commenting, but this issue is already covered in #22
