### ISSUE TITLE
[Feature]: Maintain Separate Group Section for Similar Category of Icons 

### ISSUE THREAD

**Issue by NarendraKoya999** [Bookingjini-Labs/bookingjini-icons#272]
## Issue Description:
- We have lot of Different Icons in Our Website.
- **My Request is Maintain Separate Group Section for Similar Category of Icons.**
- **And Also Create Separate Side Bar For This Feature for Better Maintainability.**

### Example:
-  **Suppose, Bookingjini Website has Some WiFi Related Icons .**
- **So, Create Group Namely Internet and Maintain this similar WiFi Related Icons put into This Group.** 

### Solution Steps:
- **Create Separate Side Bar Section for Maintaining Different Kinds of Group Sections.**
-` Example: `**Internet, Navbar, Action, Links, Technology Related Ones.**
- **Suppose, when Click on Internet related Group Button. Only that related Icons Present in Webpage like WiFi, No-WiFi Etc.**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@NarendraKoya999 this issue is already covered
