### ISSUE TITLE
Adding a newsletter subscription in the footer

### ISSUE THREAD

**Issue by linga66** [Bookingjini-Labs/bookingjini-icons#273]
### Is your feature request related to a problem? Please describe.

In the footer we can add the newsletter subscription in the footer, so they can be notified when posted new icon

### Describe the solution you'd like

![242856919-ae5ed2e3-3895-43c4-9672-837f5de6e9a2](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/103192975/d3cb71b7-cb9f-43ec-9ee8-26e99faaff30)

A sample of the design which I want to add.

### Additional context

Please assign me this issue so I can contribute to it. @bookingjini 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@linga66 thanks for the suggestion but we don't need this though.
