### ISSUE TITLE
Typewriter effect in main text

### ISSUE THREAD

**Issue by Anshika-Jain02** [Bookingjini-Labs/bookingjini-icons#276]
### Is your feature request related to a problem? Please describe.

To improve the visual appearance of the overall website through my enhancement.

### Describe the solution you'd like

*I want to add a typewriter effect in the main text "Find hospitality related icons, curated by creators from bookingjini". This will produce a dynamic effect on the overall website.*

![bookingjini](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/104912087/6d754fa5-ba5f-4dd4-8de6-0728c3972696)

@AshutoshDash1999 Please assign me this issue under gssoc'23. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sachi-shah** [comment]
Please assign me this issue. I would like to work on it under GSSOC'23.

**Comment by AshutoshDash1999** [comment]
@Anshika-Jain02 thanks for the suggestion, but we don't need this for now.
