### ISSUE TITLE
[Bug]: Maintain Separate JavaScript File Remove Clumsy Phase in index.html

### ISSUE THREAD

**Issue by NarendraKoya999** [Bookingjini-Labs/bookingjini-icons#277]
### Issue Description:
- **Maintain Separate JavaScript File and Remove Clumsy Phase in `index.html`.**
- **In` index.html,` Heavy JavaScript Code put in `<head></head> `Section and` <body></body> `Section.**
- **I recommend to Create Separate` JavaScript File` and Store Entire JavaScript Code in Respective` JavaScript File`.**
- **At a Time, Remove JavaScript Code in `index.html `File.**

### Expected behaviour

- **Remove Entire JavaScript Code in `index.html `and That code put in Whatever Creating Separate `JavaScript File`.**
- **It is Better Practice for `Programmers and Developers to Improve Maintainability and Clean Code.`**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@NarendraKoya999 assigning this to you

**Comment by NarendraKoya999** [comment]
Thanks for Assigned this Issue To Me. I complete this issue as soon as possible.

**Comment by NarendraKoya999** [comment]
Hi @AshutoshDash1999  I Completed PR . I am Checking that Website after changes, No Errors Happens. Kindly Review and Merge It

**Comment by NarendraKoya999** [comment]
Hi @AshutoshDash1999 . **It' Already Merged. Please Close this Issue and Related PR also**
