### ISSUE TITLE
Bookingjini icons title -  Light theme 

### ISSUE THREAD

**Issue by isandhyadev** [Bookingjini-Labs/bookingjini-icons#278]
### Is your feature request related to a problem? Please describe.

In light theme, the title - Bookingjini icons does not seem attractive as it of light grey which is not that much visible.

### Describe the solution you'd like

The title - BOOKINGJINI ICONS 
![Screenshot (236)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/95486852/21d22cc3-9b4e-418a-a9f8-71cf420090e1)
By changing the color of title ,it can be more attractive so that the user can find it more attractive, and visit it again and again 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@isandhyadev assigning this to you

**Comment by AshutoshDash1999** [comment]
Closed due to inactivity.
