### ISSUE TITLE
Adding a favicon to the website

### ISSUE THREAD

**Issue by abhayy143** [Bookingjini-Labs/bookingjini-icons#28]
![6](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/53009878/02290691-61f5-4ecd-b22c-3f0ab61f8031)

As a GSSoc Contributor I want to raise and fix this issue by adding a Favicon to the website. Favicons serve as a visual representation of the website and typically displayed in the browser's tab, bookmarks bar, and browser history.

**Comment by abhayy143** [comment]
I've added a PR that resolves this issue under GSSoc'23

**Comment by bookingjini** [comment]
> ![6](https://user-images.githubusercontent.com/53009878/239672403-02290691-61f5-4ecd-b22c-3f0ab61f8031.JPG)
> 
> As a GSSoc Contributor I want to raise and fix this issue by adding a Favicon to the website. Favicons serve as a visual representation of the website and typically displayed in the browser's tab, bookmarks bar, and browser history.

Thank you @abhayy143 for your response. Feel free to proceed with your code contribution. Kindly provide a screenshot while you do the pull request.

**Comment by abhayy143** [comment]
I'm a GSSoC contributor and I've added a Pull Request at #29 

Am i supposed to add the screenshot of the code snippet along with the PR ?
