### ISSUE TITLE
Add website icon to Bookingjini Icons website 

### ISSUE THREAD

**Issue by singodiyashubham87** [Bookingjini-Labs/bookingjini-icons#281]
### Is your feature request related to a problem? Please describe.

It's not a problem but an enhancement.

kindly assign me this issue under gssoc23

![Screenshot from 2023-06-16 23-44-14](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/93720428/ba7882e7-6af8-4801-8b90-0e567d611184)

### Describe the solution you'd like

I'll add the icon of website into the index.html file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
We are not accepting Favicons for now.
