### ISSUE TITLE
The Icon copied div touches the top of website

### ISSUE THREAD

**Issue by singodiyashubham87** [Bookingjini-Labs/bookingjini-icons#283]
### Describe the bug

The vanishing time of icon copied div is too much so if someone clicks on any icon continuously then it touches the top of the website.

### Expected behaviour

It should vanish a little bit early.

### Screenshots

![Screenshot from 2023-06-16 23-48-20](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/93720428/dc4b98de-11a3-4b82-919d-38b8ecafa4be)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Sorry, we don't need this for now.
