### ISSUE TITLE
Adding dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [Bookingjini-Labs/bookingjini-icons#284]
*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@AshutoshDash1999 please assign me this issue under gssoc'23.

**Comment by AshutoshDash1999** [comment]
Thanks, @Anshika-Jain02 for the suggestion. But we don't need it for now as we don't have any dependencies.
