### ISSUE TITLE
Adding auto_comment.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [Bookingjini-Labs/bookingjini-icons#285]
*We need to add an auto-comment.yml that will automatically welcome, greet and provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively. This will promote motivation and performance*

@AshutoshDash1999 Please assign me this issue under gssoc'23

**Comment by AshutoshDash1999** [comment]
Thanks, @Anshika-Jain02 for the suggestion. But we don't need it for now.
