### ISSUE TITLE
Add a creative Footer Scetion

### ISSUE THREAD

**Issue by deepeshmlgupta** [Bookingjini-Labs/bookingjini-icons#286]
### Is your feature request related to a problem? Please describe.

It's not a problem but to have a good footer makes a website look cool and easy for a user to get the details about the social media handles and many more important part from the bottom also.

### Describe the solution you'd like

I have a quite good solution for your website to add a attractive and informative footer section which will consist of all the important information about the website and all the official social media handles.

### Additional context

before
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/108192513/054ece83-2319-4bc8-bd9e-47813209b2ce)

I can create a footer like this
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/108192513/ca528982-14ca-4718-8903-84d77b4b31c9)

So Please assign me this issue under GSSOC'23 so that I can start working on it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Sorry, we don't need this for now.
