### ISSUE TITLE
improving css of bright theme

### ISSUE THREAD

**Issue by ich-tanishqa** [Bookingjini-Labs/bookingjini-icons#287]
### Describe the bug

When switched to bright mode the website looses its coolness a bit. I think by changing some fonts and other CSS we can make it more attractive.

### Expected behaviour

Just like the dark mode the website needs to look WOW in bright mode too

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ich-tanishqa** [comment]
@AshutoshDash1999 I really wanna work on this please assign me this

**Comment by AshutoshDash1999** [comment]
what exactly you want to improve?

**Comment by ich-tanishqa** [comment]
The css of the dark theme is awesome but when we switch to bright theme
somethings become dull and we can also make it more colourful

**Comment by AshutoshDash1999** [comment]
@ich-tanishqa do you have any prototype or rough diagram of what you want to do?
