### ISSUE TITLE
Adding favicon

### ISSUE THREAD

**Issue by ich-tanishqa** [Bookingjini-Labs/bookingjini-icons#288]
### Is your feature request related to a problem? Please describe.

We should add a favicon to make it more attractive.

### Describe the solution you'd like

Adding a favicon 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abansal15** [comment]
hello @AshutoshDash1999 i would like to work on this issue please assign it to me

**Comment by AshutoshDash1999** [comment]
We are not accepting issues related to favicon as it's not showing up when hosted live due to some error.
