### ISSUE TITLE
Small Bug : Light-dark toggle button has wrong initialization

### ISSUE THREAD

**Issue by Sachin4219** [Bookingjini-Labs/bookingjini-icons#291]
### Describe the bug

When the page loads the default theme is dark but the toggle slider shows the light theme.

### Expected behaviour

The light-dark toggle button should be at dark mode as it is default theme

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/91952010/258009c3-f312-4d5a-93fb-251e41aac43d)

### Additional context

You can view the bug at 
https://icons.bookingjini.tech/ 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Sachin4219 assigned this to you

**Comment by AshutoshDash1999** [comment]
@Sachin4219 any update on this?

**Comment by khadar1020** [comment]
can i work on this issue @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
@khadar1020 assigning this to you

**Comment by khadar1020** [comment]
thanks for assigning sir @AshutoshDash1999
