### ISSUE TITLE
Not showing icon

### ISSUE THREAD

**Issue by pavitrachavda97** [Bookingjini-Labs/bookingjini-icons#292]
### Describe the bug

When user type one character in search bar it is showing not found however there is present icons from that character. 

### Expected behaviour

When user type one character in search bar it should show all present icons from that character. 

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/91004608/083ce296-ead0-42e5-a1e4-1f8d3a9b6eaf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VijayalakshmiGanesh** [comment]
Hi, 

I would like to work on this issue. Can this be assigned to me under GSSOC'23 label please. Thank you

**Comment by AshutoshDash1999** [comment]
@pavitrachavda97 assigning this to you
