### ISSUE TITLE
search box is not working properly 

### ISSUE THREAD

**Issue by mandliyarajendra11** [Bookingjini-Labs/bookingjini-icons#293]
### Describe the bug

1. I am not getting accurate results when typing anything in the search box. For example, if I type 'a,' the search results should display all icons starting with 'a,' but only 1 or 2 icons are appearing.
2. debouncing concept is not present in search box - In the context of a search box, debouncing is a technique used to control and optimize the execution of search queries or other related actions triggered by user input. When a user types into a search box, it often results in frequent events firing, such as keypress or input events. Each event may trigger an action, such as sending a request to a server to retrieve search results or updating the search suggestions.

### Expected behaviour

All icons related to the searched word or sentence should appear, and the performance should be improved by implementing debouncing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@mandliyarajendra11 assigning this to you
