### ISSUE TITLE
expand more button

### ISSUE THREAD

**Issue by mandliyarajendra11** [Bookingjini-Labs/bookingjini-icons#294]
### Is your feature request related to a problem? Please describe.

In the future, if more icons are added, scrolling down to reach the lower sections, such as the footer, might become problematic.

### Describe the solution you'd like

There should be a "Expand More" or "Show More" button that, upon clicking, will load additional icons on the same page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Sorry we don't need this for now.
