### ISSUE TITLE
Make the logo on the home page clickable

### ISSUE THREAD

**Issue by MutiatBash** [Bookingjini-Labs/bookingjini-icons#295]
### Is your feature request related to a problem? Please describe.

GSSOC 23

The logos on the homepage aren’t clickable. Related to a user experience problem. Most users expects that the logo takes them back to the homepage or reloads the homepage.

### Describe the solution you'd like

When a user clicks on the logo, it should navigate back to the homepage.

### Describe alternatives you've considered

I’ll like to add the website link to the logos to make them clickable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abansal15** [comment]
Hello @MutiatBash  I would like to work on the issue pls assign it to me

**Comment by MutiatBash** [comment]
> 

Hello @abansal15 I’m also a contributor that raised the issue so I’ll work on it
You can visit the live site and see if there’s any modifications you’ll like to make

**Comment by AshutoshDash1999** [comment]
@MutiatBash you can add link to our official website on clicking the logo.

**Comment by MutiatBash** [comment]
@AshutoshDash1999 

is it the main website - https://bookingjini.com/

or the icons website- https://icons.bookingjini.tech/

**Comment by AshutoshDash1999** [comment]
The main company website is:
https://bookingjini.com/

**Comment by MutiatBash** [comment]
https://github.com/Bookingjini-Labs/bookingjini-icons/pull/312

Created a pull request

**Comment by AshutoshDash1999** [comment]
> is it the main website - https://bookingjini.com/

yes

**Comment by priyanka7976** [comment]
Hello @MutiatBash, I am GSSoc contrbutor. I would like to work on the issue pls assign it to me
