### ISSUE TITLE
Add dependabot.yml

### ISSUE THREAD

**Issue by VSatwika** [Bookingjini-Labs/bookingjini-icons#296]
### Is your feature request related to a problem? Please describe.

 - I would like to add Dependabot to the repository for automated dependency updates. 

 - Could this issue be assigned to me under GSSoC'23? Thank You

### Describe the solution you'd like

-  Regularly updating dependencies is essential to address security vulnerabilities, bug fixes, and performance improvements.  
-  Dependabot can automate this process by regularly checking for new versions of dependencies and creating pull requests to update them. 
- This will save us time and effort in manually tracking and updating dependencies. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Sorry we don't need this for now.
