### ISSUE TITLE
Improve Pull Request Template 

### ISSUE THREAD

**Issue by VSatwika** [Bookingjini-Labs/bookingjini-icons#297]
### Is your feature request related to a problem? Please describe.

 - The current pull request template is vey basic and only contains the headings of related issue, descriptions and screenshots.
 - I would like to improve the pull request template by adding necessary content.
 - I would like to work on this issue under GSSoC'23. Could this be assigned to me? Thank You.

### Describe the solution you'd like

 - I would like to add a checklist to make sure the contributor has followed the necessary guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
> * I would like to improve the pull request template by adding necessary content.

what do you want to add?
