### ISSUE TITLE
Making Major Change in Home Page Making Interactive

### ISSUE THREAD

**Issue by PatilHarshh** [Bookingjini-Labs/bookingjini-icons#299]
### Is your feature request related to a problem? Please describe.

lets make home page interactive @bookingjini  

### Describe the solution you'd like

making home page interactive UI Changes
![Screenshot (94)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/120102234/371945e9-b9e5-463d-bb78-e78b0a62b852)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
> making home page interactive UI Changes

like?
