### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [Bookingjini-Labs/bookingjini-icons#30]
I want to add readme badges.
.Please assign this issue to me under GSSOC
![badges](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/104543751/fff65819-c8f5-4527-b78a-5d27c8a395b2)

**Comment by Arnab7456** [comment]
can i started working this part

**Comment by bookingjini** [comment]
> I want to add readme badges. .Please assign this issue to me under GSSOC ![badges](https://user-images.githubusercontent.com/104543751/239673462-fff65819-c8f5-4527-b78a-5d27c8a395b2.png)

Thank you @S-ishita for your response. Feel free to proceed with your code contributions. We kindly request that you adhere to the code standards and kindly provide a screenshot along with the pull request.
