### ISSUE TITLE
Inconsistent Dark Mode Behavior on Website

### ISSUE THREAD

**Issue by pavitrachavda97** [Bookingjini-Labs/bookingjini-icons#300]
### Describe the bug

When accessing the website, the page automatically switches to dark mode. However, the mode selection button suggests that the current mode is "light mode" creating confusion for users. Additionally, when attempting to switch to light mode by clicking the button, the change does not occur immediately. Instead, it requires a double click for the mode to switch correctly.

### Expected behaviour

- When the website is opened, the mode selection button accurately reflects the current mode (i.e., "dark mode")
- Clicking the mode selection button once should immediately switch the page to the corresponding mode (e.g., light mode if "light mode" is displayed).
- Users should not be required to double click the mode selection button to achieve the desired mode.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
assigning this to you
