### ISSUE TITLE
[BUG]: errors reported on browser's console

### ISSUE THREAD

**Issue by harmeetsingh11** [Bookingjini-Labs/bookingjini-icons#301]
### Description of the bug

There are some errors reported on the browser's console when website is loaded. It needs to be fixed.

### Environment:
- OS: Windows
- Browser: Chrome

### Screenshots

![Capture](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/130365071/dd4d6a21-a021-4a57-afb1-0d77b6412494)

### Checklist

- [x] I have read the Contributing Guidelines
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### Expected behaviour

There should be no errors or warnings on browser's console as it creates a bad impression to the user.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@harmeetsingh11 assigned this to you
