### ISSUE TITLE
Toggle button need enhancement.

### ISSUE THREAD

**Issue by HimanshuNarware** [Bookingjini-Labs/bookingjini-icons#304]
### Is your feature request related to a problem? Please describe.

The toggle button present in the website it not working properly ,it need styling enhancement, I want to work on this issue,

### Describe the solution you'd like

Want to give styling to the button, and also when some click on the icon the sun button is translate in wrong direction first, also want to give more effective look to the button

### Describe alternatives you've considered

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/83147410/11354e17-a760-42bf-b621-85366dcfc41a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@HimanshuNarware assigning this to you
