### ISSUE TITLE
Add a back to the home page Navigation for the logo at the footer

### ISSUE THREAD

**Issue by PoulavBhowmick03** [Bookingjini-Labs/bookingjini-icons#305]
### Is your feature request related to a problem? Please describe.

The logo in the footer is currently unresponsive. I would like to change that

### Describe the solution you'd like

Add navigation to the logo so that it takes the user back to the top of home page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PoulavBhowmick03** [comment]
@AshutoshDash1999 please check this issue

**Comment by AshutoshDash1999** [comment]
> Add navigation to the logo so that it takes the user back to the top of the home page

It's already there. We have to click-to-top button.
