### ISSUE TITLE
Add Twitter in  Social media platform

### ISSUE THREAD

**Issue by mdfaizahmad1** [Bookingjini-Labs/bookingjini-icons#306]
### Is your feature request related to a problem? Please describe.

yes, user can see new features in twitter also, Please assign me in GSSOC23

### Describe the solution you'd like

user can see new features in twitter and other Social media handles.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ParthMadhvani2** [comment]
Hey, I am a GSSOC'23 contributor can add a Twitter icon in the footer so can you please assign this issue to me?

**Comment by AshutoshDash1999** [comment]
Thanks for your suggestion but we are not planning to add it for now.
