### ISSUE TITLE
Version Text getting black

### ISSUE THREAD

**Issue by hereisSwapnil** [Bookingjini-Labs/bookingjini-icons#308]
### Describe the bug

When the version text on the home page is clicked and is active the text gets black 

### Expected behaviour

The text should not get balck when clicked/active

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/85278243/cdf5e6f1-070a-4e2d-9029-22e52d45db65)

[Screencast from 21-06-23 07:18:04 PM IST.webm](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/85278243/d2b51bcc-3d91-4106-bf4a-1f198a47ef0f)

### Additional context

Please assign me this issue under GSSOC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Swapnil-Singh-99 assigning this to u
