### ISSUE TITLE
Add favicon icon at correct path 

### ISSUE THREAD

**Issue by Parul1606** [Bookingjini-Labs/bookingjini-icons#309]
### Favicon Icon 
The bug I have discovered is: The bookbinding-icons webpage is not able to display its favicon logo properly.  There's an issue in the code, the file is not placed at the correct location which has to be added at the proper location.

### Expected behaviour

I expected that the webpage will display its favicon logo but it ain't able to configure the file from other folders. I have found the bug and would like to fix it. 
I have added the image consists where I have found the bug, its location and code. 

### Screenshots

1. Issue pic: - 
(i). 
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/80768852/e7c22324-9f76-4934-b3e6-aecfb8615a0c)
(ii). 
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/80768852/9333e4a1-f0d2-428c-b963-4da5c3bb85f9)

2. What I expect and will configure: -
![Screenshot 2023-06-21 203537](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/80768852/f3d3e8ff-c52f-4266-9955-beb79b5b3a18)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Parul1606** [comment]
Please assign me this issue I would like to work on it.

**Comment by Parul1606** [comment]
Hello @AshutoshDash1999 @ramanujamgond,
I have seen 2 such same issues have been raised before and yet this issue has not been solved. Please let me also try it. I have gone through it one time and my code is working too. I assure you this issue will be solved soon.

**Comment by AshutoshDash1999** [comment]
Hi @Parul1606 please feel free to submit a PR. After submitting a PR please check if the favicon appears in preview deploy link.

**Comment by Parul1606** [comment]
So, that means I am assigned this issue?

**Comment by AshutoshDash1999** [comment]
Yes

**Comment by Parul1606** [comment]
Ok..thank you 🙌
