### ISSUE TITLE
Add Footer section

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [Bookingjini-Labs/bookingjini-icons#31]
@AshutoshDash1999, As a gssoc'2023 contributor I want to contribute to this issue

**Comment by bleep123** [comment]
Hi,
I would like to work on this issue. Please assign it to me.

**Comment by bookingjini** [comment]
> @AshutoshDash1999, As a gssoc'2023 contributor I want to contribute to this issue

Thank you @MOHDNEHALKHAN  for your response. Feel free to proceed with your code contributions. We kindly request that you adhere to the code standards and kindly provide a screenshot while doing a Pull request.

**Comment by MOHDNEHALKHAN** [comment]
@AshutoshDash1999 Thank you for assigning me 
I have a query regarding the contribution
1. which branch do I have to fork, main or dev(default)
2. For contribution I can create an (issue branch) at my forked repo and after that, I can PR it

**Comment by AshutoshDash1999** [comment]
@MOHDNEHALKHAN 
1. please fork `dev` branch and make sure you raise the PR against the `dev` branch
2. please do that

**Comment by MOHDNEHALKHAN** [comment]
@AshutoshDash1999 Thank you for answer i will commit PR Asap

**Comment by MOHDNEHALKHAN** [comment]
@AshutoshDash1999, I have added a footer with social icons , Now can I create a PR
For light mode -
![Screenshot 2023-05-22 001143](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/125626654/464c57a1-8466-4fd1-88ef-5103e26511a4)
For dark mode -
![Screenshot 2023-05-22 001056](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/125626654/b4d88171-a633-435a-abba-9ad042042b5c)
Review it and tell me

**Comment by AshutoshDash1999** [comment]
@MOHDNEHALKHAN I really appreciate your effort but can you try redesigning and explore some examples

**Comment by MOHDNEHALKHAN** [comment]
@AshutoshDash1999 Ok I will see some examples  but before that can I create a PR now 
I mean in second PR i can redesign it or first i have to redesign it.

**Comment by AshutoshDash1999** [comment]
Sorry, @MOHDNEHALKHAN we can't do that. We strive to maintain a smooth UI/UX for visitors. Accepting that PR will result in "not so good" UI, hence we can't risk that for now.

**Comment by MOHDNEHALKHAN** [comment]
@AshutoshDash1999 Can you please share me example of UI design which you like 
So that i can make that kind of footer

**Comment by AshutoshDash1999** [comment]
something link logo on the left and social icons on the left. Please maintain symmetry.

**Comment by vk20july** [comment]
@AshutoshDash1999 sir can i do this task under gssoc'23

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.

**Comment by AshutoshDash1999** [comment]
@priyanka7976 please don't spam every issue. Understand the issue and see what you can do.
