### ISSUE TITLE
Add the Instagram icon

### ISSUE THREAD

**Issue by parmesh-bhatt** [Bookingjini-Labs/bookingjini-icons#310]
### Is your feature request related to a problem? Please describe.

In the icon section Instagram icon is not there.

### Describe the solution you'd like

Add the Instagram icon in the icon section

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parmesh-bhatt** [comment]
I am working on this issue. Please assign it to me.

**Comment by dhruvaop** [comment]
Are you still working on this issue @Parmesh119

**Comment by parmesh-bhatt** [comment]
Yes

**Comment by dhruvaop** [comment]
Please ensure to include a screenshot whenever you make any changes on GitHub. This will help provide a visual reference and make it easier for others to understand the modifications you have made. @Parmesh119

**Comment by AshutoshDash1999** [comment]
@Parmesh119 as mentioned in #311, we are not accepting any more icons
