### ISSUE TITLE
Enhancement on the UI of the website 

### ISSUE THREAD

**Issue by ignaviaa** [Bookingjini-Labs/bookingjini-icons#313]
### Is your feature request related to a problem? Please describe.

Just want to cut off the space in the beginning and re-arrange the header part and with fonts too.

### Describe the solution you'd like

I would like to add a proper header and remove the unnecessary space which is taking up in the top half and rearrange the sections in a beautiful way and i would like to change the fonts too and the font colour of the heading as it's making the whole thing the same !

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Can you create a mockup for what you want to do?

**Comment by ignaviaa** [comment]
@AshutoshDash1999 am sorry for the inconvenience but I can't really show you any mockups at the moment as i am out of station, can you please close the issue or assign it to someone else? I am really sorry for it.

**Comment by AshutoshDash1999** [comment]
Thanks for letting me know. Really appreciate this.
