### ISSUE TITLE
`Bookingjini Icons (v2.0)` on the header is not working 

### ISSUE THREAD

**Issue by ignaviaa** [Bookingjini-Labs/bookingjini-icons#314]
### Is your feature request related to a problem? Please describe.

The `[Bookingjini Icons (v2.0)](https://icons.bookingjini.tech/#)` is not working as i hover in it it's changing the colour , but it doesn't take up to another link or anything .

### Describe the solution you'd like

 We can make a separate page on that link and the page will be on everything on and abouts , updates or major fixes on the Bookingjini Icons.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhruvaop** [comment]
Are you still working on this issue @ignaviaa do you have any relevant screenshot that the changes you have made

**Comment by ignaviaa** [comment]
@dhruvaop actually nope, i was waiting for it to be assigned to me if it's legit or not .

**Comment by dhruvaop** [comment]
yes it is legit @ignaviaa

**Comment by ignaviaa** [comment]
okay i'll start working in it asap ☺️

**Comment by AshutoshDash1999** [comment]
any update on this?
