### ISSUE TITLE
On copying the href link the copy image turns to a tick symbol.

### ISSUE THREAD

**Issue by Sh4dab** [Bookingjini-Labs/bookingjini-icons#317]
### Is your feature request related to a problem? Please describe.

Hello, I am a GSSOC'23 Contributor.
I would like to add this that while copying this link part the copy image will turn to a tick symbol which after copying turns back to same copy image.

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/97034961/0b41b5cc-3552-4421-bb23-d57671bfe371)

### Describe the solution you'd like

I will just change the image source in the eventlistener function and in setTimeout change the source to the previous.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Sh4dab assigning this to you
