### ISSUE TITLE
Convert Images to WebP Format for Improved Project Performance

### ISSUE THREAD

**Issue by Avinash905** [Bookingjini-Labs/bookingjini-icons#318]
### Is your feature request related to a problem? Please describe.

Currently, the images in the project are stored in the PNG/JPG image format. However, I would like to convert them to the more efficient WebP format. This conversion will help us reduce file sizes while maintaining image quality, leading to improved website performance and faster loading times. This issue aims to update the entire project's image assets from PNG/JPG to WebP format.

### Describe the solution you'd like

In order to optimize the project's image assets and enhance user experience, I propose converting all the PNG images to WebP format. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by AshutoshDash1999** [comment]
We don't need this for now.
