### ISSUE TITLE
Adding how to use on the website and adding fav icon

### ISSUE THREAD

**Issue by sumitkr2000** [Bookingjini-Labs/bookingjini-icons#32]
Hey @AshutoshDash1999 I want to add a how to use section and improve the UI a little bit. Please assign me this issue. Thank you!

**Comment by bookingjini** [comment]
Thank you @sumitkr2000 for your response. Kindly specify what exactly you would like to improve in terms of UI.

**Comment by sumitkr2000** [comment]
These are the improvement I want to make:-
1. Add a fav icon
2. Add a footer so that people can know that it is an open-source project.
3. Add documentation on the website.

**Comment by AshutoshDash1999** [comment]
@sumitkr2000 The above issue is already addressed in:
1. #29 
2. #20 
3. #39
