### ISSUE TITLE
Project Admins and Mentors in ReadMe

### ISSUE THREAD

**Issue by smty2018** [Bookingjini-Labs/bookingjini-icons#321]
### Is your feature request related to a problem? Please describe.

want to add project admins and mentors with their github socials in the read me , so that it is easier for contributors to tag/ contact them regarding queries.
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74114936/9de98004-c55d-45cc-bcfc-72463b4f7184)

### Describe the solution you'd like

want to add project admins and mentors with their github socials in the read me , so that it is easier for contributors to tag/ contact them regarding queries.
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74114936/9de98004-c55d-45cc-bcfc-72463b4f7184)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by smty2018** [comment]
@AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
@smty2018 sorry we don't need this for now
