### ISSUE TITLE
[Animation] Adding animation to the home page

### ISSUE THREAD

**Issue by ManishaSwain8** [Bookingjini-Labs/bookingjini-icons#322]
### Is your feature request related to a problem? Please describe.

To make a website look alive and attractive ,adding animation is best option,and it is in React using Framer Motion is best choice for animation which will attract the user .
If this new feature req. do assign under GSSOC 2023.
Changes will be done keeping the website theme in mind  : |)

### Describe the solution you'd like

Framer Motion animation in home section,footer.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Very overdo for a simple icon site
