### ISSUE TITLE
Search Bar is not working properly

### ISSUE THREAD

**Issue by Git21221** [Bookingjini-Labs/bookingjini-icons#324]
### Describe the bug

Whenever I try to search "x/X" the relevent image is not coming up.

### Expected behaviour

It should show all marks that is like x or cross

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/101005577/9feee161-f914-4382-9f0a-8cd934c6dca0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
duplicate issue
