### ISSUE TITLE
hovering effect on icons

### ISSUE THREAD

**Issue by Git21221** [Bookingjini-Labs/bookingjini-icons#325]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/101005577/464b9a1c-c2bd-4d44-b589-a3e08bc4ff9b)
When we hover we can see a transition but when we remove our mouse there is no transition.

### Describe the solution you'd like

I will add a transition at the end.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Git21221 assigning this to you

**Comment by AshutoshDash1999** [comment]
@Git21221 any update on this?

**Comment by khadar1020** [comment]
please assign me this issue @AshutoshDash1999

**Comment by Git21221** [comment]
> @Git21221 any update on this?

yeah updaing
