### ISSUE TITLE
Dark Mode + NavBar issue

### ISSUE THREAD

**Issue by Somesh-Mallewar** [Bookingjini-Labs/bookingjini-icons#326]
### Describe the bug

Hello Project Admin, 
There is a issue in the DarkMode when it's refresh the page or just open the page. It is not responding according to the button.

### Expected behaviour

When the page is loaded then it is on dark mode even after tapping on dark mode button.
It should respond according to the button

## video: 
https://github.com/Bookingjini-Labs/bookingjini-icons/assets/118499404/c26db74e-3ab6-4716-b861-7cd518f3f783

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Somesh-Mallewar any update on this?

**Comment by Somesh-Mallewar** [comment]
@AshutoshDash1999 it is a bit complicated for me. I have to change the button. Give me some time.

**Comment by AshutoshDash1999** [comment]
@Somesh-Mallewar any update?
