### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by sumitkr2000** [Bookingjini-Labs/bookingjini-icons#327]
### Is your feature request related to a problem? Please describe.

I want to add a favicon to the website. Please assign me this issue. Thank you!

### Describe the solution you'd like

Add a favicon

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sumitkr2000** [comment]
Please assign me this issue so that I can start working on it.

**Comment by AshutoshDash1999** [comment]
favicon is added
