### ISSUE TITLE
Changing the fonts and give new style to the website

### ISSUE THREAD

**Issue by sahithi-1729** [Bookingjini-Labs/bookingjini-icons#330]
The font of the text used in website is giant which makes it pretty ugly to look at. Hence I would like to give a good change to the website

**Comment by Snigdha2712** [comment]
Please assign this issue to me. I would like to work on it @bookingjini

**Comment by AshutoshDash1999** [comment]
@sahithi-1729 can you create a mockup of what you want to change?
