### ISSUE TITLE
[GSSOC'23] Footer enhancement

### ISSUE THREAD

**Issue by ritika1408** [Bookingjini-Labs/bookingjini-icons#331]
### Is your feature request related to a problem? Please describe.

Footer of the website plays a very important role in case of engagement.

### Describe the solution you'd like

I would like to make some changes in the footer section as it seems a little bit disordered.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KHADIJA-09** [comment]
Hello !
Please assign me this task.

**Comment by AshutoshDash1999** [comment]
We don't need this for now.
