### ISSUE TITLE
I want to add few new icons 

### ISSUE THREAD

**Issue by I-shika** [Bookingjini-Labs/bookingjini-icons#333]
### Is your feature request related to a problem? Please describe.

I want to some new icons as many are not present.

### Describe the solution you'd like

The icons I want to add :
1) Payments or Rupees 
2) Chats or messages 
3) notifications
4) Filled Home icon 
5) Meeting Time
6) Reports or Attachments
7) Logout 

Please assign this issue to me under GSSoC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by I-shika** [comment]
Please look into this issue  @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
Although thanks, but we are not accepting any more icons.
