### ISSUE TITLE
want to add few icons

### ISSUE THREAD

**Issue by BhartiNagpure** [Bookingjini-Labs/bookingjini-icons#334]
### Is your feature request related to a problem? Please describe.

Add few icons so that it gives different types of icons in one platform

### Describe the solution you'd like

I want to add icons related to transporation like ambulance, car etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KHADIJA-09** [comment]
Please assign me this task.I want to add icons related to transporation like ambulance, car etc.

**Comment by BhartiNagpure** [comment]
I would like to work on this.

**Comment by AshutoshDash1999** [comment]
We are not accepting any more icons for now.
