### ISSUE TITLE
Add Preloader to website 

### ISSUE THREAD

**Issue by Prajwal0225** [Bookingjini-Labs/bookingjini-icons#336]
### Problem Description

When visiting the website, there is no visual indication that the content is being loaded, leading to a perception of slow or unresponsive behavior.

### Describe the solution you'd like

 I suggest adding a preloader animation that is displayed while the website content is being loaded. This will provide a visual indication to users that the website is still loading and prevent them from experiencing a blank or unresponsive page during the loading process.

### Additional context

Can you please assign this issue to me under gssoc'23? So that I can start working on it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Sorry we don't need this for now.
