### ISSUE TITLE
 Implement Filtering Options for Icons through Categories, Labels, and Chips

### ISSUE THREAD

**Issue by Nishitbaria** [Bookingjini-Labs/bookingjini-icons#338]
### Is your feature request related to a problem? Please describe.

I would like to suggest an enhancement for the iconson by implementing filtering options. Currently, there is no functionality available to filter icons based on categories, labels, or chips, which makes it challenging to find specific icons within the repository.

### Describe the solution you'd like

1. Categories: Enable the ability to filter icons based on different categories. This would allow users to narrow down their search and locate icons related to specific categories, such as "weather," "communication," "finance," and more.

2. Labels: Introduce labels that can be assigned to icons to provide additional metadata. Users should be able to filter icons by selecting one or more labels. For example, labels could include "outline," "filled," "colored," "flat," etc., allowing users to easily find icons based on their preferred style.

3. Chips: Implement the use of chips as visual tags associated with icons. Each chip would represent a specific characteristic or attribute of an icon. Users can click on a chip to filter icons that possess the corresponding attribute. This would provide a convenient way to filter icons by properties like "arrow," "checkmark," "star," "person," and more.

These filtering options would greatly enhance the usability of the icon repository, allowing users to quickly find icons that match their specific requirements. It would simplify the search process, improve navigation, and save valuable time for users looking for icons.

I believe the addition of these filtering features would greatly benefit the icon repository and contribute to an enhanced user experience. Thank you for considering this feature request. If you require any further information or assistance, please let me know and please assign me this issue.

### Additional context

Please assign me this issue,I will complete it asap

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Nishitbaria can you share any kind of UI that you are planning to make?

**Comment by Nishitbaria** [comment]
@AshutoshDash1999 ,I will follow your ui theme just implement filtering through chips of categories

**Comment by Nishitbaria** [comment]
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/85815172/bb8cd6d2-6429-4d39-80bb-0f0035e969f0)
This are just example i will use theme  according to your website,please assign me this issue,i will create pull request today and you can review it

**Comment by AshutoshDash1999** [comment]
ok this looks good

**Comment by Nishitbaria** [comment]
@AshutoshDash1999 ,You need to give me json array of icon with category field so i can filter them?

**Comment by AshutoshDash1999** [comment]
the json is already there in the folder. It's not possible for us to label each icon for now (in terms of time and effort)

**Comment by AshutoshDash1999** [comment]
@Nishitbaria are you still working on this?
