### ISSUE TITLE
Incorrect spelling of icon

### ISSUE THREAD

**Issue by Uma-95** [Bookingjini-Labs/bookingjini-icons#34]
**Please describe the problem**
The spelling of "Confetti" is shown as "Confetty."

**Describe the solution you'd like**
I would like to change it to the correct spelling.

**Screenshot**
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/99042417/256482f2-05f4-45fd-a9af-aa232e418298)

**Comment by Uma-95** [comment]
@bookingjini  I'm a GSSOC'23 contributor.Could you please assign this issue to me as a part of GSSOC'23.

**Comment by AshutoshDash1999** [comment]
ok @Uma-95, go ahead and make sure to commit in your separate branch and tag this issue to your PR.

**Comment by Avilash-Saha** [comment]
An api is used to fetch the contents of a spreadsheet where the icon data is stored in form of a JSON file . The spelling correction has to be done in the google sheet  and the owner of this repository has access to it. We cannot make any changes unless we are given access to the google sheet. 
I am a GSSoC'23 contributor. I would like to work on this issue. please provide me access to the google sheet.                                    
I have requested access to it. email: avilashsaha1234@gmail.com 
There are similar issues #49 and #50. I will address that aswell. thank you

**Comment by Avilash-Saha** [comment]
I requested permission from the spreadsheet owner(@bikidsx) to edit and correct the spelling errors. They have granted me permission to edit it. I have fixed issue #34, #49 and #50. These issues doesn't need a PR. Thank you.

**Comment by AshutoshDash1999** [comment]
Hi, @Avilash-Saha we are indebted towards you for contributing to our project and making it better. People like you make us believe in open-source contributions. Unfortunately, since there is no PR, so this fix can't be counted towards GSSoC23.
