### ISSUE TITLE
Title is not properly align

### ISSUE THREAD

**Issue by Prajwal0225** [Bookingjini-Labs/bookingjini-icons#340]
### Is your feature request related to a problem? Please describe.

there is a lot of unnecessary gap between the logo and title they should be close to each other

![heading is not properly align](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/103810119/e153ec6e-94c8-48b0-9679-f2dd963f975e)

### Describe the solution you'd like

we have to minimize the gap 

please assign this issue to me under gssoc'23. I would like to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Prajwal0225 assigning this to you

**Comment by Prajwal0225** [comment]
Hey @AshutoshDash1999 , I am currently busy with my college work but I will do it within 3 to 4 days.
