### ISSUE TITLE
Improve the navbar:  page and navbar mixed

### ISSUE THREAD

**Issue by akanksha984** [Bookingjini-Labs/bookingjini-icons#341]
### Describe the bug

The navbar it not looking good and is mixed with the page.

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/97845909/8cf410d9-18eb-4f17-ae4c-9551be3d4caa)

### Expected behaviour

I would like to improve the navbar so that it looks good.
Please assign this issue to me under GSSOC'23 . I want to work on this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Neha5679** [comment]
I would like to work on it. Please assign me

**Comment by khadar1020** [comment]
please assign me this issue @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
The navbar has been updated.
