### ISSUE TITLE
Add background in the hero section

### ISSUE THREAD

**Issue by akanksha984** [Bookingjini-Labs/bookingjini-icons#342]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/97845909/76eaed11-ae9c-42ef-8482-581b3482cbd5)

### Describe the solution you'd like

The hero section has no background. I would like to add background to it so that it looks good.
Please assign it to me under gssoc'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
thanks for the suggestion but we don't need it for now.
