### ISSUE TITLE
Wrong display mode rendered during INITIAL loading.

### ISSUE THREAD

**Issue by decoder-hq** [Bookingjini-Labs/bookingjini-icons#343]
### Is your feature request related to a problem? Please describe.

When the website loads INITIALLY, the light mode is selected in the top right corner but the website is actually loaded in dark mode. 

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/83714476/5cd8d124-72d4-4a21-9330-245efd1d3365

### Describe the solution you'd like

Two possible solutions - 
1) Change the theme option that is selected initially.
2) Change the theme that is rendered initially.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
this issue is already covered
