### ISSUE TITLE
Font style and text-color

### ISSUE THREAD

**Issue by Neha5679** [Bookingjini-Labs/bookingjini-icons#345]
### Is your feature request related to a problem? Please describe.

If we will use better font and color then it looks better 

### Describe the solution you'd like

From google font i will choose a good font family and according to background i will choose the color of font and its alignment.

### Describe alternatives you've considered

Its looking very basic if we can add background images and according to that choose our font and icon color and adding hovering effect

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
what font you want to add?
