### ISSUE TITLE
<bug> the mode styling error

### ISSUE THREAD

**Issue by dheeraj1129** [Bookingjini-Labs/bookingjini-icons#346]
### Describe the bug

when clicking on the light mode button, it moves left then right 

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/72201773/0fb54370-b2aa-4b0c-ac85-3afa4adadc82

### Expected behaviour

The expected behavior when clicking on a light mode button would typically involve the button toggling the interface between light mode and dark mode.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Issue already covered.
