### ISSUE TITLE
New tab should open by clicking on socials

### ISSUE THREAD

**Issue by Surabhi1220** [Bookingjini-Labs/bookingjini-icons#347]
### Describe the bug

If someone clicks on the social media handles of the site a new tab should be opened if the user wants to see or use the site he has to go back and forth which is inconvenient for many.

### Expected behaviour

If the user clicks on socials a new tab will open containing the social media. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by neeraj2713** [comment]
I would like to work on this issue

**Comment by AshutoshDash1999** [comment]
@Surabhi1220 assigning this to you

**Comment by khadar1020** [comment]
please assign me this issue @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
@Surabhi1220 assigned this to you

**Comment by AshutoshDash1999** [comment]
@Surabhi1220 any update?
