### ISSUE TITLE
openAI GPT ChatBot

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [Bookingjini-Labs/bookingjini-icons#348]
### Describe the solution you'd like

Hello @AshutoshDash1999   ,
### Adding GPT v.3 {Chat Bot} 👍🏻
But you have to add your own API from Chat-GPT bcz API is a personal token and I'll also add a cloumn for that in the code so you just have to paste the API and it will run for you.
How to get GPT - API ?
You will get that API on the rapidAPI page.
Also I'll add a Step to get API while raising a PR 👍🏻

- Assign me this so I can start working 👍🏻 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

`lvl3 feature`

**Comment by AshutoshDash1999** [comment]
Why do we need ChatGPT plugin for icon pack website?

**Comment by SyedImtiyaz-1** [comment]
> Why do we need ChatGPT plugin for icon pack website?

Sure no problem but I was thinking something else.
