### ISSUE TITLE
Add new Icons

### ISSUE THREAD

**Issue by silky-modi22** [Bookingjini-Labs/bookingjini-icons#349]
### Is your feature request related to a problem? Please describe.

I want to add some more icons in the website 
- wishlist 
- traffic
- cloud 
- refresh (animated)
- shipping

### Describe the solution you'd like

I want to add some more new icons that are normally used.

### Additional context

I want to work on this issue please assign me under GSSOC 2023.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
We are not accepting any more icons.
