### ISSUE TITLE
Add a "Scroll to top" floating button 

### ISSUE THREAD

**Issue by harshitakaushik-dev** [Bookingjini-Labs/bookingjini-icons#35]
Missing scroll-to-top button.

Addition of the "scroll to top" button that would float in bottom-right corner would enhance the user experience of the website. 

I would love to work on this and request you to assign this issue to me as GSSoC 2023 Contributor

**Comment by bookingjini** [comment]
Thank you, @harshita-kaushik2, for your valuable contribution. Feel free to proceed with your code contributions. We kindly request that you adhere to the code standards and kindly provide a screenshot during the pull request.

**Comment by Saksham0205** [comment]
can you please assign me this issue under GSSoc 2023. I really want to work on this issue.

**Comment by bookingjini** [comment]
@harshita-kaushik There is a glitch on the dark mode page, the scroll-to-top button functions properly in light mode but does not appear in dark mode. Please take a look at the issue and fix it. The screenshot is enclosed for your reference.

![Screenshot 2023-05-25 153409](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/77221742/9807c03e-5147-4191-ab88-40f856381c20)

![Screenshot 2023-05-25 153439](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/77221742/1b923145-33e2-4fe1-bf6e-56ca6b231b80)

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.
