### ISSUE TITLE
Edit the footer section

### ISSUE THREAD

**Issue by PVBharadwaj** [Bookingjini-Labs/bookingjini-icons#352]
### Describe the bug

In the footer section social media icons are not visible due to WhatsApp icon. I would like to change it. 

### Expected behaviour

In the footer section social media icons are not visible due to WhatsApp icon. I would like to change it. 

### Screenshots

<img width="960" alt="image" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/117581755/92b22b35-9555-484e-ba58-5278b68343b7">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PVBharadwaj** [comment]
@AshutoshDash1999  please assign me this issue under Gssoc'23

**Comment by AshutoshDash1999** [comment]
@PVBharadwaj this repo is about bookingjini icons not bookingjini website
