### ISSUE TITLE
[Docs] Alignment and Styling improvement in README.md

### ISSUE THREAD

**Issue by jfmartinz** [Bookingjini-Labs/bookingjini-icons#355]
### Describe the bug

I would like to request an alignment adjustment for the `'How to use BookingJini Icons'` and `'How to Start Contributing'` sections in the README.md file. Currently, the README is centered, which makes it difficult to read and comprehend. 

I will also add  [Syntax Highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). To make it appealing to the contributors or users.

### Expected behaviour

By aligning these sections to the left, we can greatly enhance the user experience, as it will be easier for users to read the content from left to right. This alignment adjustment will contribute to a cleaner and more organized README.

why this is important?

1. Enhanced Readability: Aligning the sections to the left allows users to read the content naturally from left to right, following the standard reading pattern. This makes it easier for users to scan and understand the information, reducing cognitive load and improving overall readability.
2. Improved User Experience: Providing a clear and organized README promotes a positive user experience. By aligning the sections to the left, we create a visually pleasing and intuitive layout, making it more inviting for users to engage with the documentation.
3. Accessibility: Proper alignment plays a crucial role in ensuring accessibility for all users. Left alignment is a widely accepted standard that accommodates different reading preferences and assists users with visual impairments or screen readers.

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/129386460/165add30-843b-4ccc-826d-f238c08a74d2)
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/129386460/02099e77-8582-4502-bc9c-5fe3caaa511c)
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/129386460/96ddbb44-50a3-4f40-af1f-365a6380ecfb)

### Additional context

Assign this to me under GSSOC23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jfmartinz** [comment]
can you check @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
@jfmartinz assigned this to you
