### ISSUE TITLE
Redirction to home page in error404.html

### ISSUE THREAD

**Issue by rohanmittal1163** [Bookingjini-Labs/bookingjini-icons#356]
### Describe the bug

@bookingjini 
When clicking to back to home button it does not work in error404.html 

I can update this by redirecting it to the home page

pls assign this issue under GSSOC'23 

### Expected behaviour

when a user click on go back home button it redirect it to home page of website

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/97821844/1c01c660-8f74-48d7-a676-518fb027d637)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@rohanmittal1163 assigning this to you
