### ISSUE TITLE
website shows a dark theme but toggle button shows light theme

### ISSUE THREAD

**Issue by rohanmittal1163** [Bookingjini-Labs/bookingjini-icons#357]
### Describe the bug

when opens the website for the first time in browser it seem to have a default dark mode but the button is showing the website is in light mode

I can fix this issue pls allow me to work on this issue under GSSOC'23 as a contributor

### Expected behaviour

when open the website we can see the correct functioning of the theme toggling button

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/97821844/5f0e763e-3668-421e-8999-61fe6445f5cf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rohanmittal1163** [comment]
@AshutoshDash1999 How we can add new icons toyour github repo?? I have seen the Iconset.json file but how to add into cdn file. Could you pls help me in this. Really appreciates it. thank you

**Comment by AshutoshDash1999** [comment]
We are not adding new icons for now. Thank you

**Comment by rohanmittal1163** [comment]
@AshutoshDash1999
There is a bug in this github repo and has not been solved yet
Pls open this issue and assign to me so that i can work on it

**Comment by AshutoshDash1999** [comment]
> There is a bug in this GitHub repo and it has not been solved yet

Can you please explain it?

**Comment by rohanmittal1163** [comment]
@AshutoshDash1999 
when you open the website there is a dark theme enabled in the website but the theme toggle button is showing the sign of light theme. which is a controversial thing
