### ISSUE TITLE
NAVBAR need some padding

### ISSUE THREAD

**Issue by ayushlohmod** [Bookingjini-Labs/bookingjini-icons#358]
### Describe the bug

Navbar and the content need some padding and allignment 
please assign this to me

### Expected behaviour

The line and the text are not perfectly alline

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
apply padding only the x-axis so that all the content should be in the same line. make sure this is responsive too.

**Comment by udayasish** [comment]
Can I work on it?

**Comment by AshutoshDash1999** [comment]
ok @BANGBANG1999

**Comment by AnjaniChilumula123** [comment]
Can I work on this issue??

**Comment by udayasish** [comment]
I am not working on it right now @AnjaniChilumula123
