### ISSUE TITLE
favicon is not added in the title

### ISSUE THREAD

**Issue by vedanshiprajapati** [Bookingjini-Labs/bookingjini-icons#359]
### Describe the bug

as a decent website , i find it unusual to not have the favicon or it is done intentionally , i hope admins responds to this doubt of mine

### Expected behaviour

the website doesn't have a favicon or it's just my browser not loading it

### Screenshots

<img width="100" alt="Screenshot 2023-07-04 at 10 34 58 PM" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/99530989/b756e1a5-5e91-422b-96b6-42a856effcbd">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
favicon is added
