### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by zephyR00S** [Bookingjini-Labs/bookingjini-icons#36]
In the search bar we can implement a search icon and a search button instead of just showing search icon in the search bar.
![Screenshot (14)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/133316278/be1f44ba-ea52-49d5-9c5d-5b38b4cfb583)

we can also make a gradient back ground in some dark color schemes to make it look more good
we can also add the social links of the web site ( instagram , mail , etc ) in the end so that users can stay updated

**Comment by AshutoshDash1999** [comment]
hi @zephyR00S can you please share some mockups on the design part?

**Comment by An525ish** [comment]
I can customize the search bar like this and will adjust the colors accordingly with some glassmorphism...it will give a good user experience. Kindly assign it to me

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/93612051/5d47dd7d-6be6-46fb-b778-aae56e7a65ee

**Comment by zephyR00S** [comment]
> hi @zephyR00S can you please share some mockups on the design part?

We can make the search bar like the one in the attached picture or of other design and remove the placeholder - "search icon" in the website
![Screenshot (15)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/133316278/3a088994-33eb-45b9-b6f6-78d1b7717996)

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by AshutoshDash1999** [comment]
Issue Repeat of #25
