### ISSUE TITLE
Pagination for the icons 

### ISSUE THREAD

**Issue by I-shika** [Bookingjini-Labs/bookingjini-icons#366]
### Is your feature request related to a problem? Please describe.

As of now the user have have to scroll in large extent to see all the icons .

### Describe the solution you'd like

I would like to add pagination as it would be easier for user to slide the icons and all the icons of a page will be shown at a time otherwise the user have to scroll it in a large extent.

Please assign me this issue under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Icons are something that users will casually browse. If they are looking for something they should search. Therefore we don't need this for now.
