### ISSUE TITLE
Different colors are used which are not that much relevant .

### ISSUE THREAD

**Issue by Prachi-2001** [Bookingjini-Labs/bookingjini-icons#370]
I think we should improve the colors combination for the site. i found difference where button color when hovering are not matching with logo blue color which is more darker. so we can  improve button hovering color for fixing the color theme. 

another one we can change the link color to same the logo blue color which is same for button hovering so it would be more relevant color theme. Initial link color is pink. 

I will improve this small inconsistencies. Try to Assign this issue  to me @ramanujamgond 

Replace button hovering and link color to the dark blue color which is in the logo.
<img width="960" alt="image" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/92040884/51a54a83-cd30-4daa-a4f3-82300a3a7b0d">

**Comment by AshutoshDash1999** [comment]
@Prachi-2001 nice one...assigning this to you
