### ISSUE TITLE
Logo very small on mobile devices

### ISSUE THREAD

**Issue by sumitkr2000** [Bookingjini-Labs/bookingjini-icons#371]
### Describe the bug

Hey, the logo on the home page gets very small on less-width devices. Please assign me this issue. Thank you!

### Expected behaviour

Logo size should be big

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/100675296/1e828846-ff90-423c-9f3a-05ad5b990f05)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@sumitkr2000 assigning this to you
