### ISSUE TITLE
[FEATURE]: SFX AUDIOS FOR THEME SWITCH 🎵

### ISSUE THREAD

**Issue by 0xabdulkhaliq** [Bookingjini-Labs/bookingjini-icons#372]
### Is your feature request related to a problem? Please describe.

- This feature is related to accessibility, the audio will help the visually disabled people to know that the theme is updated by playing the audio whenever they clicked the theme switch

### Describe the solution you'd like

- The audio will be in two variations, one for on and one for off.
- The audio is lick a sound effect which will eventually helps the visually disabled people by playing it whenever the user hits the theme switch to change the theme.
- Besides the accessibility, this also helps to improve the User Experience of our Website.
- Here the audio is only played for lesser than one second as an sound effect, people will love to hear that.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xabdulkhaliq** [comment]
Hey there @AshutoshDash1999  👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by AshutoshDash1999** [comment]
@0xabdulkhalid we don't need this for now
