### ISSUE TITLE
Logo Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [Bookingjini-Labs/bookingjini-icons#373]
### Is your feature request related to a problem? Please describe.

No. It's an enhancement in the existing design.

### Describe the solution you'd like

By working on the styling of the logo, we can make it look more good. Currently logo is looking more like a heading.

### Describe alternatives you've considered

Improving the styling of the logo.

### Additional context

Current Design
![bookingjini (2)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/115794049/d7832d29-e912-40f1-b889-65e5dad58c7e)

Expected Updated Design
![bookingjini (1)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/115794049/1e05e261-c5ca-4948-b7e8-e5d69f3ac82c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
The current logo is the official logo of [Bookingjini](https://bookingjini.com/)
