### ISSUE TITLE
Not working any of icon...

### ISSUE THREAD

**Issue by Brijesh1963** [Bookingjini-Labs/bookingjini-icons#376]
### Describe the bug

On Mobile device,none of icon not functioning......

### Expected behaviour

![_20230708_180356](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/98037970/9087790a-2e1e-4b5d-8860-b3663d0d8742)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Brijesh1963 sorry can you explain more about the issue?
