### ISSUE TITLE
Need to be fixed the whole background with some soft Colours......

### ISSUE THREAD

**Issue by Brijesh1963** [Bookingjini-Labs/bookingjini-icons#377]
### Describe the bug

The background need to be some soft colour with latest Ui or Ux design.....

### Expected behaviour

![_20230708_180901](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/98037970/14845622-a005-4265-b9bc-e7af86ad989f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
which color code do you want to suggest?
