### ISSUE TITLE
Adding Contributor Workflow to Documentation

### ISSUE THREAD

**Issue by Jiggy9** [Bookingjini-Labs/bookingjini-icons#38]
Hey @bookingjini I am a contributor to GSSOC'23, an open-source project. I would like to add a section on 'How to start contributing' that includes all the major basic steps. This section will cover everything from forking the repository, opening it on a local device, creating a new branch, making modifications, merging it into the master branch, sending a pull request, till it revied and got merged.

I believe this section is crucial as it provides newcomers with a clear understanding of the contribution process. By following these steps, contributors can effectively participate in the project. Once I've added this section, you can review it and provide feedback on any missing or necessary information.

Could you please assign this issue to me? I'm excited to contribute and look forward to enhancing the documentation!

**Comment by AshutoshDash1999** [comment]
hi @Jiggy9 thanks for this issue, we really need this and want this ASAP. Please provide a contribution file with proper documentation. We are looking for ward to it.

**Comment by Jiggy9** [comment]
Hi @AshutoshDash1999  I sent PR  #39  regarding it. Please review it and let me know if there is something I can modify or merge it. Thank you.
