### ISSUE TITLE
Enabling lazy loading

### ISSUE THREAD

**Issue by marshadkhn** [Bookingjini-Labs/bookingjini-icons#380]
### Is your feature request related to a problem? Please describe.

**Hey @AshutoshDash1999** 
**I want to put a new feature to website that is enabling lazy loading to website**

### Describe the solution you'd like

**Lazy loading is the practice of delaying load or initialization of resources or objects until they're actually needed to improve performance and save system resources.**

**Advantage of lazy loading**
- Better data fetching
- Better user experience

**and many more**

### Describe alternatives you've considered

NONE

### Additional context

**Example**
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/80325579/d56cc5c3-8caa-47c2-95fb-6a2bd555cbb1)
**Showing a structure while the data is loading!**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Thanks for suggetion but we don't need it for now.
