### ISSUE TITLE
Bug in footer

### ISSUE THREAD

**Issue by marshadkhn** [Bookingjini-Labs/bookingjini-icons#382]
### Describe the bug

Hey @AshutoshDash1999 
While i was testing the website I found a `good-first-issue` that in the footer we do not have github icon for repo link

### Expected behaviour

In the side of linkedin icon we do have a github icon that provide us a link to navigate to the `Bookingjini` organization 

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/80325579/b0ea4d3a-fd91-4c90-b0c4-f0b01fece2c0)

### Additional context

NONE

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
We don't need it as almost all our projects are private and there is nothing that we want to be public.
