### ISSUE TITLE
New Page for Contributors

### ISSUE THREAD

**Issue by AlfiyaSiddique** [Bookingjini-Labs/bookingjini-icons#383]
### Is your feature request related to a problem? Please describe.

As this is an open-source project having a section dedicated to contributors is a common practice. I would like to add a page that contains the contributor's information in the card form.

### Describe the solution you'd like

We can do this in the following way:
I will add a link in the navbar to a page for contributors and on that page we will have a list of contributors who have contributed to this project. Later we can ask the contributors to add their names to the contribution page by themselves.

**Request** 

I am a gssoc23 contributor please assign me this issue under gssoc23 label.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
> Later we can ask the contributors to add their names to the contribution page by themselves.

Someone who hasn't contributed can also add their name, right?

**Comment by AlfiyaSiddique** [comment]
> > Later we can ask the contributors to add their names to the contribution page by themselves.
> 
> Someone who hasn't contributed can also add their name, right?

Technically, Yes. 
But when a user add his GitHub profile to the contributors data file or make any changes to this file then the PR reviewer  can check whether the user has contributed to atleast one issue in the project before adding his/her name in the contribution file!

**Comment by AshutoshDash1999** [comment]
> The PR reviewer can check whether the user has contributed to at least one issue in the project before adding his/her name in the contribution file

So it seems the reviewer will need to give some more time to maintain the contributor's page, which includes checking if the contributor has any merged PR from the commit tree. Also, keep in mind that the reviewer will also have to give time to review other issues and PRs and it's not being done full time by someone. So do you have any better idea so that the reviewer can save time while getting the same functionality in some other way?

**Comment by AlfiyaSiddique** [comment]
> > The PR reviewer can check whether the user has contributed to at least one issue in the project before adding his/her name in the contribution file
> 
> So it seems the reviewer will need to give some more time to maintain the contributor's page, which includes checking if the contributor has any merged PR from the commit tree. Also, keep in mind that the reviewer will also have to give time to review other issues and PRs and it's not being done full time by someone. So do you have any better idea so that the reviewer can save time while getting the same functionality in some other way?

How about using GitHub API for fetching the contributors list?

**Comment by AlfiyaSiddique** [comment]
We can use GitHub API to fetch the contributors list and display them on our page. In this way, the time is also saved and we don't need to store contributor's data as well.

**Comment by AshutoshDash1999** [comment]
That's what I was looking for. Explore the API and create a mock UI of how you can show the contributor's list.

**Comment by AlfiyaSiddique** [comment]
> That's what I was looking for. Explore the API and create a mock UI of how you can show the contributor's list.

Sure, I'll share the UI of the page before making a PR.👍🏻

**Comment by biplavmz** [comment]
Hii @AshutoshDash1999 I would like to work on this.
hii @AlfiyaSiddique If you are not working can i start working on this bug

**Comment by AlfiyaSiddique** [comment]
Hi @biplavmz 
I'm working on this issue
Please look for other issues or feel free to find and open new ones.

**Comment by biplavmz** [comment]
ok @AlfiyaSiddique

**Comment by AlfiyaSiddique** [comment]
Hello @AshutoshDash1999 

This is the UI of the contributor's page:


https://github.com/Bookingjini-Labs/bookingjini-icons/assets/86224794/4ad0d95a-e88b-4f68-a7fb-faeec5966d58



Some works are still remaining to complete like adding some padding, managing dark-light mode, and making the page responsive.

I would like to hear your feedback at this point in the page development.

If you want me to make any changes to the layout or design please let me know

**Comment by AshutoshDash1999** [comment]
- Name the button as Our Contributors
- You have to also change the colour based on light mode
- Please change the card color so that it looks like it is dark/light mode

**Comment by AlfiyaSiddique** [comment]
> - Name the button as Our Contributors
> - You have to also change the colour based on light mode
> - Please change the card color so that it looks like it is dark/light mode

Yes okay .
I have decided to make the card background color white in dark mode and black in light mode for good visuals purpose, is that okay?

Or do you want me to change it in any other color??

**Comment by AshutoshDash1999** [comment]
Please change the color appropriately... You can take references from other websites. Try fb in dark mode.

**Comment by AlfiyaSiddique** [comment]
How's this color combination for light/dark mode @AshutoshDash1999  ?


https://github.com/Bookingjini-Labs/bookingjini-icons/assets/86224794/1995f8c4-01e1-4eaf-be47-ef46dc8a5d24

**Comment by AshutoshDash1999** [comment]
Not too black...use soft black

**Comment by AlfiyaSiddique** [comment]
> Not too black...use soft black

How's this @AshutoshDash1999 ?

Previous
<img width="958" alt="prev" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/86224794/c07ee117-2818-4ad4-9398-815871de1c86">



New
<img width="958" alt="new" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/86224794/46f22582-3eca-4c11-a4c6-c11ed090299c">


If I make it more light black the the background color and card color will be similar.

**Comment by AshutoshDash1999** [comment]
Its good. Add very subtle shadow and make little bit of light greyish not whitish.

Add more padding.

**Comment by AlfiyaSiddique** [comment]
> Its good. Add very subtle shadow and make little bit of light greyish not whitish.
> 
> Add more padding.

Okay, Should I make PR  after these changes?

**Comment by AshutoshDash1999** [comment]
Ok
