### ISSUE TITLE
Wrong link added in navbar brands logo

### ISSUE THREAD

**Issue by sumitkr2000** [Bookingjini-Labs/bookingjini-icons#385]
### Describe the bug

Hey, @AshutoshDash1999 I can see that the link added in the navbar brand is not correct and needs to be corrected. Please assign me this issue. Thank you!

### Expected behaviour

The link should redirect to the home page.

### Screenshots

It is redirecting to this page.

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/100675296/f02e68b9-968b-4882-89cd-401ebf5cf440)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
> link added in the navbar brand is not correct

Why do you think it's wrong?

> The link should redirect to the home page.

We only have a single page!

**Comment by sumitkr2000** [comment]
You can check by clicking on the logo @AshutoshDash1999 

I have attached the screenshot where it is redirected

**Comment by AshutoshDash1999** [comment]
> You can check by clicking on the logo @AshutoshDash1999
> 
> I have attached the screenshot where it is redirected

It's correct. [Bookingjini](https://bookingjini.com/) is our official site. This repo is one of our product.

**Comment by sumitkr2000** [comment]
Ohh ok... sorry for misunderstanding
