### ISSUE TITLE
Add GitHub link in footer

### ISSUE THREAD

**Issue by blindaks** [Bookingjini-Labs/bookingjini-icons#386]
### Is your feature request related to a problem? Please describe.

I want to add a GitHub link in the footer section.
![Screenshot (36)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/128223364/e98772c9-63c6-489b-82ca-97d9dcd626cb)

### Describe the solution you'd like

I will add a link to Github account in the footer section.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Github link is already there on the navbar
