### ISSUE TITLE
[GSSoC'23] [Docs] Adding a small Licenses section to the readme and a MIT Licenses badge

### ISSUE THREAD

**Issue by 1Shubham7** [Bookingjini-Labs/bookingjini-icons#387]
### Is your feature request related to a problem? Please describe.

The readme doesn't have any info about Licenses, 

### Describe the solution you'd like

I can add a small Licenses section
and a MIT badge as well 
![afters](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/116020663/8747de3f-753c-46c8-a738-fc18ed09d61a)

### Additional context

Please assign me this issue under GSSoC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by AshutoshDash1999** [comment]
We don't need this for now.
