### ISSUE TITLE
Animated icons for Social media icons 

### ISSUE THREAD

**Issue by aasthad27** [Bookingjini-Labs/bookingjini-icons#389]
### Is your feature request related to a problem? Please describe.

Yes, it is related to a problem, it will enhance the User experience 

### Describe the solution you'd like

would like to make it more animated, it will enhance the UI 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@aasthad27 can you give some examples or references?

**Comment by aasthad27** [comment]
@AshutoshDash1999  Floating icons 

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/89932857/6f7477b2-7e77-4008-af00-8eac7d7b446f

**Comment by AshutoshDash1999** [comment]
Thanks for suggesting. We don't need this for now.
