### ISSUE TITLE
Background and fonts need to be fixed with enriching & attractive colors

### ISSUE THREAD

**Issue by Tanishashrivas** [Bookingjini-Labs/bookingjini-icons#390]
### Is your feature request related to a problem? Please describe.

There are certain detailing needed to make the website vibrant and easily accessible.

### Describe the solution you'd like

I can make the whole website look more attractive by enhancing the details of urls, buttons and navbar. Please assign this to me under GSSOC23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
We don't need this for now.
