### ISSUE TITLE
Changes to the light theme mode

### ISSUE THREAD

**Issue by liyashaji** [Bookingjini-Labs/bookingjini-icons#395]
### Describe the bug

When switched to light mode, the website becomes less readable. If the color and theme of the light mode is modified a little bit the issue can be resolved

### Expected behaviour

When viewing the website in light theme mode, it should be easier for the user to read the contents.By changing the color palette of the light mode, this can be achieved.

### Screenshots

![Screenshot 2023-07-18 at 09-57-54 Bookingjini Icons](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/95729024/9de2d568-afda-46b9-a490-bfe87b56edae)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
> By changing the color palette of the light mode, this can be achieved.

Which color palette you want to add?

**Comment by liyashaji** [comment]
> > By changing the color palette of the light mode, this can be achieved.
> 
> Which color palette you want to add?

I am thinking about going with darker color. This will help in making the website more readable. As we can see now the contents in light blue and grey make it less visible.

**Comment by AshutoshDash1999** [comment]
hmm okay, but I'm not sure about this. We don't need this for now.
