### ISSUE TITLE
Adding navbar with user sign-in

### ISSUE THREAD

**Issue by Tanusingh02** [Bookingjini-Labs/bookingjini-icons#40]
Adding navbar and also adding the sign in sign out option for user.

I want to contribute under gssoc'23

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by AshutoshDash1999** [comment]
We don't want to create any database for users as it is anyway open source and anybody can use it. So there's no point of adding sign-in option for this type of project.

Anyway thanks for checking out this repo. You are welcome to open any other issue. 😊
