### ISSUE TITLE
Changing the Night/Day button with attractive button  🔘

### ISSUE THREAD

**Issue by SaiyamTuteja** [Bookingjini-Labs/bookingjini-icons#403]
### Is your feature request related to a problem? Please describe.

I want to Change the button of day and night button with the new and attractive one with attractive one 
As i am the **GSSOC23** Contributor please assign me this issue 

### Describe the solution you'd like

I have a new button with the animation in the button 
Given Button snapshot will describe in better way -:
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/119167105/22e4adde-3c60-45aa-8c98-8c000241a413)
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/119167105/6dbd5f3b-0a53-448e-87a7-751296a612cc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
ok cool

**Comment by khadar1020** [comment]
can i raise the issue again and solve it as you have closed it @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
> can i raise the issue again and solve it as you have closed it @AshutoshDash1999

ok
