### ISSUE TITLE
[BUG]: IMPROPER TRANSITION EFFECT DURING HOVERING ICONS 🪲

### ISSUE THREAD

**Issue by 0xabdulkhaliq** [Bookingjini-Labs/bookingjini-icons#404]
### Describe the bug

- The bug is about the improper Transition effect that have been applied for the icons during the Hover state.
- The transition starts smoother but doesn't ends as the same.
- This bug needs to fixed as soon as possible, because it affect the UX of our Website.

### Expected behaviour

- The Transition want to be applied for both in and out states.

### Screenshots

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/92252895/ebd22a65-2920-4b69-81d4-025606a94c81

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xabdulkhaliq** [comment]
Hey there @AshutoshDash1999 👋🏻,

Please make sure to assign this issue to me as soon as possible so that i can proceed my progress regarding fixing this issue.

Thank you!

**Comment by akankshabach** [comment]
I want to solve this issue please assign me .
Thank you!
