### ISSUE TITLE
Bug in NAVBAR

### ISSUE THREAD

**Issue by marshadkhn** [Bookingjini-Labs/bookingjini-icons#408]
### Describe the bug

Hey @AshutoshDash1999 I found a bug in navabr 
The buttons are not aligned properly, they are not up and down each other

### Expected behaviour

The `Downlaod button` should be on top and then the all buttons

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/80325579/118a4b92-81d2-417f-8234-93f50112335f)

### Additional context

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marshadkhn** [comment]
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/80325579/72104623-9c2a-4ef9-be19-b4d71c6497bf)

**This also**

**Comment by AshutoshDash1999** [comment]
> ![image](https://user-images.githubusercontent.com/80325579/254871540-72104623-9c2a-4ef9-be19-b4d71c6497bf.png)
> 
> **This also**

How did you get this in the site?

**Comment by AshutoshDash1999** [comment]
> The buttons are not aligned properly, they are not up and down each other

The website is meant to be open in PC not in mobile.

**Comment by marshadkhn** [comment]
It's opened in pc not the mobile

**Comment by AshutoshDash1999** [comment]
how are you seeing this? Its okay in my end?

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/46455250/500f9366-67a0-4226-8a9a-5f7208ef1ada)

**Comment by marshadkhn** [comment]
Seems like it's my browser default
