### ISSUE TITLE
Add details about the significance of each symbol

### ISSUE THREAD

**Issue by aishwarya1735** [Bookingjini-Labs/bookingjini-icons#41]
Add about section and instructions on how to use the icons and their meanings on what is each symbol significance.
This gives more information for the users of choose their symbols.

**Comment by rafiya2003** [comment]
can I work on this?

**Comment by bookingjini** [comment]
> Add about section and instructions on how to use the icons and their meanings on what is each symbol significance. This gives more information for the users of choose their symbols.

Thank you, @aishwarya1735, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by aishwarya1735** [comment]
Okay sure. Thank you!

**Comment by KamalSritha-04** [comment]
Can you please assign me this issue under GSSOC'23

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.
