### ISSUE TITLE
Create a login and sign button missing

### ISSUE THREAD

**Issue by Vermasushant144** [Bookingjini-Labs/bookingjini-icons#418]
### Is your feature request related to a problem? Please describe.

![22 07 2023_00 15 20_REC](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/98468495/a6825aee-e67a-4bdb-8890-873ebd7b437b)
I see your website all goood but i things is missing is login and sign up button 

### Describe the solution you'd like

please assign this issue i can fix this issue 
solution is i create a login and sign page user interact 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vermasushant144** [comment]
@AshutoshDash1999 please assign this issue i want do work on the issue under Gssoc 23

**Comment by AshutoshDash1999** [comment]
We don't need this man... it's an icon pack. How many icon packs have you seen where you have to log in to access icons?
