### ISSUE TITLE
Website's Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [Bookingjini-Labs/bookingjini-icons#42]
The website's design is nice, but it can be improved by making some design adjustments. Working on the design of the website, I would like to make it even better.

**Comment by iamRabia-N** [comment]
I would like to work on this issue as a part of GSSOC-23.

**Comment by Saksham0205** [comment]
can you please assign me this issue under GSSoc 2023. I really want to work on this issue.
Problem which I noticed in the website is the "Light mode" I can make the light and dark mode graphic better.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by AshutoshDash1999** [comment]
@iamRabia-N can you please specify or share any mockup how you wanted it to improve?

**Comment by iamRabia-N** [comment]
Hello @AshutoshDash1999!
I will:
1. change the font-family of the text used in the website.
2. move logo more on left-side and other options on right side to make central space more clear.
3. make homepage clear with icons by moving icons little bit towards bottom and adding separate heading for them.
4. change the design of "light mode" button

**Comment by AshutoshDash1999** [comment]
@iamRabia-N can you please work only on the font-changing part? The rest of the changes are not in priority for us for now.

**Comment by iamRabia-N** [comment]
Sure. I would love to work on it.

**Comment by vk20july** [comment]
@AshutoshDash1999 sir can i do this task under gssoc'23

**Comment by AshutoshDash1999** [comment]
We are closing this issue for now as assignee took a lot of time and we don't need this anymore.

**Comment by iamRabia-N** [comment]
@AshutoshDash1999 this issue is completed. The related pull request is merged and is mentioned below:
Website's Updated Font #100

**Comment by AshutoshDash1999** [comment]
got it @iamRabia-N please always tag the issue number with the PR so that we can be in loop.
