### ISSUE TITLE
Issue: Found a bug for mobile users for top buttons during theme change

### ISSUE THREAD

**Issue by anshumanjaiswal** [Bookingjini-Labs/bookingjini-icons#420]
### Describe the bug

 Found that the download, star repo and our contributors are aligned as same during the theme change button is pressed for mobile users(responsive).

### Expected behaviour

It should be same for both the themes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
can you share a screenshot or video?

**Comment by anshumanjaiswal** [comment]
Looks like someone corrected it after I raised this bug @AshutoshDash1999 !
