### ISSUE TITLE
docs: workflow to assign PR to its author

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Bookingjini-Labs/bookingjini-icons#423]
### Is your feature request related to a problem? Please describe.

- The purpose of this workflow is to automatically assign the author of the pull request. It uses the provided GitHub token
(`secrets.GITHUB_TOKEN`) to perform this action.

### Describe the solution you'd like

- I will add this with proper conventions using GitHub Actions `.yml`
- It will remove the burden of the maintainers to some extent
- By using this workflow, the author of a pull request will be automatically assigned when the pull request is opened or reopened in the repository.

### Describe alternatives you've considered

> I will contribute this under GSSoC'23.

> Actually, I am amazed that you don't have workflows. It would really lessen your burden. 

### Additional context

> Working Output
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74038190/725aa215-6131-4cfb-a580-4e20f2be3434)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
We don't need this for now.
