### ISSUE TITLE
fix: issue form error

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Bookingjini-Labs/bookingjini-icons#424]
### Describe the bug

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74038190/ae0edcb7-0b30-42c0-bf2f-57fbc4b0a668)

> Under GSSoC'23.

I will further improve things as per standard conventions.

### Expected behaviour

> It will be shown while creating a new issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
assigning this to you
