### ISSUE TITLE
docs: improve all the issue forms

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Bookingjini-Labs/bookingjini-icons#425]
### Is your feature request related to a problem? Please describe.

These are the changes that I want to do in the issue forms:

1. Every Issue Form

- You can easily get information like whether the author of the issue:
   - is participating under GSSoC'23
   - read the contribution guidelines
   - have checked the existing issues

> After addition
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74038190/81e1d1bd-bf23-46ce-951b-960af6e37a36)

2. Bug Report

- We can have a dropdown to quickly get on which browser was the issue seen, it would be a optional field.

3. Remove unwanted fields in feature issue form

> Image
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74038190/f4a9d826-2cd5-4074-851b-a94c345484b2)

### Describe the solution you'd like

`I will improve all the forms with proper conventions`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Anmol-Baranwal assigning this to you. Please add a field to add screenshots or video while submitting a bug.
