### ISSUE TITLE
docs: update contributing guidelines

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Bookingjini-Labs/bookingjini-icons#426]
### Is your feature request related to a problem? Please describe.

There are no further guidelines that a contributor needs to take care of:

- It is always necessary that everything should be mentioned in the contributing guidelines, even conventional commit messages.

- I am not going to improve everything, but this is one area that you should definitely include if a new contributor comes.

- I will also include a statement to refer to the official GitHub flow in case they are not familiar with Git & GitHub.

### Describe the solution you'd like

> Image
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74038190/b25038b0-94ab-4846-8c6d-e8d8a6e7f19d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
Thanks for the suggestion but not needed for now.
