### ISSUE TITLE
feat: improve star button to show dynamic stats

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Bookingjini-Labs/bookingjini-icons#427]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74038190/724f022c-01e4-402a-849d-faf086398bd6)

### Describe the solution you'd like

- We can make it dynamic, showing the stats of the current repository.

- I will make sure to adjust it according to the theme.

### Describe alternatives you've considered

> What I did on LinksHub.
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74038190/39f351fa-7680-4f88-9915-3054764b7720)

I shared the image just to let you know that I will complete the issue with a proper understanding of the project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
@Anmol-Baranwal assigning this to you
