### ISSUE TITLE
feat: add a link to show author commit history

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Bookingjini-Labs/bookingjini-icons#428]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/74038190/78701e31-2f59-4a9b-89c1-bf8a2c9e1cdd)

> Author commit history of `AshutoshDash1999`
https://github.com/Bookingjini-Labs/bookingjini-icons/commits?author=AshutoshDash1999

### Describe the solution you'd like

- We can replace the long text of `View Profile` to `GitHub`
- We can add another button but it will make it very tough to read due to less space. (I can try)
- Or we can simple display two icons
- Or we can just add a link to `Contributions: <number>` with the appropriate link above the current CTA

Let me know what you think, and if you need some clarification.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
> * Or we can just add a link to `Contributions: <number>` with the appropriate link above the current CTA

do this
