### ISSUE TITLE
Modify Toggle Button

### ISSUE THREAD

**Issue by Raisa-12** [Bookingjini-Labs/bookingjini-icons#433]
### Is your feature request related to a problem? Please describe.

I will modify the existing toggle button and add new designs to it that will make it more attractive. Images are attached below.
![WhatsApp Image 2023-07-23 at 1 15 28 PM](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/87924606/14787459-80b9-4418-bc3b-b98a8bdefbfa)

### Describe the solution you'd like

The background will be added in the toggle button which will make it different from other ordinary toggle buttons.
![WhatsApp Image 2023-07-23 at 1 13 24 PM (1)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/87924606/94393d07-f222-4eaa-994b-b3e7c6130160)
![WhatsApp Image 2023-07-23 at 1 13 24 PM](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/87924606/d9196efb-26d7-44a8-8dba-a0fea12acdb2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshutoshDash1999** [comment]
the proposed design doesnt go well with the overall UI of website... you can try with some flat design though
