### ISSUE TITLE
[FEATURE] error page

### ISSUE THREAD

**Issue by khadar1020** [Bookingjini-Labs/bookingjini-icons#435]
### Description

in the error page, the go home button is showing the same styling even we are hovering on it and not hovering on it

### Describe the solution you'd like

we can add an hovering effect so that it looks attractive and box-shadow if necessarya

### Additional context

Before hover
![WhatsApp Image 2023-07-24 at 17 05 49](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/124120102/0bfb7e9f-219e-4e96-9429-da68abad5743)
After hover
![WhatsApp Image 2023-07-24 at 17 05 49](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/124120102/697cf3d8-9b9c-4a6d-86bc-4ea05d984e78)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by khadar1020** [comment]
please assign me this issue @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
Actually we don't need this page as it wont be opened to general user.
