### ISSUE TITLE
[FEATURE] contributor page

### ISSUE THREAD

**Issue by khadar1020** [Bookingjini-Labs/bookingjini-icons#436]
### Description

in the contributor page when we hover over the contributors image it is not showing any effect like it is not increasing its size and also no hovering effect on the contributor block 

### Describe the solution you'd like

i will add box shadow and when we hover on the image the image will increase its size

### Additional context

![WhatsApp Image 2023-07-24 at 17 18 02](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/124120102/9e113d8c-1784-48ad-9df2-6129cd90d0ee)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by khadar1020** [comment]
please assign me this issue @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
assigning this to you.

Also I had asked you to comment on #403 so that i can assign it to you
