### ISSUE TITLE
[BUG] <uneven navbar in dark and white mode>

### ISSUE THREAD

**Issue by Git21221** [Bookingjini-Labs/bookingjini-icons#439]
### Description

in some part of navbar i can see some margin and padding problem. 

### Expected behaviour

margin and padding should be same for all modes

### Screenshots/Video

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/101005577/531f6573-1490-4767-b874-e990c2e283f8)
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/101005577/e286b8c9-6316-420f-b09f-91b4d01401da)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
@Git21221 assigned it to u
