### ISSUE TITLE
Add the CodeQL workflow 

### ISSUE THREAD

**Issue by metabiswadeep** [Bookingjini-Labs/bookingjini-icons#444]
### Description

As a project with multiple users contributing to it, it is essential to ensure that no security vulnerabilities arise due to improper coding styles followed by contributors.

### Describe the solution you'd like

Add the codeql analysis workflow to be run on every push and pull request to prevent any security vulnerabilities in the codebase.

I would like to work on this as a part of GSSoC 23.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
We don't need this for now.
