### ISSUE TITLE
[BUG] Our contributions button overlapping with title in mobile view

### ISSUE THREAD

**Issue by PVBharadwaj** [Bookingjini-Labs/bookingjini-icons#445]
### Description

Our contributions button overlapping with title in mobile view

### Expected behaviour

Our contributions button overlapping with title in mobile view. I would like to fix it.

### Screenshots/Video

<img width="325" alt="image" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/117581755/98468488-7011-4cfe-af98-5af6441de8b9">

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
@PVBharadwaj assigned it to you
