### ISSUE TITLE
[FEATURE] logo transformation

### ISSUE THREAD

**Issue by khadar1020** [Bookingjini-Labs/bookingjini-icons#448]
### Description

when we hover on the image in footer of contribution and also the index page the image is not showing any transformation

### Describe the solution you'd like

i will add transformation so that its size increases 

### Describe alternatives you've considered

.

### Additional context

![WhatsApp Image 2023-07-27 at 22 07 14](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/124120102/7b5bf7fc-289a-4098-9e71-5ab98c34471e)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by khadar1020** [comment]
please assign me this issue @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
We don't need this for now.
