### ISSUE TITLE
[DOCS] adding Tech stack section and badges to the readme

### ISSUE THREAD

**Issue by 1Shubham7** [Bookingjini-Labs/bookingjini-icons#449]
### Description

We can add a tech-stack section in the readme to make it more professional and more visually appealing

Example -
![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/be1693e2-2172-4b6a-9237-810d7082600e)

### Screenshots

added above

### Additional information

Please assign me this issue under GSSoC'23

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by AshutoshDash1999** [comment]
The project is not that impressive with the tech stack, so we need this for now.
