### ISSUE TITLE
[FEATURE] Add GitHub logo in footer

### ISSUE THREAD

**Issue by blindaks** [Bookingjini-Labs/bookingjini-icons#450]
### Description

I want to add GitHub link in the footer section.

### Describe the solution you'd like

Adding link

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
we don't need this now.
