### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by amrit2611** [Bookingjini-Labs/bookingjini-icons#453]
### Description

This application is not dockerized and does not have a Dockerfile.

### Describe the solution you'd like

I will create a Dockerfile for this application, deploy the docker image on DockerHub and provide the deployment link in README.md

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
Why dockerization is needed for an icon's website?

**Comment by amrit2611** [comment]
> Why dockerization is needed for an icon's website?

I agree that it's not a necessity. But future collaborators who have knowledge of docker would benefit with the practise of using docker. And for those who don't, they can always continue in the regular way.

**Comment by AshutoshDash1999** [comment]
But you also have to consider the effort-to-output ratio. Making things overcomplicated will discourage beginners to contribute in this repo. Also for a simple site built on HTML, CSS and JS, its just adding cost in maintaining the server while not bringing anything useful will contribute increasing the negative cash flow, which as a organization is a big NO NO! Exploring tech is good but considering the economics is more important.
