### ISSUE TITLE
[FEATURE] want to add aeroplane svg

### ISSUE THREAD

**Issue by harshita-2003** [Bookingjini-Labs/bookingjini-icons#456]
### Description

want to add aeroplane svg

### Describe the solution you'd like

want to add aeroplane svg

![Screenshot 2023-07-31 020350](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/119532943/61eae2fd-7d6f-4de9-90c0-e8cf165fd15d)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
we are not adding more icons for now
