### ISSUE TITLE
[BUG] Buttons in navbar does not align properly on resize of window

### ISSUE THREAD

**Issue by ratishjain12** [Bookingjini-Labs/bookingjini-icons#457]
### Description

on resized the buttons are touching each other

### Expected behaviour

I want to fix the layout of buttons on resize

Please assign me this issue so I can fix this.

### Screenshots/Video

![Screenshot 2023-07-29 235014](https://github.com/agamjotsingh18/pollitup/assets/43003421/ed4bda97-5ba7-4cf7-9f92-bbabd41adb7d)
![Screenshot 2023-07-29 235101](https://github.com/agamjotsingh18/pollitup/assets/43003421/234ba9e8-fd23-47e1-a41e-16a1f98f2d69)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
this issue is active and already covered.
