### ISSUE TITLE
[DOCS] Adding a "Table on content" in the readme to make it easier to navigate

### ISSUE THREAD

**Issue by 1Shubham7** [Bookingjini-Labs/bookingjini-icons#458]
### Description

We must add a "Table of content" in the readme of the project to make it easier to navigate and more professional.

An example would be ->

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/116020663/5128f19d-30f0-4c61-accb-8656cdfbb841)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by AshutoshDash1999** [comment]
not needed for now
