### ISSUE TITLE
[DOCS] Update the Image of the README file of the new updated website

### ISSUE THREAD

**Issue by tanujbordikar** [Bookingjini-Labs/bookingjini-icons#459]
### `Under GSSOC'23`
I wanted to update the image in the README file with the image of the updated website image.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
We will do that after the GSSOC program
