### ISSUE TITLE
Want to add favicon to bookingjini site

### ISSUE THREAD

**Issue by LadityaGogoi** [Bookingjini-Labs/bookingjini-icons#46]
![3](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/108052802/4e28ba43-0fb2-401f-86cc-d66e9046b1bf)

### ISSUE :
**bookingini doesn't have any favicon on it's website**

### SOLUTION : 
![4](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/108052802/a9873d7a-797a-4fa2-a8dd-5c326e012d5f)
**I want to update the website by adding the above favicon**

Please assign this issue to me, under @GSSOC2023

**Comment by ayushnighoskar** [comment]
Hi,I have experience with the project's tech stack.I will try to make it as better as possible.Please assign this issue to me.It would be grateful for me to work on it.

**Comment by bookingjini** [comment]
> ![3](https://user-images.githubusercontent.com/108052802/239697797-4e28ba43-0fb2-401f-86cc-d66e9046b1bf.png)
> 
> ### ISSUE :
> **bookingini doesn't have any favicon on it's website**
> 
> ### SOLUTION :
> ![4](https://user-images.githubusercontent.com/108052802/239697869-a9873d7a-797a-4fa2-a8dd-5c326e012d5f.png) **I want to update the website by adding the above favicon**
> 
> Please assign this issue to me, under @GSSOC2023



> ![3](https://user-images.githubusercontent.com/108052802/239697797-4e28ba43-0fb2-401f-86cc-d66e9046b1bf.png)
> 
> ### ISSUE :
> **bookingini doesn't have any favicon on it's website**
> 
> ### SOLUTION :
> ![4](https://user-images.githubusercontent.com/108052802/239697869-a9873d7a-797a-4fa2-a8dd-5c326e012d5f.png) **I want to update the website by adding the above favicon**
> 
> Please assign this issue to me, under @GSSOC2023

Thank you, @Lobi29, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by bookingjini** [comment]
> ![3](https://user-images.githubusercontent.com/108052802/239697797-4e28ba43-0fb2-401f-86cc-d66e9046b1bf.png)
> 
> ### ISSUE :
> **bookingini doesn't have any favicon on it's website**
> 
> ### SOLUTION :
> ![4](https://user-images.githubusercontent.com/108052802/239697869-a9873d7a-797a-4fa2-a8dd-5c326e012d5f.png) **I want to update the website by adding the above favicon**
> 
> Please assign this issue to me, under @GSSOC2023

Thank you, @Lobi29, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.
