### ISSUE TITLE
[FEATURE] the night and dark mode button

### ISSUE THREAD

**Issue by khadar1020** [Bookingjini-Labs/bookingjini-icons#460]
### Description

I want to Change the button of day and night button with the new and attractive one with attractive one

### Describe the solution you'd like

I have a new button with the animation in the button
Given Button snapshot will describe in better way -:
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/124120102/812fdc8c-e579-4554-89b1-9231e1237147)
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/124120102/5fa0b900-6b10-42c2-bcb6-5bc1ad5e9676)

### Describe alternatives you've considered

.

### Additional context

.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by khadar1020** [comment]
i have raised an issue as you have told me in issue: #403 please assign me this issue @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
@khadar1020 any update on this?

**Comment by khadar1020** [comment]
I will update the pr tomorrow night @AshutoshDash1999
