### ISSUE TITLE
[BUG] Non Sticky Navbar

### ISSUE THREAD

**Issue by parasss19** [Bookingjini-Labs/bookingjini-icons#463]
### Description

- Right now the navbar is not sticky to its position
- Its move up upon scrolling
- And as a user its very time consuming for me to every time go back to top and download the icons

### Expected behaviour

- The navbar should stick to its position so that it very helpful for user to navigate easily on your website

### Screenshots/Video

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/101205226/19244628-6406-4f3c-b13c-5fca7d4eb675

### Additional context

Hey @AshutoshDash1999 
- I will redesign the navbar with position stick to top
- Also i will  made transparent navbar with background blur effect giving it glass morphism effect

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
@parasss19 ok
