### ISSUE TITLE
[FEATURE] Add link of home page in navbar brand

### ISSUE THREAD

**Issue by sumitkr2000** [Bookingjini-Labs/bookingjini-icons#464]
### Description

Hey, I had a really bad experience when I was on the contributor page and I was not able to go to the home page. I want to add a link to the home page in the text "bookingini icons" of the navbar brand. Please assign me this issue. Thank you!

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/100675296/fd0a2581-e50a-4ebb-a0d9-795665a9edf4)

### Describe the solution you'd like

Add link to the home page to the text of navbar brand

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
@sumitkr2000 ok
