### ISSUE TITLE
[BUG] responsiveness breach

### ISSUE THREAD

**Issue by ManashAnand** [Bookingjini-Labs/bookingjini-icons#465]
### Description

The webapp is not responsive 
On mobile and tablet view many icons and text hide

I will provide screenshot to prove my points.

### Expected behaviour

The webapp should be respnsive 
to maintain the decoram of the UI/UX
and for the ease of users

### Screenshots/Video

On tablet view
![i2](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/91553087/2e3a41b8-c471-4a6d-babc-1e3be20857df)
on mobile view
![i1](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/91553087/56b69194-831e-4da9-a8d1-15f1734393e4)

### Additional context

Please assign me this issue and labeled it as GSSOC 23

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
ok @ManashAnand

**Comment by AshutoshDash1999** [comment]
@ManashAnand any update?
