### ISSUE TITLE
[BUG] Footer doesn't follow the website theme in dark mode

### ISSUE THREAD

**Issue by vipulpandey7860** [Bookingjini-Labs/bookingjini-icons#468]
### Description

the footer doesn't follow the website's main color theme when in dark mode.

### Expected behaviour

it should follow website color theme in both light and dark mode.

### Screenshots/Video

![footer bug](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/53248489/6231e896-a3a0-4306-9820-db4186e76429)

### What browser are you seeing the problem on?

Brave

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
Its fine now...don't need to change
