### ISSUE TITLE
Critical SEO Tag Implementation Issues: missing tags which effect Search Engine Visibility and Performance

### ISSUE THREAD

**Issue by Mrprayag077** [Bookingjini-Labs/bookingjini-icons#470]
### Description 

SEO tags play a crucial role in optimizing web pages for search engines and improving their visibility in Google rankings. However, some pages in the application are currently lacking essential SEO tags, which can hinder their performance in search engine results pages (SERPs).

**examples-
Lack of Metadata
Missing Alt Attributes
Lack of Structured Data (Schema.org markup)
XML Sitemap many more**

### Expected behaviour

<meta name="robots" content="index, follow">
<meta name="google-site-verification" content="your_verification_code">
<meta name="csrf-token" content="your_csrf_token">
<meta name="msvalidate.01" content="your_verification_code">

### Screenshots/Video

![Screenshot (1487)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/99162236/41c9323d-cf04-42ab-b845-0d076df6bdd7)

### Benefits:

**Improved Search Engine Visibility:** Including SEO tags ensures that search engines can effectively crawl and index our web pages, leading to better visibility in search results.

**Higher Click-Through Rates (CTR):** Well-optimized meta titles and descriptions can attract users' attention in search results, increasing the likelihood of them clicking on our pages.

**Enhanced User Experience:** SEO tags, such as heading tags, help structure the content on our pages, making it more organized and user-friendly. This improves the overall user experience and encourages visitors to spend more time on our site.

**Targeted Keyword Optimization:** By strategically incorporating relevant keywords in our SEO tags, we can align our content with user search intent and improve our rankings for specific queries.

**To enhance the SEO performance and indexing of our pages, it is essential to implement these missing SEO tags across the application. This will help us rank higher in Google search results, attract more organic traffic, and ultimately improve the overall success of our website.**

### How can we reproduce this bug?

go in the index.html see in the head section the main tags are missing which are required for boosting the SEO, indexing, ranking in browser

**examples-
Lack of Metadata
Missing Alt Attributes
Lack of Structured Data (Schema.org markup)
XML Sitemap many more**

High priority

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

@AshutoshDash1999 plz assign me this task under GSSOC-23

**Comment by AshutoshDash1999** [comment]
we dont need it for now
