### ISSUE TITLE
Redesigning the 404 Page for Improved User Experience, current page UI lags

### ISSUE THREAD

**Issue by Mrprayag077** [Bookingjini-Labs/bookingjini-icons#471]
### Describe the bug:
There is no current 404 page on the website, resulting in a poor user experience. When users encounter a 404 error, they are presented with a visually inconsistent and potentially confusing page that does not align with the website's branding. This inconsistency can lead to frustration and a negative perception of the website.

### Expected behaviour

The expected behavior is to upgrade the 404 page to align with the overall theme and design of other pages on the website. The upgraded 404 page should reflect the branding and visual style of the website, providing a consistent user experience. It should display a clear and informative message indicating that the requested page could not be found, along with relevant suggestions or links to help users navigate to other parts of the website.

### Screenshots/Video

![Screenshot (1488)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/99162236/a461e82a-645a-45ec-b1ca-07701db89017)

### Benefits:

Enhanced user experience: A well-designed and visually consistent 404 page improves user experience by maintaining the overall look and feel of the website. Users will feel more confident and reassured, even when encountering errors or broken links.

Brand consistency: The upgraded 404 page ensures brand consistency throughout the website, reinforcing the website's identity and creating a cohesive experience for users.

Increased user engagement: By providing helpful suggestions or links on the 404 page, users are encouraged to explore other parts of the website, reducing bounce rates and increasing overall user engagement.

Positive perception: A visually appealing and user-friendly 404 page leaves a positive impression on users, showcasing the website's attention to detail and commitment to providing a seamless browsing experience.

Error recovery: The upgraded 404 page can help users recover from the error more easily by providing alternative options or guiding them to relevant content. This reduces frustration and improves the chances of users staying on the website.

Professionalism: A well-designed 404 page demonstrates professionalism and attention to user needs, instilling trust and credibility in the website and its content.

plz assign this task under the GSSOC-23 program

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
The website is built on html, css. We don't have routing. So we don't need it for now.
