### ISSUE TITLE
[FEATURE] <write a small description here>

### ISSUE THREAD

**Issue by Kashish-29** [Bookingjini-Labs/bookingjini-icons#473]
### Description

Add Padding and different modes to your Figma file

### Describe the solution you'd like

I would like to add different  modes and make it responsive

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
we don;t need it for now
