### ISSUE TITLE
[DOCS] Update Readme

### ISSUE THREAD

**Issue by Parul1606** [Bookingjini-Labs/bookingjini-icons#474]
### Description

Current State:
The Contributing section of the README file requires extra documentation. Some commands that should be applied while contributing to the project are missing.

Desired State:
I know some small basic steps don't require to be explained. But, I would like to add those extra commands like a repository should be pulled by creating a remote repository(for reference), the first step like creating a folder at your desired location, etc. I have divided the whole process into 17-18 simple steps which will be easy to understand by the contributors. I won't be deleting any part will just modify it in a better way. I have the desired image of how it will look after updating the README.
The image attached is just an outlook of how README will be displayed:

### Screenshots

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/80768852/ea7bffbf-e6fa-47b8-8d6e-5f10c45dd0b7)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Parul1606** [comment]
Please assign me this issue, I would like to work on it under gssoc @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
These are already added in the readme. Nothing more to add for now.

> I have divided the whole process into 17-18 simple steps

don't you think 17-18 steps will be too long to follow?

**Comment by Parul1606** [comment]
> These are already added in the readme. Nothing more to add for now.
> 
> > I have divided the whole process into 17-18 simple steps
> 
> don't you think 17-18 steps will be too long to follow?

But 2 commands are necessary to follow add remote reference to project, and fetching upstream main @AshutoshDash1999
