### ISSUE TITLE
[FEATURE] <Dark mode Enhancement>

### ISSUE THREAD

**Issue by Manishak798** [Bookingjini-Labs/bookingjini-icons#475]
### Description

The default setting of the website is set to dark mode, but when a user switch to light mode and reloads the webpage or clicks on any button the light mode instantly gets disabled which does not look appealing as a visitor.
I am willing to work on this bug and want to enhance the UX experience using JavaScript.
Please assign this to me under GSSOC23.

### Describe the solution you'd like

When a user switch to light mode the theme must remain the same until the user is there but it does not happen in this case, so I want to improve this feature of switching between dark mode. 

### Describe alternatives you've considered

I want to work on this storage feature with the help of JavaScript that theme remains the same until the user's session expires.

### Additional context

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/90680330/2afaac71-b1a5-4c96-8dff-0faad9ca5b4f)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
@Manishak798  assigned to you

> until the user's session expires.

use localStorage instead

**Comment by Manishak798** [comment]
I will use local storage and update you soon with my work.
Thank you for assigning this to me. @AshutoshDash1999

**Comment by Manishak798** [comment]
Hey, @AshutoshDash1999 Kindly check my PR and let me know your views on the same.
