### ISSUE TITLE
[FEATURE]  Want to add our Contributor page in the website

### ISSUE THREAD

**Issue by HimanshuNarware** [Bookingjini-Labs/bookingjini-icons#476]
### Description

Details
Is your feature request related to a problem? Please describe.
Our Contributors page in the website

### Describe the solution you'd like

Describe the solution you'd like
We can add a Contributors page in the website. which is shows the name and the profile image of the contributor.and the number of commits is done by the contributor

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by AshutoshDash1999** [comment]
its already there
