### ISSUE TITLE
Adding a contact us button in the navbar

### ISSUE THREAD

**Issue by Krishi1211** [Bookingjini-Labs/bookingjini-icons#48]
**Please describe the problem**
Why do you want to add this feature?
It would be quiet easy to report and give feedback to the owner about the website and icons.

**Describe the solution you'd like**
It would contain several social media icons like insta,facebook,linkedin,twitter,github etc with images.

**Screenshot**
Please attach any relevant screenshot(s).
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/97182407/0895f383-8b45-47bd-9ab8-b2cefa0ee8dc)

**Comment by rafiya2003** [comment]
can you please assign me this work?

**Comment by bookingjini** [comment]
> Krishi1211

Thank you, @Krishi1211, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by Krishi1211** [comment]
> > Krishi1211
> 
> Thank you, @Krishi1211, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

can you share some of your social media handles So that i can add it

**Comment by AshutoshDash1999** [comment]
@Krishi1211 you can get all the handles from our website: https://www.bookingjini.com/

**Comment by mandliyarajendra11** [comment]
@AshutoshDash1999 issue is still open 
i want to work on this issuee

**Comment by AshutoshDash1999** [comment]
this is already added to website
