### ISSUE TITLE
Four spelling mistakes of the icons 

### ISSUE THREAD

**Issue by Avilash-Saha** [Bookingjini-Labs/bookingjini-icons#49]
**Please describe the problem**
There are 3 spelling mistakes. "Bath-Robe" is spelled as "Bath-Rob", "Door-Close" is spelled as "Dor-Close", "Flower-Vase" is spelled as "Flower-Bas", "Hygiene" is spelled as "Hygine".

**Describe the solution you'd like**
I would like to correct the spelling mistakes

**Screenshot**
![bathrobe](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/85384757/e5439e4e-87d7-4a59-bdef-b0f6a4ba4e14)
![doorclose](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/85384757/536630b1-327c-4b9c-aa8f-17f6b3c084de)
![flowervase](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/85384757/2fc32370-e06a-4f4c-a889-22dc330a6136)
![hygiene](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/85384757/85edc898-8439-4785-9c42-d42bb173e828)

**Comment by Avilash-Saha** [comment]
I am a GSSoC'23 contributor. Can you please assign me this task?

**Comment by kasturimandlik** [comment]
I would like to work on this under GSSOC'23. please assign me this issue.

**Comment by op-amateur** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by Avilash-Saha** [comment]
I have fixed this issue. I have written about this in detail at issue #34 .
