### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by Anshkaran7** [Bookingjini-Labs/bookingjini-icons#50]
Please describe the problem
The spelling of "Calendar" is shown as "Callender

Describe the solution you'd like
I would like to change it to the correct spelling.

**Screenshot**
Please attach any relevant screenshot(s).
![Screenshot 2023-05-21 015332](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/106963118/7f25e504-b7be-469e-b759-0ceb9a0f61eb)

**Comment by AishwaryVishwa** [comment]
As a gssoc'23 contributor I would like to work on this issue please assign it to me.

**Comment by Avilash-Saha** [comment]
I have fixed this issue. I have written about this in detail at issue #34 .
