### ISSUE TITLE
Bug: Light mode button says "Light Mode" even when in light mode

### ISSUE THREAD

**Issue by rayyan016** [Bookingjini-Labs/bookingjini-icons#53]
**Please describe the problem**
The page, when in light mode, says "Light mode" on the button. This is a bug.

**Describe the solution you'd like**
I would like to fix this bug under GsSOC'23. Please assign me this issue. Thankyou.

**Screenshot**
Please attach any relevant screenshot(s).
![jini1](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/102043379/ed751d6a-5c38-4b82-85bc-843678913432)

**Comment by bookingjini** [comment]
> **Please describe the problem** The page, when in light mode, says "Light mode" on the button. This is a bug.
> 
> **Describe the solution you'd like** I would like to fix this bug under GsSOC'23. Please assign me this issue. Thankyou.
> 
> **Screenshot** Please attach any relevant screenshot(s). ![jini1](https://user-images.githubusercontent.com/102043379/239719842-ed751d6a-5c38-4b82-85bc-843678913432.png)

Thank you, @rayyan016, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.
