### ISSUE TITLE
Padding issue fixed

### ISSUE THREAD

**Issue by piyushkhurana2019** [Bookingjini-Labs/bookingjini-icons#55]
**Please describe the problem**
When we see the website in the mobile view, the objects appears to be sticked to the left and leaving a blank gap in the right side like this

<img width="1440" alt="Screenshot 2023-05-21 at 11 25 11 AM" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/96003210/1739dbd6-81a5-4e99-b386-0e0d6a42fc95">

**Describe the solution you'd like**
i have fixed the padding issue now all items are aligned to the centre

<img width="1440" alt="Screenshot 2023-05-21 at 11 24 58 AM" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/96003210/17740f76-a364-45ff-af2f-1f53a08f0930">

**Comment by op-amateur** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by khushi767** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by bookingjini** [comment]
> **Please describe the problem** When we see the website in the mobile view, the objects appears to be sticked to the left and leaving a blank gap in the right side like this
> 
> <img alt="Screenshot 2023-05-21 at 11 25 11 AM" width="1440" src="https://user-images.githubusercontent.com/96003210/239723029-1739dbd6-81a5-4e99-b386-0e0d6a42fc95.png">
> **Describe the solution you'd like** i have fixed the padding issue now all items are aligned to the centre
> 
> <img alt="Screenshot 2023-05-21 at 11 24 58 AM" width="1440" src="https://user-images.githubusercontent.com/96003210/239723019-17740f76-a364-45ff-af2f-1f53a08f0930.png">

Thank you, @piyushkhurana2019, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.
