### ISSUE TITLE
create a social media navbar

### ISSUE THREAD

**Issue by KhushiKhandelwal610** [Bookingjini-Labs/bookingjini-icons#56]
I want to add a social media navbar . Please assign it to me under GSSOC'23.

**Comment by op-amateur** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by khushi767** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by bookingjini** [comment]
> KhushiKhandelwal610

Thank you, @KhushiKhandelwal610, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by vk20july** [comment]
@bookingjini sir can i do this task under gssoc'23
