### ISSUE TITLE
Creating mockups/assets for the landing page

### ISSUE THREAD

**Issue by sanya031** [Bookingjini-Labs/bookingjini-icons#58]
The website could use some phone mockups which display screens where the icons are being used. We can highlight them and write some captivating texts which can make the user use these icons.  

These mockups can be used for the hero section of the landing page to enhance it and will result in a better design of the website. 

Please assign me this issue so i can improve the landing page with better pictures/assets. 

sanya
ggsoc 23 contributor

**Comment by sanya031** [comment]
The UI of the website seems a bit simple and can be done nicely with custom illustrations/mockups with which i can help. I can 
create the design of the landing page.  (provide a figma file to the developers)

@AshutoshDash1999 Please assign me the issue so i can help create a better landing page. Thankyou

**Comment by AshutoshDash1999** [comment]
@sanya031 sorry for the late reply. Do you want to contribute in design only? or code it too?

**Comment by sanya031** [comment]
I would like to contribute to design only if it's okay. But I sure can and have collaborated on projects with developers and can help in the process with some knowledge I have on development. 

But mainly I would like to re-design the ui for the landing page and add custom mockups as mentioned before. 
Thankyou

**Comment by AshutoshDash1999** [comment]
ok then please focus on the design then, we will create a new issue for the UI part then. Would love to see your magic. 😊

**Comment by sanya031** [comment]
Is there a deadline i should keep in mind ? My end-sem exams finish on 29th june so I should be able to handover the designs by 5th july or sooner. 

Thankyou for assigning me !

**Comment by sanya031** [comment]
@AshutoshDash1999 Can you please share the icon set svg file so I can use them in the designs? Thanks

**Comment by AshutoshDash1999** [comment]
There is no deadline for now. But please keep us updated every 2-3 days after your exam so that we can be in sync.

Icon set file: 
https://www.figma.com/file/NJ3P5hqp1qKSKF6E8lMTnN/Icons?type=design&node-id=0%3A1&t=DmnV81b7NsXGSGlX-1

**Comment by sanya031** [comment]
Hi I have started my work. 
Starting by Categorizing the icons so that people can view different groups of icons by category instead of the only option of viewing them all at once.

**Comment by AshutoshDash1999** [comment]
@sanya031 please share the design of what you will be working on before finalizing.

**Comment by sanya031** [comment]
Should i just draw a sketch and share, you can tell me what i should edit ? I also wanted to ask if i can create multiple pages ? or do you want a single page website

**Comment by AshutoshDash1999** [comment]
How about you create a different page with categories? the main page will have all the icons.

**Comment by sanya031** [comment]
Let me share a sketch of the page that i am thinking and then you can help me finalize it. It will be much easier than to type out my design

**Comment by AshutoshDash1999** [comment]
sure, please go ahead

**Comment by sanya031** [comment]
@AshutoshDash1999 
This is very rough sketch but there are different sections to the landing page :

**Section 1- Navbar** 
Navlinks- logo, icon for dark and light mode, designer, developer, get cdn 

**Section 2- hero section**
Download 300+ icons.....
headline
cta button 
with illustration

**Section 3- designer and developer path**
2 cards
card1- designer (talks about the figma plugin and steps to run it)
card2- developer( shows the categories and steps to use listed icons)

**Section 4- categories**
small section to showcase different categories

**section 5- text** 
last headline and cta button that will take you to categories (developer page)

**section 6 - footer (optional)**
let me know what you want to write in this section. Else we can delete it. 

Please let me know if you want any changes 

![landing page 1](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/7a1250ad-a391-41d8-9b76-0c4e889b19fb)
![landing page 2](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/f9f3fecd-462f-4953-8db5-7ecd37efb927)
![designer-developer page](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/19419f60-4a5c-43dc-94c5-7b4d03645657)

**Comment by AshutoshDash1999** [comment]
Everything is good except in **section 4**, i am think of adding all icons. section 5 will not be needed. for footer just add about bookingjini and social icons

**Comment by sanya031** [comment]
The developer page has one category named 'all' (see 3rd picture) which will have all the icons. I don't think it makes sense to show all icons on the landing page. But if you want it that way i can do so. 

I will start designing and inform you as i complete each section.

**Comment by AshutoshDash1999** [comment]
well... let's not go with the category part and show all icons in 1 place.

**Comment by sanya031** [comment]
sure !

**Comment by AshutoshDash1999** [comment]
hey @sanya031, our team has decided to add categories. And they really liked your idea. Only thing is that we will mention the categories and what icons to include in them. Please go forward with your idea. I am really sorry for bothering you. 😅

**Comment by sanya031** [comment]
Oh it’s totally fine. Can you just add the category names in the same figma file that had all the icons and group the icons according to category.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AshutoshDash1999** [comment]
@sanya031 please continue with the rest of the page. We are brainstorming on the category names and what icons to add on. Ping me once you start working on that particular section.

**Comment by AshutoshDash1999** [comment]
@sanya031 any update on this?

**Comment by sanya031** [comment]
Hi @AshutoshDash1999 To view the prototype on your screen click on Opions>Fit Width. Its on top left corner 

here is the link to the prototype : [prototype](https://www.figma.com/proto/XwQqLhjYKxub4uv1qjHgd4/bookingjini-website?type=design&node-id=1-1198&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=10%3A56)

here is the link to the figma file : [figma file ](https://www.figma.com/file/XwQqLhjYKxub4uv1qjHgd4/bookingjini-website?type=design&node-id=0-1&t=Nzt63SNBiXYgneFG-0)

Please let me know if there are any changes you want me to do

**Comment by sanya031** [comment]
Please check the hover on the last icon only

I have not made any categories as you said you'll be categorizing the icons and sharing it with me. I have made only one category just to show you how it will look. 

I was hoping you could let me know in what format you'll be providing the icons. 



![Desktop - 3 (1)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/3ca7ee3b-6610-4833-ba29-191f63f44ad8)

**Comment by AshutoshDash1999** [comment]
@sanya031 this is a very good work

Some suggestions though:
- add some border radius here:
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/46455250/e29526e2-6a44-4efd-a632-6de0de397cad)
- remove the border and add some shadow and reduce the text size
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/46455250/9758b103-e10b-4bd4-8bbe-26f6cae013b5)
- here is the official bookingjini icon for your reference
![Bookingjini](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/46455250/fbeb83a4-3ae0-4168-bebc-9b355e05fd44)

**Comment by AshutoshDash1999** [comment]
> I was hoping you could let me know in what format you'll be providing the icons.

For now, it has click to copy like `<i class="jini-Arrow-1"></i>` . We want to add more options for downloading the icons in various format or customise it. Do you want to work on it?

**Comment by sanya031** [comment]
Yeah I'd love to design that. 

The svg list you had shared with me (figma file) has less number of icon than the ones on the original website. I used a figma plugin to get the website in figma editable format. 

So when you do send the correct and all icons by caregory can you please send the figma file in this format for the icons. It will be a lot easier for me 
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/55c5f7e5-eab2-4998-a7a1-1127e904db50)

**Comment by sanya031** [comment]
I also wanted to request if you could increase the level number on this issue. Since it is a lot of work. It's ok if you can't and thanks for considering.

**Comment by sanya031** [comment]
I also wanted to request if you could increase the level number on this issue. Since it is a lot of work. It's ok if you can't and thanks for considering. 

@AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
> The svg list you had shared with me (figma file) has less number of icons than the ones on the original website.

Can you recheck, we have 290 icons in website and 300 icons in figma file.

> can you please send the figma file in this format for the icons

Do you need the file with the name and icon?

Our team decided that you can give the category names by yourself. Feel free to do that. Also, you have write access to the Figma file that I shared earlier.

**Comment by sanya031** [comment]
> Do you need the file with the name and icon?

Yes that would be great. icon and name just like on the website.

**Comment by sanya031** [comment]
> Some suggestions though:

I have made the changes.

**Comment by AshutoshDash1999** [comment]
> So when you do send the correct and all icons by caregory can you please send the figma file in this format for the icons. It will be a lot easier for me

Sorry, we don't have that now....but you can get the json file from the website directory. There we have added the icons with their names.

**Comment by sanya031** [comment]
hey @AshutoshDash1999. I just wanted to show that these are the categories i am working with. 
![category-14](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/4b3b3f1f-a2fe-4449-9799-2bcd540e8c78)
![category-13](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/b5be61e7-51e9-4b23-8f03-a4559ed2503d)
![category-12](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/cc6692d6-04c8-4ef7-a772-b62a9e3ce0a4)
![category-11](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/e7867fcf-b139-4e22-b568-7fe155241b37)
![category-10](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/aaa8b156-cbe9-457d-83d4-c91505ff9a5a)
![category-9](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/759316f9-5e83-40eb-a5a4-2b8c1a65acee)
![category-8](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/d8b4c63d-d656-4908-b945-d9d8fbdd9fe4)
![category 7](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/db792d47-3e20-4610-ae51-915a1dfe3e69)
![category-6](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/efb42f68-eb70-40b9-8bd2-a45d6c1d29e2)
![category-5](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/24c4a9e6-6164-46c3-b7bb-a8bb6a733f0c)
![category-4](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/80f536e3-80ce-4ae3-8dc5-4e1cfe0962a0)
![category-3](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/aa4f2895-9c8c-4545-a4b9-59194d4fd18a)
![category-2](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/a487aacc-b374-42a5-b3f5-65e2d91b98b1)
![category-1](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/598af3a1-0cd3-44c3-9ce8-9981b841a072)

**Comment by AshutoshDash1999** [comment]
Cool

**Comment by sanya031** [comment]
hey @AshutoshDash1999 I have designed the page according to the new category designs. 
I have done the navigation for the prototype for the first 4 categories. And the first icon of all those categories have hover effect. 

[Prototype link](https://www.figma.com/file/XwQqLhjYKxub4uv1qjHgd4/bookingjini-website?type=design&node-id=17%3A101&t=jciFgQNVSOYhKJaY-1)

**Comment by AshutoshDash1999** [comment]
good work @sanya031 

Will you be developing their code too?

**Comment by sanya031** [comment]
No just the design i'm afraid. Please let me know if ypu want my help in any other design related work for this website.

**Comment by AshutoshDash1999** [comment]
Ok @sanya031 let me know if the design is complete. We will then proceed with the pr then.

**Comment by sanya031** [comment]
@AshutoshDash1999 Only the light mode is left. I have completed the home page and the developers page and there is a 'coming soon' page on the designer's page till the plugin is developed

**Comment by AshutoshDash1999** [comment]
Ok Ok take your time.

**Comment by sanya031** [comment]
hey @AshutoshDash1999 Everything is done. You can check and let me know if there are any changes else we can merge this 

figma file - https://www.figma.com/file/XwQqLhjYKxub4uv1qjHgd4/bookingjini-website?type=design&node-id=0%3A1&mode=design&t=sTxy0KZwTwpVPrQg-1


https://github.com/Bookingjini-Labs/bookingjini-icons/assets/69260951/4ecdf22d-164b-4cb5-85ee-7f84d23e25f3

**Comment by AshutoshDash1999** [comment]
@sanya031  
1. Create a new folder and rename it as `New Website Design`.
2. Add a readme file there and add the figma links and add screenshot of every page there and make a pr
