### ISSUE TITLE
Creating figma plugin for the icon set 

### ISSUE THREAD

**Issue by sanya031** [Bookingjini-Labs/bookingjini-icons#59]
Creating a Figma plugin for this icon set will give the designers ( figma community/users) a helping tool when creating designs for the hospitality sector. The chances of using the icon set will increase as a Figma plugin

Please assign me this so I can create a figma plugin for your iconset.
Thank you 
sanya 
GSSOC 2023 contributor

**Comment by AshutoshDash1999** [comment]
This is a good issue. Can you please specify any charges for this? or is it free to publish? Also is there anything you want us to help you with that?

**Comment by sanya031** [comment]
It is free to create a Figma plugin. 
here is the official plugin guide link by figma- https://www.figma.com/plugin-docs/

if we don't want to pursue this, an alternative to this is creating a library of icon and publishing it on the Figma community page. We can use components and do it in a user friendly way. I can create the file. Or we can do both. 

Let me know which way you want to go

**Comment by AshutoshDash1999** [comment]
@sanya031 so for the Figma part do we have to create an account or something like that??

**Comment by sanya031** [comment]
Yes we can publish the library and plugin in **2 ways** 

1) I can create the library on my figma account share the file with you. You can duplicate it and publish it under your name. 
The plugin is to be coded so we can code on any system but will be uploaded for public use from your account only. 

2) You can create a figma account using your gmail, create a file and give me editing access. This way I can create the library in your account's file  and you can see the progress too by opening it. 

Either way you have to create an account under your name or bookingjini whatever is comfortable for you. 
**I think the 2nd method is easier.**

**Comment by AshutoshDash1999** [comment]
@bikidsx can you please take it forward from here

**Comment by AshutoshDash1999** [comment]
@sanya031 Please go forward with creating a plugin. We don't need a library as of now. Upload the code in this repo, we will then publish it from our account.

Will this work for you?

**Comment by AshutoshDash1999** [comment]
@sanya031 any update on this?

**Comment by AshutoshDash1999** [comment]
closing the issue since the assignee didn't give any  update
