### ISSUE TITLE
Sign and log in page 

### ISSUE THREAD

**Issue by kasturimandlik** [Bookingjini-Labs/bookingjini-icons#60]
I think there should be a sign in and login page for the website. This will enhance the user experience. It will help the user to safely access the information from the website by having their own personal space.
The Sign in page will collect all the required details like username, email address, password, Stream of the student, interested subjects, mobile number, etc.
The login page will have fields like username and password.
I can design the frontend part of sign in and log in page.
I would like to work on this issue under GSSOC'23.
Please assign me this issue

**Comment by AshutoshDash1999** [comment]
We don't want to create any database for users as it is open source and anybody can use it. So there's no point of adding a sign-in option for this type of project.

Anyway, thanks for checking out this repo. You are welcome to open any other issue. 😊
