### ISSUE TITLE
Adding a separate section for user to store their favourite icons. 

### ISSUE THREAD

**Issue by P10swati** [Bookingjini-Labs/bookingjini-icons#61]
Adding  a section of favorite icons would help the user to find their "used before" or "liked" icons easily. If you are okay with the idea, please assign me the issue I would like to work on this. gssoc'23

**Comment by AshutoshDash1999** [comment]
Although we don't want to handle any database for the "liked" icons, you are free to explore if you want to handle that using local storage.

During PR please mention the screenshot of what you have done.

Assigning you this issue.

**Comment by AshutoshDash1999** [comment]
Closed this due to inactivity.
