### ISSUE TITLE
[FEATURE] Sorting the Icons according to their genre and usage 

### ISSUE THREAD

**Issue by Kushdapush** [Bookingjini-Labs/bookingjini-icons#62]
Since the website has considerable number of icons, it takes some time to get an overview  of all the different types of icons.

To solve this problem, we can create multiple containers displaying a particular niche of types of icons that will make it easy for users to navigate through the website!

So I would like to work on making this possible under the Gssoc 2023!
Thank you!

**Comment by bookingjini** [comment]
> Kushdapush

Thank you, @Kushdapush, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by AshutoshDash1999** [comment]
@Kushdapush any update on this?

**Comment by Kushdapush** [comment]
Sir I am working on this, was occupied with some college exams. I will
surely come up with my best attempt till Sunday 4th of June

**Comment by Kushdapush** [comment]
@AshutoshDash1999 I have come up with something, I am attaching a screenshot of it , If you are satisfied with this the please do let me know

**Comment by Kushdapush** [comment]
![Screenshot (40)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/129064700/dc7b4f56-c4b9-4042-8101-8d1dc0432a40)

**Comment by AshutoshDash1999** [comment]
how will be the ui while searching?

**Comment by Kushdapush** [comment]
![Screenshot (41)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/129064700/69e57fa3-671c-4e5e-9d96-8c5e0839a786)

**Comment by Kushdapush** [comment]
It is getting a little bit messy. I will try to sort this as well

I will make a final pr of my work by tomorrow so please can we tackle this bug in the next issue 
I have streamlined the Icons data storing by creating separate .json files so that when our project scales up, storing huge data becomes relatively easy and rendering the icons becomes quick

**Comment by AshutoshDash1999** [comment]
@Kushdapush this is not how things work. You can't just push anything and assume that other developers would handle it. Please don't overdo things if not required.

**Comment by Kushdapush** [comment]
@AshutoshDash1999  I said that I will fix this as well! 
I wont push anything irresponsibly and spill it for others to complete 
there is some misunderstanding regarding this bug sir

**Comment by Kushdapush** [comment]
@AshutoshDash1999  pls reopen the issue

**Comment by AshutoshDash1999** [comment]
Ok please make sure your PR is efficient and keep simplicity as priority...It's not good practice to overdo complicated things.
