### ISSUE TITLE
[BUG] When switched to Light mode, the button still says 'Light Mode'

### ISSUE THREAD

**Issue by amrit2611** [Bookingjini-Labs/bookingjini-icons#65]
## Screenshots and description
![2](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/81375472/65517371-b615-4640-838e-8235c26fc13a)
![1](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/81375472/af40ca5f-39f8-47ef-8036-4d9cffd74996)

When switched to the light mode, the button should show 'Dark Mode' 

## Proposed solution
I would make sure that this bug is resolved and when we switch to dark mode, the button shows 'Light Mode' and when switched to light mode, the button shows 'Dark Mode'

Kindly assign me this issue under the GSSOC '23

**Comment by SomilDaswani** [comment]
Hey, I would like to solve this issue.
Kindly assign this issue to me under GSSOC'23

**Comment by himanshuaggar** [comment]
Hey, I would love to resolve this issue. please assign it to me. Thanks in advance.

**Comment by ivanMehvish** [comment]
I would love to resolve this issue. Kindly assign it to me under GSSoC'23.

**Comment by bookingjini** [comment]
@amrit2611  - The issue had already been addressed. Please feel free to investigate the repository for any additional issues that may require attention.

**Comment by amrit2611** [comment]
> @amrit2611  - The issue had already been addressed. Please feel free to investigate the repository for any additional issues that may require attention.

Sure
