### ISSUE TITLE
Add error 404 page

### ISSUE THREAD

**Issue by VC6378** [Bookingjini-Labs/bookingjini-icons#66]
Hey,
I would like to add an error 404 page to the website.
Thanks and regards,
Vibhuti Chandrakar.

**Comment by NehaKariya0309** [comment]
Hey,
I am also interested to work on the error page.
Thanks and regards,
Neha Kariya

**Comment by bookingjini** [comment]
Thank you, @VC6378, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by VC6378** [comment]
@bookingjini Since this page is a single-page website, I do not think there is a need of adding an error 404 page. But I have made an error 404 page, so if it is required please let me know.

**Comment by bookingjini** [comment]
@VC6378, we are eager to review the changes you have made. We value every small modification, as they are important to us. Please proceed with submitting a pull request (PR).

**Comment by PatilHarshh** [comment]
@bookingjini Please assign me this issue I want to work on this issue Asap !

**Comment by PatilHarshh** [comment]
@AshutoshDash1999 i want to work on this issue
