### ISSUE TITLE
"No Result Found" [GSSoC'23]

### ISSUE THREAD

**Issue by yashpreet2707** [Bookingjini-Labs/bookingjini-icons#68]
Please assign me this issue under GSSoC'23. I'd love to contribute to this project by solving this issue ( I've already figured it out )

<br>
It looks like this now

<img width="1440" alt="now" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/111020648/ef955410-94f4-44cf-9045-b1207d390917">

<br>
Suggested feature.

<img width="1440" alt="suggested" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/111020648/5d113b00-4bd9-4e71-8326-ae951731a7b1">

**Comment by bookingjini** [comment]
> yashpreet2707

Thank you, @yashpreet2707, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.
