### ISSUE TITLE
Icon Preview and Download Options

### ISSUE THREAD

**Issue by swati-sharma14** [Bookingjini-Labs/bookingjini-icons#69]
I would like to provide users the ability to preview icons in different sizes and formats before downloading. As soon as someone clicks an icon, they will be redirected to a new webpage where they'll see the icon in bigger size and from there they can download that icon.

**Comment by AshutoshDash1999** [comment]
this is a good idea. Instead of directing it to new page can you create a modal? please share the design on what you want to do

**Comment by swati-sharma14** [comment]
Sure. Should I first give you a prototype of the webpage which can be accounted as a contribution and then I will start working on it if it gets approved ?

**Comment by AshutoshDash1999** [comment]
@swati07sharma The design is part of this contribution. We don't expect an expert-level design...only a basic mockup. After approving you can work on that.

**Comment by swati-sharma14** [comment]
Cool. Thankyou !

**Comment by AshutoshDash1999** [comment]
Closed this due to inactivity.
