### ISSUE TITLE
Add scroll to top button

### ISSUE THREAD

**Issue by Laxmankohar** [Bookingjini-Labs/bookingjini-icons#70]
**Please describe the problem**
Why do you want to add this feature?
Adding a scroll-to-top button helps to enhance user experience, allowing visitors to easily navigate back to the top of a webpage without manually scrolling. This feature is especially useful for long or content-heavy pages. 

**Describe the solution you'd like**
I will be using HTML, CSS and javascript

**Screenshot**
Please attach any relevant screenshot(s).

Hey @bookingjini , I would like to work on this issue under GSSoc23. Can you assign it to me?

**Comment by bookingjini** [comment]
> Laxmankohar

@Laxmankohar - The issue had already been addressed. Please feel free to investigate the repository for any additional issues that may require attention.
