### ISSUE TITLE
Arrow icon name mismatching

### ISSUE THREAD

**Issue by Killer2OP** [Bookingjini-Labs/bookingjini-icons#71]
**Please describe the problem**
The names of arrow icon are mismatching.

**Describe the solution you'd like**
I can change the name and match them properly.
Assign me this under GSSoC'23

**Screenshot**
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/111378171/bd658b7e-2366-4d97-8a30-b1ff5f6b9252)

**Comment by bookingjini** [comment]
> Killer2OP

Thank you, @Killer2OP, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by vk20july** [comment]
@bookingjini sir can i do this task under gssoc'23
