### ISSUE TITLE
Social svg

### ISSUE THREAD

**Issue by Killer2OP** [Bookingjini-Labs/bookingjini-icons#72]
**Please describe the problem**
As I went through all the SVG Icons , I didn't saw any social svg icon(google , LinkedIn , Twitter , GitHub ,etc.)  
**Describe the solution you'd like**
So , I can add these svg icons in the website which will be very useful for the users.
Assign me this issue under GSSoC'23.
**Screenshot**
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/111378171/b0c6520a-36c0-4547-a6b4-182e35fbc035)

**Comment by AshutoshDash1999** [comment]
@Killer2OP We are not accepting new icons for now.
