### ISSUE TITLE
New color design through Figma

### ISSUE THREAD

**Issue by Ks103** [Bookingjini-Labs/bookingjini-icons#73]
**Please describe the problem**
As the website fonts and colors have to be much better for user interface so that website looks attractive.

**Describe the solution you'd like**
From designer aspect I can contribute this project and can make designs user friendly.
I request you to please assign me this project.

**Screenshot**
![Screenshot 2023-05-22 142121](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/86292101/0e9c8973-558b-40df-a463-6216a59e8e9a)

**Comment by bookingjini** [comment]
> Ks103

Thank you, @Ks103, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by Ks103** [comment]
I have upload the file please verify @bookingjini

**Comment by AshutoshDash1999** [comment]
@Ks103 have you submitted any PR?

**Comment by Ks103** [comment]
I have raised issues , also I request you @AshutoshDash1999 to please merge this issue for the little contribution I made into your repository.
Thankyou.

**Comment by AshutoshDash1999** [comment]
@Ks103 we can't merge an issue. You have to raise a PR then only we can see what you have done and then merge it.
