### ISSUE TITLE
Inconsistent or Breaking Navbar Elements

### ISSUE THREAD

**Issue by premsaivarmachekuri** [Bookingjini-Labs/bookingjini-icons#75]
Hi @AshutoshDash1999,  I wanted to bring to your attention an issue I discovered in our website's navigation bar. 
**Problem**
* Currently, the navbar elements on our website are displaying inconsistently or breaking in certain scenarios. This can lead to a poor user experience and may cause confusion for our website visitors.
* The purpose of addressing these issues is to improve the user experience and visuality of the website on different devices (specifically mobile and tablet/medium-sized devices).
* By fixing the inconsistent or breaking navbar elements and adjusting the placement of the Bookingjini Icons (v1.0) logo, Lightmode, and Download elements, we aim to provide a better user experience and ensure that the website functions optimally on various screen sizes and devices.
* The goal is to enhance the usability and visual appeal of the website, making it more user-friendly and accessible to a wider range of users.

**Describe the solution you'd like**
* Review the CSS styling and ensure that it is compatible with all major browsers and devices.
* Conduct thorough testing on different screen sizes, resolutions, and devices to identify any specific scenarios where the navbar elements are breaking or displaying inconsistently.
* Make necessary adjustments to the CSS code to fix the issues and ensure consistent display of navbar elements across all scenarios.
* Implement responsive design techniques to ensure that the navbar adapts well to different screen sizes and devices.

**Screenshot**
Mobile: 
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/110842297/80f1fbb0-fa7f-45bd-8de4-54646def0b0f)

Tablet:
![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/110842297/5e9bc6de-749a-4ac8-9852-432f58bea15f)

I am confident in my ability to tackle this problem as I have experience in addressing similar issues on various projects. I understand the importance of a consistent and user-friendly navigation experience, and I will be solving the issue under [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).

 I am excited to contribute to the project as part of GSSOC23 and look forward to contribute more to enhance the user experience of the website.

**Comment by AshutoshDash1999** [comment]
hi @premsaivarmachekuri I respect your time and effort that you have spent in writing this issue. But this issue is already covered in #22, so I can't assign it to you for now.

**Comment by premsaivarmachekuri** [comment]
Ok no problem. I will try to raise some more enhancements which were not
covered.
