### ISSUE TITLE
Add a scroll to top button

### ISSUE THREAD

**Issue by nishita2104** [Bookingjini-Labs/bookingjini-icons#76]
**Please describe the problem**
The page gets too long. 

**Describe the solution you'd like**
Adding a scroll to top function adds a functionality to make the site more professional.

**Comment by Ujjwal-soni98** [comment]
@AshutoshDash1999 Hey I can integrate the button. I want to work on it under GSSoC'23.
Kindly assign it to me!!

**Comment by Sandeep0306** [comment]
Hii, I want to add scroll to top button which will be easy to navigate to top of the page .Can you please assign it to me under GSSOC'23

**Comment by AshutoshDash1999** [comment]
Duplicate issue #35 
PR #52
