### ISSUE TITLE
Add separate sections for the category of the icon

### ISSUE THREAD

**Issue by vrishti29** [Bookingjini-Labs/bookingjini-icons#77]
**Please describe the problem**
Why do you want to add this feature?
right now, all the icons are just posted on the page

**Describe the solution you'd like**
group the icons according to various categories, this will make it easier for the user to search for a particular icon
**Screenshot**
Please attach any relevant screenshot(s).

**Comment by bookingjini** [comment]
> vrishti29

Thank you @vrishti29, for your response. - The issue had already been addressed in issue #62 . Please feel free to investigate the repository for any additional issues that may require attention.
