### ISSUE TITLE
modification in icon according to user requirement

### ISSUE THREAD

**Issue by vrishti29** [Bookingjini-Labs/bookingjini-icons#78]
hi, i am a gssoc'23 contributor. i would like to suggest some changes in your project.
1. add same icon in different styles
2. give the user color options in which they would like to use the icon

**Comment by bookingjini** [comment]
> hi, i am a gssoc'23 contributor. i would like to suggest some changes in your project.
> 
> 1. add same icon in different styles
> 2. give the user color options in which they would like to use the icon

Thank you, @vrishti29, for your prompt reply. Could you please share a prototype or design sample illustrating the changes you intend to contribute? This will help us better understand the modifications you wish to make to the repository.

**Comment by vrishti29** [comment]
> > hi, i am a gssoc'23 contributor. i would like to suggest some changes in your project.
> > 
> > 1. add same icon in different styles
> > 2. give the user color options in which they would like to use the icon
> 
> Thank you, @vrishti29, for your prompt reply. Could you please share a prototype or design sample illustrating the changes you intend to contribute? This will help us better understand the modifications you wish to make to the repository.

Could i share an image as of now? if you like it i can share a repo.

**Comment by AshutoshDash1999** [comment]
> Could i share an image as of now?

yes

**Comment by vrishti29** [comment]
> 

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/105159048/5d808267-cbf5-4cec-b74a-e6fcd766fb02)

like you can name a collection, for example "Dust Bins" and the collection will include all the different kinds of dustbins.

**Comment by AshutoshDash1999** [comment]
Ok @vrishti29 but we are not looking forward to add icons for now.
