### ISSUE TITLE
change the pointer to cursor ?

### ISSUE THREAD

**Issue by codewithnadeem14502** [Bookingjini-Labs/bookingjini-icons#80]
i think we need to make cursor so that user can think that logo is clickable. and i request you to assign me this issue. happy to work with you 
![icons](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/105824474/9bb2f345-20e1-48fc-a648-ec2bae3260a1)

**Comment by codewithnadeem14502** [comment]
shall i start the work ?

**Comment by bookingjini** [comment]
> i think we need to make cursor so that user can think that logo is clickable. and i request you to assign me this issue. happy to work with you ![icons](https://user-images.githubusercontent.com/105824474/239986031-9bb2f345-20e1-48fc-a648-ec2bae3260a1.png)

Thank you, @codewithnadeem14502, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by AshutoshDash1999** [comment]
@codewithnadeem14502 any update ??

**Comment by vk20july** [comment]
@AshutoshDash1999 sir can i do this task under gssoc'23

**Comment by AshutoshDash1999** [comment]
@vk20july @codewithnadeem14502 sorry we don't need this for now.
