### ISSUE TITLE
It's not a mobile responsive ?

### ISSUE THREAD

**Issue by codewithnadeem14502** [Bookingjini-Labs/bookingjini-icons#81]
i think adding mobile responsiveness to the webiste is mandatory in this modern days. i request you to please assgin me this issue . and i am happy to work with you
![mobile](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/105824474/6bc26381-4ebf-4393-8edf-b1556620aaa7)

**Comment by codewithnadeem14502** [comment]
shall i start the work ?

**Comment by bookingjini** [comment]
> i think adding mobile responsiveness to the webiste is mandatory in this modern days. i request you to please assgin me this issue . and i am happy to work with you ![mobile](https://user-images.githubusercontent.com/105824474/239986718-6bc26381-4ebf-4393-8edf-b1556620aaa7.png)

Thank you @codewithnadeem14502, for your response. - The issue had already been addressed in issue #22. Please feel free to investigate the repository for any additional issues that may require attention.
