### ISSUE TITLE
It's not tablet responsive 

### ISSUE THREAD

**Issue by codewithnadeem14502** [Bookingjini-Labs/bookingjini-icons#82]
i think adding tablet responsiveness to the website is mandatory in this modern days. i request you to please assgin me this issue . and i am happy to work with you
![tableimg](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/105824474/295c00f5-904c-4730-bb69-abed44722bf5)

**Comment by codewithnadeem14502** [comment]
shall i start the work ?

**Comment by bookingjini** [comment]
> i think adding tablet responsiveness to the website is mandatory in this modern days. i request you to please assgin me this issue . and i am happy to work with you ![tableimg](https://user-images.githubusercontent.com/105824474/239986941-295c00f5-904c-4730-bb69-abed44722bf5.png)

Thank you @codewithnadeem14502, for your response. - The issue had already been addressed in issue #22. Please feel free to investigate the repository for any additional issues that may require attention.
