### ISSUE TITLE
we can add a demo video ?

### ISSUE THREAD

**Issue by codewithnadeem14502** [Bookingjini-Labs/bookingjini-icons#83]
i think add the demo video will a good option to readme i will increase the user experience and i request you to please assign me this issue . and i am happy to work with you

**Comment by codewithnadeem14502** [comment]
shall i start the work ?

**Comment by KumariShaliniDwivedi** [comment]
please assign me for this work

**Comment by bookingjini** [comment]
> i think add the demo video will a good option to readme i will increase the user experience and i request you to please assign me this issue . and i am happy to work with you

Thank you, @codewithnadeem14502, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by codewithnadeem14502** [comment]
sure i will update you soon
