### ISSUE TITLE
modify Font, adding About US page, and Favicon

### ISSUE THREAD

**Issue by PrathamAsrani** [Bookingjini-Labs/bookingjini-icons#85]
**Please describe the problem**
#GSSOC23 | Contributor
Why do you want to add this feature?
1.     In professional website it is stated that to use Serif as the font for the headings and San Serif for paragraphs and text.
2.     In addition I want to add a about US page which shows the contact details also.
3.     and lastly a Great Logo will give a best look, I want to design a logo with favicon

**Describe the solution you'd like**
Solutions: 
1.     Updating fonts
2.     Creating About US + Contact US section page
3.     Creating Logo and Favicon

**Comment by RSN601KRI** [comment]
I'll do it also it's been a great experience to all, please assigned me .

**Comment by bookingjini** [comment]
> **Please describe the problem** #GSSOC23 | Contributor Why do you want to add this feature?
> 
> 1. ```
>    In professional website it is stated that to use Serif as the font for the headings and San Serif for paragraphs and text.
>    ```
> 2. ```
>    In addition I want to add a about US page which shows the contact details also.
>    ```
> 3. ```
>    and lastly a Great Logo will give a best look, I want to design a logo with favicon
>    ```
> 
> **Describe the solution you'd like** Solutions:
> 
> 1. ```
>    Updating fonts
>    ```
> 2. ```
>    Creating About US + Contact US section page
>    ```
> 3. ```
>    Creating Logo and Favicon
>    ```

Thank you, @PrathamAsrani, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by bookingjini** [comment]
@PrathamAsrani 
[Note- Point number 3 has already been resolved in the previous issue. Before proceeding any further, please take a moment to review the previous issues for reference.]

**Comment by PrathamAsrani** [comment]
Dear @bookingjini 
Thanks for assigning me this opportunity surely I will make a pull Request by 'June 10, 23', as per the COC of the repository.

**Comment by PrathamAsrani** [comment]
Dear team,
80 % of the work is completed(delay cause of exams), in upcoming 72hrs I will create a merge request.
regards,
Pratham Asrani

**Comment by AshutoshDash1999** [comment]
Closed this due to inactivity.
