### ISSUE TITLE
adding social media icons in web page

### ISSUE THREAD

**Issue by Amankumarharsh** [Bookingjini-Labs/bookingjini-icons#86]
I find that social media icons were not visible in web page , I want to add up it with functionality. I hope u will give me chance to contribute to this . I also connect the social media icons like instagram , facebook , linkedin with accounts of bookingjini.

**Comment by bookingjini** [comment]
> I find that social media icons were not visible in web page , I want to add up it with functionality. I hope u will give me chance to contribute to this . I also connect the social media icons like instagram , facebook , linkedin with accounts of bookingjini.

Thank you @Amankumarharsh, for your response. - The issue had already been addressed in issue #48. Please feel free to investigate the repository for any additional issues that may require attention.

**Comment by StutiShah01** [comment]
please assign me this issue. I want to work on it
