### ISSUE TITLE
Adding a Logo to the header-section

### ISSUE THREAD

**Issue by shagunZ** [Bookingjini-Labs/bookingjini-icons#87]
As part of enhancing the website's branding and visual identity, we need to add a logo to the header section of the website.
The logo will serve as a prominent visual element, reinforcing the brand presence across the page.
Kindly assign me this under GSSOC'23

**Comment by bookingjini** [comment]
> As part of enhancing the website's branding and visual identity, we need to add a logo to the header section of the website. The logo will serve as a prominent visual element, reinforcing the brand presence across the page. Kindly assign me this under GSSOC'23

Thank you, @shagunZ, for your response. You are welcome to continue with your code contribution. Please ensure that you follow the code standards and include a screenshot when submitting your pull request.

**Comment by shagunZ** [comment]
Hello Sir my PR has been successfully approved and merged into your project
. You have assigned my issue number #87 as level 3 gssoc but you haven't
assigned my approved PR with the level because of which points aren't
displayed on my gssoc leaderboard. Kindly look into the matter please. PR
number #91
Thanks & Regards
