### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by shraddha761** [Bookingjini-Labs/bookingjini-icons#88]
**Please describe the problem**
Why do you want to add this feature?

**Describe the solution you'd like**

**Screenshot**
Please attach any relevant screenshot(s).
![Screenshot 2023-05-21 160801](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/106100728/ff3d52ef-5505-469c-85e3-40702ace106c)

Adding this badges to readme makes it more attractive assign me this issue under GSSOC'23

**Comment by ramanujamgond** [comment]
I appreciate your response, @shraddha761. The update mentioned has already been put into effect. I encourage you to continue exploring for additional issues. Many thanks.
