### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by ImranNawar** [Bookingjini-Labs/bookingjini-icons#89]
Hi there!
I recommend adding a **CODE_OF_CONDUCT.md** file to your repository. This file would serve as a guide for potential contributors, providing them with a clear set of expectations, guidelines, and behavior standards for participating in your project. It plays an essential role in creating a welcoming and inclusive environment for everyone involved.

I would like to work on this issue. Please assign it to me under **<img width="660" alt="Screenshot 2023-05-23 153728" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/102653102/1949ade4-f34f-4190-8394-ea6bd7adc2e0">**.

Thank you!

**Comment by ramanujamgond** [comment]
Thank you @ImranNawar for your response. Feel free to proceed with your contribution and do provide a screenshot during the pull request.
