### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ImranNawar** [Bookingjini-Labs/bookingjini-icons#90]
Hi there!
I recommend adding a **CONTRIBUTING.md** file to your repository. This file would serve as a guide for potential contributors, outlining the project's contribution guidelines, coding conventions, and steps to follow when raising issues or submitting pull requests. It will help streamline the contribution process and provide clarity to newcomers.

I would like to work on this issue. Please assign it to me under  GSSoC'23.
**<img width="660" alt="Screenshot 2023-05-23 153728" src="https://github.com/Bookingjini-Labs/bookingjini-icons/assets/102653102/4b956dce-bb19-4ba4-b24c-fd50fd34bf20">**.

Thank you!

**Comment by bookingjini** [comment]
> Hi there! I recommend adding a **CONTRIBUTING.md** file to your repository. This file would serve as a guide for potential contributors, outlining the project's contribution guidelines, coding conventions, and steps to follow when raising issues or submitting pull requests. It will help streamline the contribution process and provide clarity to newcomers.
> 
> I would like to work on this issue. Please assign it to me under GSSoC'23. **<img alt="Screenshot 2023-05-23 153728" width="660" src="https://user-images.githubusercontent.com/102653102/240238793-4b956dce-bb19-4ba4-b24c-fd50fd34bf20.png">**.
> 
> Thank you!

Thank you @ImranNawar, for your response. - The issue had already been addressed in issue #38. Please feel free to investigate the repository for any additional issues that may require attention.

**Comment by ImranNawar** [comment]
Alright!

**Comment by ImranNawar** [comment]
Alright!
