### ISSUE TITLE
New page for customizing the icons

### ISSUE THREAD

**Issue by Srishti-1602** [Bookingjini-Labs/bookingjini-icons#92]
I am planning to add a new page for customizing the icons after clicking on them, 
the page will contain the option to save the icons in different format i.e svg, png etc and changing it's color.

Please assign this issue to me, and mark it under GSSoC'23

**Comment by ramanujamgond** [comment]
Thank you @Srishti-1602 for your response. Feel free to proceed with your contribution and do provide a screenshot during the pull request.

**Comment by Srishti-1602** [comment]
I am done with the customization part, but I am facing trouble with the SVG format copy.

**Comment by ramanujamgond** [comment]
@Srishti-1602, could you provide more details about your problem? It would be helpful if you could share your code or provide a sandbox where we can thoroughly investigate the issue.

@AshutoshDash1999, please take a look at this as well.

**Comment by Srishti-1602** [comment]
@ramanujamgond I will make a PR consisting the code, you can check the code over there.
And also it says that the download path is incorrect, what should be the path for the icons so that they can be downloaded.

**Comment by AshutoshDash1999** [comment]
@Srishti-1602 please don't push incomplete code or code with error

**Comment by AshutoshDash1999** [comment]
@Srishti-1602 please don't push incomplete PR. For the  SVG part, please check the console, it shows getIconFromURLParams  not defined
