### ISSUE TITLE
Color of "Bookingjini Icons (v1.0)" in light mode

### ISSUE THREAD

**Issue by Shreyans2004** [Bookingjini-Labs/bookingjini-icons#93]
**Please describe the problem**
Why do you want to add this feature?
The color of "Bookingjini Icons (v1.0)" in  light mode on hovering is not so much catchy .On the other hand in the dark mode it is looking fabulous but in light mode the blue color is not looking attractive due to light background.

**Describe the solution you'd like**
I can change the color of "Bookingjini Icons (v1.0)" in light mode so that it may look good in white background also.Can you assign this task to me?

**Screenshot**
Please attach any relevant screenshot(s).

**Comment by bookingjini** [comment]
> **Please describe the problem** Why do you want to add this feature? The color of "Bookingjini Icons (v1.0)" in light mode on hovering is not so much catchy .On the other hand in the dark mode it is looking fabulous but in light mode the blue color is not looking attractive due to light background.
> 
> **Describe the solution you'd like** I can change the color of "Bookingjini Icons (v1.0)" in light mode so that it may look good in white background also.Can you assign this task to me?
> 
> **Screenshot** Please attach any relevant screenshot(s).

Thank you @Shreyans2004, for your response. - The issue had already been addressed in issue #47. Please feel free to investigate the repository for any additional issues that may require attention.
