### ISSUE TITLE
No space between the text "Bookingjini Icons (v1.0)"  and Light moded in IPhone XR

### ISSUE THREAD

**Issue by Shreyans2004** [Bookingjini-Labs/bookingjini-icons#94]
**Please describe the problem**
Why do you want to add this feature?
There is no space between the  text "Bookingjini Icons (v1.0)"  and Light mode in IPhone XR.

**Describe the solution you'd like**
I can add the space between them so that they look better.Can you assign this task to me?

**Screenshot**
Please attach any relevant screenshot(s).

**Comment by bookingjini** [comment]
> Shreyans2004

Thank you @Shreyans2004, for your response. - The issue had already been addressed in issue #22. Please feel free to investigate the repository for any additional issues that may require attention.
