### ISSUE TITLE
Searchbar and hero section text is not reponsive in mobile device

### ISSUE THREAD

**Issue by crocmons** [Bookingjini-Labs/bookingjini-icons#95]
Searchbar and hero section text is not reponsive in mobile device..Can you assign this issue to me under GSSOC'23?

![Screenshot (335)](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/106610322/38fbe7c7-356d-49dd-850b-868da0330928)
**Please describe the problem**
Why do you want to add this feature?

**Describe the solution you'd like**

**Screenshot**
Please attach any relevant screenshot(s).

**Comment by RajeevDash007** [comment]
I would like to solve this issue

**Comment by crocmons** [comment]
Can you assign this issue to me under GSSOC'23?

**Comment by ramanujamgond** [comment]
Thank you @crocmons for your response. Feel free to proceed with your contribution and do provide a screenshot during the pull request.
