### ISSUE TITLE
Arranging the icons into different categories groups leading to easy differentiation.

### ISSUE THREAD

**Issue by SrishtiSonam** [Bookingjini-Labs/bookingjini-icons#96]
**Please describe the problem**
Then icons are arranged in alphabetically but unable to differentiate leading to difficulty to find the right one required.

**Describe the solution you'd like**
Arranging the icons in different category : first - alphabetically in the boxes for each alphabet and second - most used and related one. { Or any one of them }

**Screenshot**
![IMG-20230523-WA0009](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/113123593/2f8dbac7-6b04-42b4-9393-d22aef45385d)
like a pseudo representation of the website.

*********
Assign me this issue under gssoc'23

**Comment by ramanujamgond** [comment]
Thank you @SrishtiSonam for your response. Feel free to proceed with your contribution and do provide a screenshot during the pull request.

**Comment by Kushdapush** [comment]
hey @ramanujamgond  I am assigned this issue already (issue#62) so wont this lead to merge conflict

**Comment by SrishtiSonam** [comment]
Dear @ramanujamgond ,

I want to sincerely apologize for not being able to resolve the issue I raised #96. I understand the frustration and inconvenience this may have caused you. 

After thoroughly investigating the problem and considering various approaches other than mine, I regret to inform you that I was unable to find a suitable solution within the given constraints. I genuinely appreciate your effort of giving attention to my idea and I'm sorry that I couldn't meet the expectations in this case.

Please know that I value your feedback and the opportunity to learn from this experience. I will make sure to keep this issue in mind for future improvements and enhancements. If there are any other ways I can be of assistance, please do let me know.

Thank you for your understanding and patience. Once again, I apologize for any inconvenience caused.

**Comment by bookingjini** [comment]
I appreciate your time and effort, @SrishtiSonam, in addressing the issue you brought up. It's all part of the developer journey, so please don't worry. You can always search for another issue to work on and resolve. That being said, I will now proceed to close the issue you raised.
