### ISSUE TITLE
we can animate the Text ?

### ISSUE THREAD

**Issue by codewithnadeem14502** [Bookingjini-Labs/bookingjini-icons#97]
instead of this plain text we  can have animation of text like typing effect. please assign me this issue. i am happy to work with you 

![Screenshot 2023-05-24 011222](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/105824474/aa9f91e6-621f-4886-8608-5c447f23248e)

**Comment by ramanujamgond** [comment]
Thank you @codewithnadeem14502 for your response. Feel free to proceed with your contribution and do provide a screenshot during the pull request.

**Comment by codewithnadeem14502** [comment]
Sure sir soon I am going to start working this

**Comment by codewithnadeem14502** [comment]
created a PR please have a look
