### ISSUE TITLE
change the text of the light&dark mode toggle button

### ISSUE THREAD

**Issue by riddhigupta1110** [Bookingjini-Labs/bookingjini-icons#98]
**Please describe the problem**
After we switch to light mode, the mode toggle button needs to show 'Dark Mode' to move from light mode to dark mode but instead it remains as 'Light Mode'. It will enhance the user experience and make it easier for the user to toggle between the two modes.

**Describe the solution you'd like**
After switching to light mode, the text on the button should read 'Dark Mode'. 

**Screenshot**
![dark-mode button](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/112184998/7b5397a8-ea52-44dd-944f-a6bdaa41e75c)
![light-mode button](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/112184998/115417db-afcc-4a98-9257-29ec1b54c881)

**Comment by ramanujamgond** [comment]
Thank you @riddhigupta1110 for your response. Feel free to proceed with your contribution and do provide a screenshot during the pull request.

**Comment by riddhigupta1110** [comment]
Sure, I'll remember to add a screenshot during the Pull Request

**Comment by riddhigupta1110** [comment]
It seems like the changes have already been made by someone else.
