### ISSUE TITLE
make the text responsive and readable

### ISSUE THREAD

**Issue by riddhigupta1110** [Bookingjini-Labs/bookingjini-icons#99]
**Please describe the problem**
The text 'Bookingjini Icons' isn't responsive. The text 'Find hospitality related icons, curated by creators from Bookingjini' isn't readable in light mode. 

**Describe the solution you'd like**
The font size should decrease as we decrease the screen size. Also, we could remove the full stop at the end of Bookingjini icons.
The text color of the text 'Find hospitality related icons, curated by creators from Bookingjini' is too light for reading in light mode - I could change it to a darker color.

**Screenshot**
![not-responsive](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/112184998/23073c3f-0c64-4b9c-9932-5c0cf69dcb6e)

![light_text](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/112184998/ec06fa28-1df6-4629-88e5-16cf088c5b24)

**Comment by Amankumarharsh** [comment]
pls assign this issue to me as I done this in my previous project.  I can do this more efficiently.
